<?php $testimonial=$this->getTestimonial(); ?>
<div class="customer-testimonials">
	<div class="page-title">
		<h1><?php echo $this->__('Customer Testimonials');?></h1>
        <?php if(Mage::getStoreConfig('testimonial/testimonial_options/allow_customers_write_testimonial') == 1):?>
		<div class="submit-testimonial">
				<!--button class="button" onclick="setLocation('<?php echo $this->getFormUrl(); ?>')"-->
				<button class="button" onclick="setLocation('<?php echo $this->getUrl('testimonial/form/'); ?>')">
					<span>
						<span>
							<?php echo $this->__('Submit Your Testimonial');?>					
						</span>
					</span>
				</button>
		</div>
        <?php endif ?>
    </div>
	<?php echo $this->getPagerHtml();?>
	<?php if ($testimonial->getSize()): ?>
		<?php $i==0; foreach ($testimonial as $obj):?>
			<?php if($obj->getStatus()==1): ?>
			<div class="customer-testimonials-content<?php if($i==0):?> first<?php endif;?><?php if($i==(count($testimonial)-1)):?> last<?php endif;?>" name="<?php echo $obj->getName(); ?>" id="<?php echo $obj->getName(); ?>">
				
				
				<div class="testimonial-source">
					<span class="testimonial-author"><?php echo $obj->getName(); ?></span>
					<span class="testimonial-date testimonial-state">
						<?php echo $obj->getAddress();//echo date('F d, Y', Mage::getModel('core/date')->gmtTimestamp($obj->getCreatedTime())); ?>
					</span>
					<span class="testimonial-date">
						<?php if(date('Y',strtotime($obj->getCreatedTime()))!="-0001") {
							echo date('M d, Y',strtotime($obj->getCreatedTime()));
						} ?></span>
				</div>
				<div class="testimonial-content">
                    <div class="testimonial-content-avatar">
                        <?php
                            if($obj->getAvatarName() != ''){
                                $avatarLink = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'magebuzz/avatar/'.$obj->getAvatarName();
                                ?><img src="<?php echo $avatarLink ?>" alt="test" height="120" width="120" /><?php
                            }
                        ?>
                    </div>
                    <span class="more buttonset-readmore" >
						<?php echo $obj->getTestimonial();?>
					</span>
				</div>
				<div id="ratingBox">
				<?php
				$count = 5;
				// echo $obj->getRating();
				for($i=1; $i<=$count; $i++) {
				?><div class="rateDiv <?php if($i<=$obj->getRating()) echo "rateActive" ?>" id="rateThis_<?php echo $i ?>" ></div><?php //echo $i;
				}
				?>
				</div>
				<!-- <div class="buttonset-readmore"><a href="">Read more</a></div> -->
			</div>
			<?php endif ?>
			<?php $i++; ?>
		<?php endforeach;?>
		<?php echo $this->getPagerHtml(); ?>
	<?php else: ?>
		<p class="note-msg"><?php echo $this->__('There is no testimonial submitted.'); ?></p>
	<?php endif ?>
</div>
<script type="text/javascript">
	jQuery(document).ready(function() {
    // Configure/customize these variables.
    var showChar = 200;  // How many characters are shown by default
    var ellipsestext = " ....";
    var moretext = "Read more";
    var lesstext = "Read less";
    jQuery('.more').each(function() {
        var content = jQuery(this).html(); 
        if(content.length > showChar) { 
            var c = content.substr(0, showChar);
            var h = content.substr(showChar, content.length - showChar); 
            var html = c + '<span class="moreellipses"><span class="dot_color">' + ellipsestext+ '</span>&nbsp;</span><span class="morecontent"><span>' + h + '</span>&nbsp;&nbsp;<a href="" class="morelink">' + moretext + '</a></span>'; 
            jQuery(this).html(html);
        } 
    });
    jQuery(".morelink").click(function(){
        if(jQuery(this).hasClass("less")) {
            jQuery(this).removeClass("less");
            jQuery(this).html(moretext);
        } else {
            jQuery(this).addClass("less");
            jQuery(this).html(lesstext);
        }
        jQuery(this).parent().prev().toggle();
        jQuery(this).prev().toggle();
        return false;
    });
});
</script>