<div class="banner_sec">
	<div class="drug_search_area">
		<?php echo $this->getLayout()->createBlock("core/template")->setTemplate("homepage/drugsearch.phtml")->toHtml();?>
	</div>
	<!-- <div class="banner_area"> -->
		<!-- <img src="<?php echo $this->getSkinUrl('images/home/adc_banner.jpg'); ?>" alt="AllDayChemist" class="fleft"/> -->
		<!-- <h1>Simply a better
pharmacy!</h1>
		<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
		<a href="" class="banner_btn"><span>Learn More</span></a> -->
	<!-- </div> -->
	<ul id="slides1">
			<li>
				<div class="banner_area"> 
					<!-- <img src="<?php echo $this->getSkinUrl('images/home/adc_banner.jpg'); ?>" alt="AllDayChemist" class="fleft"/> -->
					<h1>Simply a better pharmacy!</h1>
					<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
					<a href="" class="banner_btn"><span>Learn More</span></a>
				</div>
				<div class="clear"></div>
			</li>
			<li>
				<div class="banner_area"> 
					<!-- <img src="<?php echo $this->getSkinUrl('images/home/adc_banner.jpg'); ?>" alt="AllDayChemist" class="fleft"/> -->
					<h1>Simply a better pharmacy!</h1>
					<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
					<a href="" class="banner_btn"><span>Learn More</span></a>
				</div>
				<div class="clear"></div>
			</li>
			<li>
				<div class="banner_area"> 
					<!-- <img src="<?php echo $this->getSkinUrl('images/home/adc_banner.jpg'); ?>" alt="AllDayChemist" class="fleft"/> -->
					<h1>Simply a better pharmacy!</h1>
					<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
					<a href="" class="banner_btn"><span>Learn More</span></a>
				</div>
				<div class="clear"></div>
			</li>
			<li>
				<div class="banner_area"> 
					<!-- <img src="<?php echo $this->getSkinUrl('images/home/adc_banner.jpg'); ?>" alt="AllDayChemist" class="fleft"/> -->
					<h1>Simply a better pharmacy!</h1>
					<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
					<a href="" class="banner_btn"><span>Learn More</span></a>
				</div>
				<div class="clear"></div>
			</li>
	</ul>
</div>
<div class="clearSty"></div>
<?php echo $this->getLayout()->createBlock("core/template")->setTemplate("homepage/adc_banner_below.phtml")->toHtml();?>