<style>
.cms-calendar h1 { margin-bottom: 15px; font-size: 22px; }
.cms-calendar #category_bottom_description_footer { display: none;}
</style>
<h1>2015 AllDayChemist e-Calendar</h1>
<p>We at AllDayChemist really appreciate the trust and faith you have placed in us over the years. To show our gratitude we have come up with a calender with a health theme so you can keep taking care of yourself and your family as the year progresses. We at AllDayChemist wish you a very healthy and uplifting year ahead!</p>
<center><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/calendar_image.jpg' ?>" alt="" /></center>
<p>&nbsp;</p>
<center>
<div class="buttons-set"><button style="float:none;" class="button button1" title="Download e-Calendar" onclick="var win=window.open('http://www.alldaychemist.com/ADC_calendar_2015.pdf', '_blank'); win.focus();" type="button"><span><span>Download e-Calendar&nbsp;</span></span>&nbsp;</button></div>
</center>
<p>&nbsp;</p>
<p style="font-size: 12px; color: #ee6363;">*Please note - The holidays are for information purpose only and AllDayChemist doesn't take responsibility in the authenticity of the mentioned holidays in the e-Calendar.</p>