<?php 

$model = Mage::getModel('homepagebanner/homeslider')->getCollection();
// echo '<pre>';
// print_r($model->getData());
$mediaurl=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
?>
<div class="banner_sec">
	<ul id="slides1">

<?php 
foreach ($model->getData() as $banner) {
	// print_r($banner);
	$url = $banner['url'];
	if (!parse_url($url, PHP_URL_SCHEME)) {
		$url = 'http://' . $url;
	}
	$imagesrc = $mediaurl.''.$banner['image'];
	echo '<li>	<div class="adc_banner_area"> ';
	echo '<a href="'.$url.'">';
	echo '<img src="'.$imagesrc.'" alt="'.$banner['name'].'" />';
	echo '</a>';
	echo '</div><div class="clear"></div></li>';
}
?>
