<?php 

//Get Visitor's information  
  $visitorData = Mage::getSingleton('core/session')->getVisitorData();  

  // printing visitor information data  
  // echo "<pre>"; print_r($visitorData); echo "</pre>";  
  // echo '<br/>';
  // // user's ip address (visitor's ip address)  
  // echo $remoteAddr = Mage::helper('core/http')->getRemoteAddr(true);  
  //  echo "<pre>"; print_r($remoteAddr); echo "</pre>";  
  // echo '<br/>';

  // // server's ip address (where the current script is)  
  // echo $serverAddr = Mage::helper('core/http')->getServerAddr(true);  
  //  echo "<pre>"; print_r($serverAddr); echo "</pre>";  
  // echo '<br/>';
   $ipaddress = '';
    if ($_SERVER['HTTP_CLIENT_IP'])
        $ipaddress = $_SERVER['HTTP_CLIENT_IP'];
    else if($_SERVER['HTTP_X_FORWARDED_FOR'])
        $ipaddress = $_SERVER['HTTP_X_FORWARDED_FOR'];
    else if($_SERVER['HTTP_X_FORWARDED'])
        $ipaddress = $_SERVER['HTTP_X_FORWARDED'];
    else if($_SERVER['HTTP_FORWARDED_FOR'])
        $ipaddress = $_SERVER['HTTP_FORWARDED_FOR'];
    else if($_SERVER['HTTP_FORWARDED'])
        $ipaddress = $_SERVER['HTTP_FORWARDED'];
    else if($_SERVER['REMOTE_ADDR'])
        $ipaddress = $_SERVER['REMOTE_ADDR'];
    else
        $ipaddress = 'UNKNOWN';
    print_r($ipaddress);exit();
?>