<script type="text/javascript">

jQuery(document).ready(function() {
	jQuery('.read_more_content').css({'font-weight':'bold'});
	jQuery('.less_content_para').css({'font-weight':'bold'});
	jQuery('.content_para').hide();
	jQuery('.read_more_content').click(function (){
		//alert('.'+this.id);
		jQuery('.'+this.id).slideDown( "slow" );
		jQuery('#'+this.id).hide();
	});

	jQuery('.less_content_para').click(function (){
		//alert('.'+this.id);
		var class_string = this.id;
		var strarray = class_string.split('_');
		console.log(strarray);
		var newidforless = strarray[1]+'_'+strarray[2];
		jQuery('.'+newidforless).slideUp( "slow" );
		// jQuery('#'+this.id).css({'display':'none'});
		// jQuery('.read_more_content').css({'display':'block'});
		jQuery('.read_more_content').show();
	});

});
</script>

<div class="home-content">
	<h1>We are all day chemist</h1>
	<p class="content_heading"><h2>Welcome to AllDayChemist - it’s your pharmacy </h2></p>
	<p class="content">Welcome User. Please see our Terms and Conditions before you start with shopping on our site.</p>

	<p class="content">AllDayChemist is one of the leading online pharmacies specializing in providing generic and OTC products. All of our products are compatible and consistent with FDA standards, and they are manufactured by reputed manufacturers. We usually supply a 90-day supply of drugs; however, we will also supply generic medicines as per the quantity needed by our customers for personal use.</p>

	<p class="content">Our generic drugs are identical in their pharmaceutical and chemical compositions as compared to their U.S. counterparts; also there are no hidden charges involved in the drug and medicines prices.
	<a id="content_para1" class="read_more_content">Read More</a></p>

	<div class="content_para1 content_para">

			<p class="content">AllDayChemist is one of those online chemist whose endeavor is to simplify your search for generic medicines. You can either search by Brand-Name or search by Generic Name before you decide on buying medicine online. You can also mention the desired quantity of drugs required and check-out after providing us with the required information. We intend to become the best online pharmacy through concentrated efforts towards community service in the form of affordable medicines.</p>

			<p class="content"><b>Please note that your online drug transaction will be considered valid after we receive a fax or scanned copy of your prescription.</b></p>

			<p class="content">We expect our site visitors to be at least 21 years of age and we encourage our customers to keep themselves informed about their respective country’s laws related to online pharmacies and import of generic drugs for personal use.</p>

			<p class="content"><b>AllDayChemist assumes no legal responsibility for those not in compliance with such guidelines regarding the import of generic drugs.</b></p>

			<p class="content">AllDayChemist has been serving the community worldwide since 2000. Our internal audit teams ensure that our processes are aligned with our mission while serving the community with reliability and integrity. We believe in consumer satisfaction and strive to ensure there are no delays in delivery. In case a consumer experiences delay in the arrival of the consignment of generic drugs, we ship the consignment at absolutely no cost to the customer.</p>

			<p class="content"><b>Buy prescription drugs and health care products from your favorite online chemist – AllDayChemist, without paying any extra or hidden charges.</b>
			</p>
			<a id="less_content_para1" class="less_content_para content"><span class="less_space">Less</span></a></p>
		</div>

		<h1>Why Choose AllDayChemist?</h1>
		<p class="content">We believe in directing our skills and expertise in delivering and developing quality, in online pharmacy services which is not gained by accident. Our promise to deliver and maintain the present quality of work forms the basis of our work philosophy, a claim endorsed by online pharmacy reviews.</p>

		<p class="content">We believe that as we develop our work quality we will be one step closer to helping you enrich your lives with good health and happiness. We wish to see our consumers to live life filled with long life and comforts. This is AllDayChemist’s commitment towards the community.</p>


		<p class="content_heading"><h2>Hassle-free service:</h2></p>
		<p class="content">Our home delivery service provides utmost convenience to help you order drugs online  without compromising on time and quality. Along with being well-recognized for dispersing high quality drugs inexpensively, we offer hassle-free services to our valued customers. For those requesting privacy of order, the consignments are sent in small bubble envelopes or card boxes for the same.</p>


		<p class="content_heading"><h2>Savings and Safety</h2></p>
		<p class="content">At AllDayChemist, we purchase our medicines from only the best and respected manufacturing companies. We practice hygiene measures to make sure all the drugs are safely placed in suitable conditions. We at AllDayChemist do not compromise drug quality for the sake of discounted price. We encourage you to buy drugs online as it saves both time and energy. If a product is damaged during the transit we ensure a new package is immediately dispatched.</p>

		<p class="content_heading"><h2>Best buy at best prices:</h2></p>
		<p class="content">We at AllDayChemist aim to provide you with a 100% Satisfaction Guarantee. We live by the adage of healthy life and affordable medical expenses. You can buy drugs online by paying us through check/money orders, or credit cards. We have made lives easier with our easy to use search engines that will help you find and buy medicine online. You can also avail the various exciting offers that are always ongoing at our store.
		<a id="content_para3" class="read_more_content">Read More</a></p>

		<div class="content_para content_para3">
		<p class="content">If you order drugs online from us and it does not reach you or is damaged in transit, we quickly arrange to ship another package. Due to circumstantial factors if that is not possible, we offer a full refund. <a id="less_content_para3" class="less_content_para"><span class="less_space">Less</span></a></p>
		</div>

		<p class="content_heading"><h2>Manufacturers:</h2></p>
		<p class="content">We order our drugs from reputed international manufacturers and are made available for sale after careful scrutiny of the quality. This way we can spend more time and efforts to help you when you buy medicine online. These drugs sold in other countries are known by other brand names, but generically they are the same drugs.
		<a id="content_para4" class="read_more_content">Read More</a></p>
		<div class="content_para4 content_para" >
		<p class="content">AllDayChemist orders their drugs from reputed manufacturing companies in India. Some of these companies are:</p>
		<p class="content">
			<ol>
			<li class="content">Ranbaxy Laboratories Ltd.</li>
			<li class="content">Cipla Ltd.</li>
			<li class="content">Dr. Reddy'S Laboratories Ltd.</li>
			<li class="content">Nicholas Piramal India Ltd.</li>
			<li class="content">Aurobindo Pharma Ltd.</li>
			<li class="content">Glaxosmithkline Pharmaceuticals Ltd.</li>
			<li class="content">Lupin Ltd.</li>
			<li class="content">Cadila Healthcare Ltd.</li>
			<li class="content">Sun Pharmaceutical Inds. Ltd.</li>
			<li class="content">Wockhardt Ltd.</li>
			<li class="content">Aventis Pharma Ltd.</li>
			<li class="content">Orchid Chemicals & Pharmaceuticals Ltd.</li>
			<li class="content">Ipca Laboratories Ltd.</li>
			<li class="content">Alembic Ltd.</li>
			<li class="content">Pfizer Ltd.</li>
			<li class="content">Morepen Laboratories Ltd.</li>
			<li class="content">U S V Ltd.</li>
			<li class="content">Matrix Laboratories Ltd.</li>
			<li class="content">Biocon Ltd.</li>
			<li class="content">Novartis India Ltd.</li>
			<li class="content">Torrent Pharmaceuticals Ltd.</li>
			<li class="content">Abbott India Ltd.</li>
			<li class="content">Cadila Pharmaceuticals Ltd.</li>
			<li class="content">Merck Ltd.</li>
			<li class="content">Unichem Laboratories Ltd.</li>
			<li class="content">Glenmark Pharmaceuticals Ltd.</li>
			<li class="content">Wyeth Ltd.</li>
			<li class="content">Divi'S Laboratories Ltd.</li>
			<li class="content">J B Chemicals & Pharmaceuticals Ltd.</li>
			<li class="content">F D C Ltd.</li>
			<li class="content">Emcure Pharmaceuticals Ltd.</li>
			<li class="content">Panacea Biotec Ltd.</li>
			<li class="content">Strides Arcolab Ltd.</li>
			<li class="content">Shasun Chemicals & Drugs Ltd.</li>
			<li class="content">Elder Pharmaceuticals Ltd.</li>
			<li class="content">Macleods Pharmaceuticals Ltd.</li>
			<li class="content">Aarti Drugs Ltd.</li>
			<li class="content">Dabur Pharma Ltd.</li>
			<li class="content">Nectar Lifescience Ltd.</li>
			<li class="content">Ind-Swift Ltd.</li>
			<li class="content">Astrazeneca Pharma India Ltd.</li>
			<li class="content">Unimark Remedies Ltd.</li>
			<li class="content">Jagsonpal Pharmaceuticals Ltd.</li>
			<li class="content">Organon (India) Ltd.</li>
			<li class="content">Surya Pharmaceutical Ltd.</li>
			<li class="content">Ind-Swift Laboratories Ltd.</li>
			<li class="content">Kopran Ltd.</li>
			<li class="content">K D L Biotech Ltd.</li>
			<li class="content">T T K Healthcare Ltd.</li>
			<li class="content">Neuland Laboratories Ltd.</li>
			</ol>
		<a id="less_content_para4" class="less_content_para"><span class="less_space">Less</span></a></p>
		</div>

		<p class="content_heading"><h2>Our Community</h2></p>
		<p class="content">You can subscribe to our newsletter to be up to date with our inflow of information, new products and medications. Creating an account with us will facilitate faster checkouts, store multiple shipping addresses and check the status of your order online through the order tracker facility. Your Wishlist is our Command!</p>

		<p class="content_heading"><h2>Information:</h2></p>
		<p class="content">Along with supplying the best medicines, our website has a host of information on an eclectic set of topics in form of our blogs that will give you a better perspective on your medicines. When buying medications it will become easy to know your order before placing it. Also, with each of our medications we offer extensive product review. There is also space provided for User reviews.</p>

		<p class="content_heading"><h2>Reliability:</h2></p>
		<p class="content">AllDayChemist strongly believes in maintaining patient's privacy. In case the delivery is not made on time, is misplaced or damaged; a replacement or full refund is given. At AllDayChemist, we deliver in two-three weeks.
		<a id="content_para5" class="read_more_content">Read More</a></p>
		<div class="content_para5 content_para" >
			<p class="content">We host our site not just for commercial gains, but also to educate and spread awareness about healthy living. Stay up-to-date with various health related articles with the help of our blog.</p>
			<p class="content">Other than medications to counter almost every disease, we also sell supplements and drugs for beauty and health, weight loss and more.
			<a id="less_content_para5" class="less_content_para"><span class="less_space">Less</span></a></p>
		</div>

		<p class="content_heading"><h2>Medications</h2></p>
		<p class="content">We offer medicines for a host of ailments and diseases at our online pharmacy. We offer medications at discounted prices for various ailments, diseases, and deficiency. These include medicines and products for Epilepsy, Cancer, Diabetes, Infertility, Migraine, Alzheimers, HIV, Herpes, and Blood pressure. We also have a section dedicated to beauty and skin care products. It includes Gels, Fairness creams, careprost, hair fall solutions, serums as well as syrups and medication for skin and hair health.
		<a id="content_para6" class="read_more_content">Read More</a></p>
		<div class="content_para6 content_para" >
			<p class="content">We have dedicated categories in our site to simplify your search. The categories have been named after the ailments they are intended to target.
			<a id="less_content_para6" class="less_content_para"><span class="less_space">Less</span></a></p>
		</div>

		<p class="content_heading"><h2>Health Supplements</h2></p>
		<p class="content">Modern lifestyle has rendered regular meals inefficient in supplying our bodies with the required nutrients. We may have to include supplements in our diets to meet our body’s dietary needs. Get all the nutrition that you require with a little help of supplements. Here at AllDayChemist, we offer the best supplements for both men and women. You can refer to our blogs for more information on a given subject.</p>

		<p class="content_heading"><h2>Referral programme</h2></p>
		<p class="content">If want to join us and contribute in our efforts towards helping the community lead a healthy and happy life, then you can join our referral program. To know more, send mail at david@alldaychemist.com and we will guide you further.</p>

</div>





