
<?php 
// print_r(Mage::app()->getFrontController()->getRequest());

//getRouteName
if( Mage::registry('current_category')):
$currentCategory = Mage::registry('current_category')->getId(); //get current id of the category
$parentCategory = Mage::getModel('catalog/category')->load($currentCategory); //find the parent of the current category id
$parentCategoryId = $parentCategory->getData('parent_id');
$configcategory_id = Mage::getStoreConfig('general/herbalcategory/category_id',Mage::app()->getStore());
$configId = explode(',',Mage::getStoreConfig('general/herbalcategory/herbal_category_ids',Mage::app()->getStore()));

// $configId = $configarray;
if(in_array($currentCategory, $configId) || ($currentCategory==$configcategory_id)): //check if parent id is present in arry or not 

?>
<!-- Start of Left Navigation for Herbal Category -->
<div id='cssmenu'>
  <div class="block">
    <div class="block-title">
        <a href="<?php echo Mage::getBaseUrl();?>herbal.html"><strong><span>Herbal</span></strong></a>
    </div>
      <div class="block-content">
      <ul class="harbal_links">
    <?php 
    $_rootCatId     = $configcategory_id;
    $_rootCategory  = Mage::getModel('catalog/category')->load($_rootCatId);
    $_catName       = $_rootCategory->getName();
    if($_rootCategory->hasChildren()) 
    {
    $_collection = Mage::getResourceModel('catalog/category_collection')
                    ->addAttributeToFilter('is_active', 1)
                    ->addAttributeToSort('position', 'asc')
                    ->joinUrlRewrite();

    $_iterateCollection =$_collection->addIdFilter($_rootCategory->getChildren())->load();

    foreach($_iterateCollection AS $_sub)
    {
        $_subCat    = Mage::getModel('catalog/category')->load($_sub->getId());

        if($_subCat->hasChildren()) 
        {   
            echo '<li class="leve10 nav-'. $_subCat->getId() .'">';
                echo '<a id="subCatLink" href="'. $_subCat->getUrl() .'">';
                    echo '<span>'. $this->htmlEscape($_subCat->getName()) .'</span><span class="arrowname"></span>
                    </a>';
        
            echo '<ul id="subCatUl" style="">';
            $__collection = $_collection->addIdFilter($_subCat->getChildren())->load();

            foreach($__collection AS $__sub)
            {

                $__subCat   = Mage::getModel('catalog/category')->load($__sub->getId());
                if($currentCategory==$__subCat->getId()){
                  $status =  'current_category';
                }else{
                  $status = '';
                }
                echo '<li class="leve20 nav-'. $__subCat->getId() .' '.$status.'">
                        <a href="'. $__subCat->getUrl() .'">
                         <span>'. $this->htmlEscape($__subCat->getName()) .'</span>
                        </a>
                     </li>';
            }
            echo '</ul></li>';
        }
        else
        {
            echo '<li class="leve10 nav-'. $_subCat->getId() .'">
                <a href="'. $_subCat->getUrl() .'">
                 <span>'. $this->htmlEscape($_subCat->getName()) .'</span>
                </a>
             </li>';
        }
    }
    }
    ?>
    </ul>
    </div>
  </div>
</div>

<style type="text/css">

#cssmenu ul ul {
  display: none;
}
</style>

<script type="text/javascript">
jQuery(document).ready(function($){

  //  $('#cssmenu > ul > li ul').each(function(index, element){
  //    var count = $(element).find('li').length;
  //    var content = '<span class="cnt">' + count + '</span>';
  //    $(element).closest('li').children('a').append(content);
  // });
   $('#cssmenu ul ul li:odd').addClass('odd');
   $('#cssmenu ul ul li:even').addClass('even');
   $('#cssmenu > ul > li > a').click(function() {

     var checkElement = $(this).next();
     $('#cssmenu li').removeClass('active');
     $('#cssmenu li .arrowname').removeClass('arrow_top'); 
     $(this).closest('li').addClass('active'); 
     $(this).closest('li').find(".arrowname").addClass('arrow_top'); 

     if((checkElement.is('ul')) && (checkElement.is(':visible'))) {
       $(this).closest('li').removeClass('active');
       $(this).closest('li').find(".arrowname").removeClass('arrow_top');
       checkElement.slideUp('normal');
    }
    if((checkElement.is('ul')) && (!checkElement.is(':visible'))) {
       $('#cssmenu ul ul:visible').slideUp('normal');
       checkElement.slideDown('normal');
    }

    if($(this).closest('li').find('ul').children().length == 0) {
       return true;
    } else {
       return false; 
    }

 });


   $('#cssmenu > ul > li > a > ul > li > a').click(function() {

     var checkElement = $(this).next();
     $('#cssmenu li').find(".arrowname").removeClass('arrow_top');
     $('#cssmenu li').removeClass('active');
     $(this).closest('li').find(".arrowname").addClass('arrow_top'); 
     $(this).closest('li').addClass('active'); 

     if((checkElement.is('#cssmenu ul')) && (checkElement.is(':visible'))) {
       $(this).closest('li').removeClass('active');
       $(this).closest('li').find(".arrowname").removeClass('arrow_top');
       checkElement.slideUp('normal');
     }
     if((checkElement.is('#cssmenu ul')) && (!checkElement.is(':visible'))) {
       $('#cssmenu ul ul:visible').slideUp('normal');
       checkElement.slideDown('normal');
     }

     if($(this).closest('li').find('ul').children().length == 0) {
       return true;
     } else {
       return false; 
     }

   });

   // jQuery code goes here!
   var current_cat = '<?php echo $parentCategoryId;?>';
   jQuery('.nav-'+current_cat).addClass('active');
   jQuery('.nav-'+current_cat).find(".arrowname").addClass('arrow_top');
   jQuery('.nav-'+current_cat+' ul').show();
   // jQuery('.nav-'+current_cat+' ul li a').css("color","#4c6804");
});
</script>
<!-- End of Left Navigation for Herbal Category -->
<?php endif;?>
<?php endif;?>

