<?php 

$_frontendHelper = $this->helper('frontend/data');
?>
<?php if($this->getItems()->getSize()): ?>
  <div class="block block-custom linked_products">
    <div class="block-title">
      <strong><span><?php echo $this->__('You May Also Like') ?></span></strong>
    </div>
    <div class="block-content">
      <ul class="custom-products-list" id="block-custom">
        <?php foreach($this->getItems() as $_item): ?>
        <?php if($_item->getThumbnail()){
          $imagePath = $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(100);
        }else{
          $imagePath = Mage::getSingleton('catalog/product_media_config')->getBaseMediaUrl(). '/placeholder/' .Mage::getStoreConfig("catalog/placeholder/thumbnail_placeholder");
        }
        ?>
          <li class="item">
            <?php if(!$_item->isComposite() && $_item->isSaleable()): ?>
              <?php if (!$_item->getRequiredOptions()): ?>
                <input type="checkbox" class="checkbox custom-checkbox" id="custom-checkbox<?php echo $_item->getId() ?>" name="custom_products[]" value="<?php echo $_item->getId() ?>" /> 
              <?php endif; ?>
            <?php endif; ?>
            <div class="product">
              <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $imagePath ?>" width="100" height="100" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
              <div class="product-details">
               <?php
               $strength = $_item->getData('configurable_attribute');
               $special_price = $_item->getData('special_price');
               $us_brand_name = $_item->getData('us_brand_name');
               $simpleProduct = $_frontendHelper->getFirstChildInfo($_item);
               $activeingredient = $_frontendHelper->getActiveIngredients($_item);

               ?>
               <a href="<?php echo $_item->getProductUrl() ?>">
                <b><?php echo $this->htmlEscape($_item->getName()).'</b> <br/>'; ?>
              </a>
              <span class="equivalentSty">(<?php echo 'Generic for '.' '.trim($us_brand_name)?>)</span>
              <a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($activeingredient) ?></a>
              <?php echo $simpleProduct; ?>
              <?php if($_item->isSaleable()): ?>
               <div class="clear"  ></div>
               <a href="<?php echo $this->getAddToCartUrl($_item) ?>" class="link-cart">
                <?php echo $this->__('View Details') ?>
              </a>
            <?php  endif; ?>
          </div>
        </div>
      </li>
    <?php endforeach ?>
  </ul>
  <script type="text/javascript">decorateList('block-custom', 'none-recursive')</script>
</div>
</div>
<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery('.custom-products-list').slick({
      infinite: true,
      arrows: true,
      slidesToShow: 4,
      slidesToScroll: 1,
      responsive: [
      {
        breakpoint: 980,
        settings: {
          slidesToShow: 3,
          slidesToScroll: 1,
        }
      },
      {
        breakpoint: 840,
        settings: {
          slidesToShow: 4,
          slidesToScroll: 1,
        }
      },
      {
        breakpoint: 680,
        settings: {
          slidesToShow: 3,
          slidesToScroll: 1,
        }
      },
      {
        breakpoint: 480,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 1,
        }
      },
      {
        breakpoint: 320,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
        }
      }
                // You can unslick at a given breakpoint now by adding:
                // settings: "unslick"
                // instead of a settings object
                ]
              });
  });
</script>
<?php endif ?>
