<?php
$ruleName = array();
$ruleCollection = Mage::getModel('salesrule/rule');
// echo "<pre>";
// print_r($this->helper('checkout/cart')->getQuote()->getAppliedRuleIds());

 // echo "<pre>";  echo "salman"; print_r($this->helper('checkout/cart')->getQuote()->getData('rewardpoints')); exit;

$rewardpoints = $this->helper('checkout/cart')->getQuote()->getData('rewardpoints');
$appliedRules = $this->helper('checkout/cart')->getQuote()->getAppliedRuleIds();
$subtotal = $this->helper('checkout/cart')->getQuote()->getSubtotal();
$order_totals = $this->getTotal()->getValue();
$cartqty = $this->helper('checkout/cart')->getQuote()->getData('items_qty');


$cartItems = $this->helper('checkout/cart')->getQuote()->getAllItems();
foreach ($cartItems as $item)
{
    $productQty[] = $item->getQty();
}

foreach(explode(",",$appliedRules) as $ruleID){
    $rule = $ruleCollection->load($ruleID);
    if($rule->getDiscountAmount() > 0) { 
        $ruleNames[] = $rule->getName(); 
    }
}
$ruleTitle = implode(',',$ruleNames);
?>
<tr>
    <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="totals-rewards">
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
            <?php //echo $this->escapeHtml($this->getTotal()->getTitle()); ?>
            <span class="dis_label">
                <?php 
                // if($this->getTotal()->getTitle() == 'Discount'){ 
                    echo '<b>Discount('.$ruleTitle.')</b>';
                // } else { 
                    // echo $this->getTotal()->getTitle();
                // } ?></span>
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
    </td>
    <td style="<?php echo $this->getTotal()->getStyle() ?>">
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
            <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
    </td>
</tr>
<tbody class="discount_block" style="display:none;">
    <?php if($rewardpoints): ?>
    <tr>
        <td class="label"><strong><?php echo 'Rewardpoints Discount'; ?></strong></td>
        <td><?php echo $this->helper('checkout')->formatPrice($rewardpoints); ?></td>
    </tr>
    <?php endif; ?>
    <?php $count = 0; foreach(explode(",",$appliedRules) as $ruleID) {
            //Load the rule object
            $rule = $ruleCollection->load($ruleID);
            $ruleAmount[] = $rule->getDiscountAmount();
            // echo "<p>Rule - ".$rule->getName()." applied </p>";
    ?>
    <tr>
        <td class="label"><strong><?php if($rule->getDiscountAmount() > 0) { echo $rule->getName(); }?></strong></td>
        <?php if( $rule->getSimpleAction() == 'by_percent' ) { ?>
            <td>
                <?php
                    array_pop($ruleAmount);
                    $cart_dis = (($subtotal - array_sum($ruleAmount)) * $rule->getDiscountAmount()) / 100;
                    echo $this->helper('checkout')->formatPrice($cart_dis);
                ?>
            </td>
         <?php } else if( $rule->getSimpleAction() == 'by_fixed' ) { ?>
            <td>
                <?php
                    if($rule->getData('discount_qty')) {
                        foreach ($productQty as $qty) {
                            if($qty > $rule->getData('discount_qty')) {
                                $subtractQty[] = $qty - $rule->getData('discount_qty');
                            }
                        }
                        $cartAppliedQty = $cartqty - array_sum($subtractQty);
                        $cart_dis = $cartAppliedQty * $rule->getDiscountAmount();
                    } else {
                        $cart_dis = $cartqty * $rule->getDiscountAmount();
                    }
                    echo $this->helper('checkout')->formatPrice($cart_dis);
                ?>
            </td>
        <?php } else { ?>
            <td><?php  if($rule->getDiscountAmount() > 0) { echo $this->helper('checkout')->formatPrice($rule->getDiscountAmount()); }?></td>
        <?php } ?>
    </tr>
    <?php $count++; } ?>
</tbody>
<script type="text/javascript">
jQuery(document).ready(function(){
    jQuery('#checkout-review-table .discount_block .label').attr("colspan", 3);
    var img_url = "<?php echo Mage::getDesign()->getSkinUrl('images',array('_area'=>'frontend')) ?>"+'/j2t_add_one.png';
    more_discount = jQuery(".totals-rewards").prepend('<span class="more_offers"><img src="'+img_url+'" style="height:100%; width:auto;"/></span>');
    jQuery('.totals-rewards').click(function(){
        jQuery('.discount_block').toggle();
    });
});
</script>
<style type="text/css">
.totals-rewards { cursor: pointer; }
.totals-rewards .more_offers { height: 20px; width: 20px; display: inline-block; }
</style>
