<div class="accordion">
    <a href="#" class="accord">Shop by categories </a>
    <div class="pane">HI</div>

    <a href="#" class="accord">Search by brands</a>
    <div class="pane">
        test

        <a href="#" class="accord">Level 1:1</a>
        <div class="pane">HI</div>    
        
        <a href="#" class="accord">Level 1:2</a>
        <div class="pane">test</div>

    </div>
    <a href="#" class="accord">Featured Products</a>
    <a href="#" class="accord">Contact Us</a>
</div>
