<div class="trustedcompany-widget">
 <iframe id="trustedcompany-widget" width="266" height="220" frameborder="0" scrolling="no"></iframe>
 <a href="http://trustedcompany.com/us/alldaychemist.com-reviews" target="_blank" title="Alldaychemist Reviews"></a>
 <script>(function(){document.getElementById('trustedcompany-widget').src='//trustedcompany.com/embed/widget/v2?domain=alldaychemist.com&type=c&review=1&text=b';})();</script>
</div>
