
<style type="text/css">
   .align_center h1{
      text-align: center;
       font-size: 26px;
       font-weight: normal;
   }
   .image_loader{
      text-align: center;
      position: absolute;
      top: 50%;
      left: 50%;
      margin: -60px 0 0 -60px;
   }
   .image_loader{
      width: 120px;
   }
   body{
       background: rgba(153, 158, 145, 0.18);
       padding: 20px;
       text-align: left;
       font-size: 20px;
   }
</style>
<?php 
       
$encrypted_order_id = $this->getRequest()->getParam('order_id');
$frontendHelper = Mage::helper('frontend');
$orderId = $frontendHelper->encrypt_decrypt('decrypt',$encrypted_order_id);

$_order = Mage::getModel('sales/order')->load($orderId);

if($_order->getId()){

   $incrementId = $_order->getIncrementId();
   $customerFullName = $_order->getCustomerName();
   $billingaddress = $_order->getBillingAddress();
   $shippingaddress = $_order->getShippingAddress();
   $customerPhone = $billingaddress->getData('telephone');
   $customerAddress = $billingaddress->getData('street').' '.$billingaddress->getData('city').' '.$billingaddress->getData('region').' '.$billingaddress->getData('postcode').' '.$billingaddress->getData('country_id');

   $customerCity = $billingaddress->getData('city');
   $customerZip = $billingaddress->getData('postcode');

   $region_id = $billingaddress->getData('region_id');
   $regionModel = Mage::getModel('directory/region')->load($region_id);

   $customerStateCode = $billingaddress->getData('region');

   $customerCountryCode = $billingaddress->getData('country_id');
   if($customerCountryCode=='US'){
      $customerStateCode = $regionModel->getData('code');
   }
   $orderDescription = $_order->getCustomerOrderIncrementId();
   $orderAmount = $_order->getGrandTotal();
   $orderQty = $_order->getData('total_qty_ordered');
   $customerEmail = $_order->getCustomerEmail();
   ?>
   <div class="image_loader">
      <img src="<?php echo $this->getSkinUrl('images/hourglass.gif');?>">
   </div>
   <div class="align_center">
   <h1>     
     You will be redirected to Payment Gateway page in a few seconds......   
   </h1>
   </div>
   <form id="gspay_form" method="post" action="https://secure.redirect2pay.com/payment/pay.php">
      <input type="hidden" name="siteID" value="118409">
       <input type="hidden" name="OrderDescription" value="<?php echo "Order # ".$orderDescription;?>">
      <input type="hidden" name="Amount" value="<?php echo $orderAmount;?>">  
      <input type="hidden" name="OrderID" value="<?php echo $incrementId; ?>" />
      <input type="hidden" name="customerFullName" value="<?php echo $customerFullName; ?>" />
      <input type="hidden" name="customerPhone" value="<?php echo $customerPhone;?>" />
      <input type="hidden" name="customerAddress" value="<?php echo $customerAddress;?>" />
      <input type="hidden" name="customerCity" value="<?php echo $customerCity;?>" />
      <input type="hidden" name="customerZip" value="<?php echo $customerZip;?>" />
      <input type="hidden" name="customerCountryCode" value="<?php echo $customerCountryCode;?>" />
      <input type="hidden" name="customerStateCode" value="<?php echo $customerStateCode;?>" />
      <input type="hidden" name="customerEmail" value="<?php echo $customerEmail;?>" />
      
      <input type="hidden" name="returnURL" value="<?php echo $this->getUrl('offlinepayment/link/pending');?>" />
      <input type="hidden" name="ApproveURL" value="<?php echo $this->getUrl('offlinepayment/link/success');?>" />
      <input type="hidden" name="DeclineURL" value="<?php echo $this->getUrl('offlinepayment/link/failure');?>" />
   </form>
   <script type="text/javascript">
      document.getElementById("gspay_form").submit();
   </script>
   <?php }else{
      Mage::getSingleton('core/session')->addError('Request Order is not exists in the System');
      Mage::app()->getResponse()->setRedirect(Mage::getBaseUrl());
   } ?>
