<div class="echeck_banner">
	<a class="the_top_banner" href="<?php echo $this->getUrl('content/114-echeck') ?>"><img class="" src="<?php echo $this->getSkinUrl(); ?>images/left_banners/eCheckBanner.png" /></a>
	<a class="the_bottom_banner" href="<?php echo $this->getUrl('content/88-order-online') ?>"><img class="" src="<?php echo $this->getSkinUrl(); ?>images/left_banners/how-to-order-banner.gif" /></a>
</div>