<?php

 $order = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId());
 $customer_name = $order->getCustomerName();
 // echo $this->getLayout()->createBlock('core/template')->setTemplate('checkout/message/birthday.phtml')->toHtml();  
 echo $this->getChildHtml('birthday');
?>
<?php 
		//payment method used session in set in saveOrder Controller and Echeckapi Module
 		$paymentMethosUsed = Mage::getSingleton('core/session')->getPaymentMethosUsed();
        if(Mage::getSingleton('core/session')->getEchecksuccess() == '1'){
 		 	$paymentMethosUsed = 'echecknormal';

 		 }
 		
 		 if(!isset($paymentMethosUsed)){
 		 	$paymentMethosUsed = 'default';
 		 }

 		switch ($paymentMethosUsed) {
 			case 'echeck':    
 			echo $this->getChildHtml('echeck_approved');
 			// echo $this->getLayout()->createBlock('core/template')->setTemplate('checkout/message/echeck_approved.phtml')->toHtml();  
			break;
			case 'echecknormal':    
			 echo $this->getChildHtml('echeck_normal_approved');
 			// echo $this->getLayout()->createBlock('core/template')->setTemplate('checkout/message/echeck_normal_approved.phtml')->toHtml();  
			break;

 			case 'anytrans': 
 			 echo $this->getChildHtml('anytrans_approved');
 			// echo $this->getLayout()->createBlock('core/template')->setTemplate('checkout/message/anytrans_approved.phtml')->toHtml();  

 			break;   

 			case 'gspay': 
 			 echo $this->getChildHtml('gspay_approved');
 			// echo $this->getLayout()->createBlock('core/template')->setTemplate('checkout/message/gspay_approved.phtml')->toHtml();  
 			break;

			default:  ?>
					<div class="page-title">
					<h1><?php echo $this->__('Your order has been received.') ?></h1>
					</div>
					<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
					<h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h2>

					<?php if ($this->getOrderId()):?>
					<?php if ($this->getCanViewOrder()) :?>
					<p><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></p>
					<?php  else :?>
					<p><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?></p>
					<?php endif;?>
					<p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
					<?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
					<p>
					<?php echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $this->getPrintUrl()) ?>
					<?php echo $this->getChildHtml('checkout.success') ?>
					</p>
					<?php endif;?>
					<?php endif;?>
					<?php 
						/* if ($this->getAgreementRefId()): ?>
		 			<p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
		 			<?php endif;?>

		 			<?php if ($profiles = $this->getRecurringProfiles()):?>
		 			<p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
		 			<ul class="disc">
		 				<?php foreach($profiles as $profile):?>
		 				<?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
		 				<li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
		 				<?php endforeach;?>
		 			</ul>
		 			<?php endif; */



					?>
			<?php break;
		}
?>
<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>
<div style="display:none">
<?php //echo $this->getChildHtml('echeck_approved');?>
</div>
<?php
$orderObject = $order->getData();
//$orderObject = $order->getData();
//Mage::log('eCheck'.Zend_Debug::dump($orderObject, null, false), null, 'echeckTest.log');
?>
