<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost', array('_secure' => $this->getRequest()->isSecure())) ?>" method="post" id="form-validate-email" style="display:none" onsubmit="return false">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>    
       
        <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
        <ul class="form-list forgot_pwd_form">
            <li>
                <label for="email_address"  class="required email_address"><?php echo $this->__('Email Address') ?><em>*</em></label>
                <div class="input-box">
                    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                </div>
            </li>
            <li>
                <!-- <input type="button" name="submitofemail" id="submitofemail" /> -->
                <button class="btn btn-primary" name="submitofemail" id="submitofemail" />
                    <span><span>Submit</span></span>
                </button>
            </li>
            <li><p class="message"></p></li>
        </ul>
       
</form>
<script type="text/javascript">
jQuery('#submitofemail').click(function(){
    //<![CDATA[
        var forgotform = new VarienForm('form-validate-email', true);
    //]]>
    if(!forgotform.validator.validate()){ return false;}
    var email=jQuery('#email_address').val();
    jQuery.ajax({
        url: "<?php echo Mage::getBaseUrl().'onepage/index/forgotpasswordpost';?>",
        data: {'email':email},
        type:'post',
        beforeSend :function(){
            IWD.OPC.Checkout.showLoader();
        },
        success: function(result){
            var resultmes = jQuery.parseJSON(result);
            jQuery("div.md-content-wrapper li p.message").html(resultmes.message);
            IWD.OPC.Checkout.hideLoader();
        }
    });
});

jQuery('.restore-account').click(function() {
    jQuery('#tab-1 .proceed-next').hide();
});



</script>
