<embed width="500" height="400" src="http://www.youtube.com/watch?v=zf-sZ8wwi4M" type="application/x-shockwave-flash"></embed>
<ul class="list02">
<li>Food and Drug Administration (FDA), US</li>
<li>Medicines Control Agency (MCA), UK</li>
<li>Therapeutic Goods Administration (TGA), Australia</li>
<li>Medicines Control Council (MCC), South Africa</li>
<li>National Institute of Pharmacy (NIP), Hungary</li>
<li>Pharmaceutical Inspection Convention (PIC), Germany</li>
<li>World Health Organisation (WHO)</li>
<li></li>
</ul>