<div class="page-title">
    <h1><?php echo $this->__('Refill Reminder') ?></h1>
</div>
<?php //echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php
$customerSession = Mage::getSingleton('customer/session');
$productModel = Mage::getModel('catalog/product');
$childProductModel = Mage::getModel('catalog/product');
$productConfModel = Mage::getModel('catalog/product_type_configurable');
$model = Mage::getModel('refillreminder/refillreminder'); //model to process reminder checking data
if($customerSession->isLoggedIn()) {
	$email = $customerSession->getCustomer()->getEmail();
}
$collection = $model->getCollection();
$collection->addFieldToFilter('customer_email', array('eq'=>$email));
?>
<?php echo $this->getToolbarHtml(); ?>
<?php if($collection->getSize()) { ?>
<table class="data-table" id="reminder_table">
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th><?php echo $this->__('SKU') ?></th>
            <th><?php echo $this->__('Product Name') ?></th>
            <th><?php echo $this->__('Pack size') ?></th>
            <th><?php echo $this->__('Product Image') ?></th>
            <th><?php echo $this->__('Remind in') ?></th>
            <th><?php echo $this->__('Next reminder') ?></th>
            <!-- <th><span class="nobr"><?php //echo $this->__('Options') ?></span></th> -->
        </tr>
    </thead>
	<?php
		foreach($collection->getData() as $myAllReminders) {
			$child_id = $productModel->getIdBySku($myAllReminders['product_sku']);
			$childProduct = $productModel->load($child_id);
			$parent_ids = $productConfModel->getParentIdsByChild($child_id);
			$product = $productModel->load($parent_ids[0]);
			if($myAllReminders['reminder_days']>30) {
				$remindIn = round($myAllReminders['reminder_days']/30)." Months";
				if(round($myAllReminders['reminder_days']/30) == "1") {
					$remindIn = round($myAllReminders['reminder_days']/30)." Month";
				}
			}
			else {
				$remindIn = $myAllReminders['reminder_days']." Days";
				if($myAllReminders['reminder_days'] == "1") {
					$remindIn = $myAllReminders['reminder_days']." Day";
				}
			}
			$lastRemindDate = date("Y-m-d", strtotime($myAllReminders['last_mail_sent']));
			$separateSkuPackSize = explode("-", $myAllReminders['product_sku']);
			$tblData = '<tr>';
			$tblData.= '<td class="first_img_td"><a href="'.$product->getProductUrl().'"><img width="150px" src="'.$product->getImageUrl().'"/></a></td>';
			$tblData.= '<td class="sku first">'.$separateSkuPackSize[0]/*$product->getSku()*/;
			$tblData.= '<div class="refill-action"><div class="action_links">';
			if($myAllReminders['remind_flag'] == 1) {
				$tblData.= '<a id="edit_link'.$myAllReminders['reminder_id'].'" class="edit_link" href="'.$this->getUrl().'refillreminder/edit?remind_id='.$myAllReminders['reminder_id'].'">Edit</a> |';
				$notice = "";
			}
			else {
				$notice = '<span class="smallred">You have not purchased this product.</span>';
			}
			$tblData.= '<a class="remove_reminder" id="rdata_"'.$myAllReminders['reminder_id'].' href="'.$this->getUrl().'refillreminder/view/delete?remind_id='.$myAllReminders['reminder_id'].'">Remove</a></div>'.$notice.'</div>';
			$tblData.= '</td>';
			$tblData.= '<td class="product_name"><a href="'.$product->getProductUrl().'">'.$product->getName().'</a></td>';
			$tblData.= '<td>'.$separateSkuPackSize[1].'</td>';
			$tblData.= '<td class="mid_img_td"><a href="'.$product->getProductUrl().'"><img width="150px" src="'.$product->getImageUrl().'"/></a></td>';
			$tblData.= '<td>'.$remindIn.'</td>';
			$tblData.= '<td>'.date("Y-m-d", strtotime($lastRemindDate. ' + '.$myAllReminders['reminder_days'].' days'));
			
			
			$tblData.= '</td>';
			$tblData.= '</tr>';
			echo $tblData;
		}
	?>
</table>
<div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->getBaseUrl(''); ?>customer/account/"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    </div>
<?php echo $this->getToolbarHtml(); ?>
<?php }else { ?>
		<!-- echo "No data to display"; -->
        <p><?php echo $this->__('The reminder is empty.'); ?></p> 
<?php } ?>
 <script type="text/javascript">decorateTable('reminder_table');</script> 
<script type="text/javascript">
jQuery(".remove_reminder").click(function(){
	var r=confirm("Are you sure?");
	if (r==true) {
		//alert(jQuery(this).attr('href'));
		jQuery.post(jQuery(this).attr('href'), function(data) {
			jQuery('#reminder_table').replaceWith(data);
		});
		return false;
	}
	else {
		//alert("You pressed Cancel!");
		return false;
	}
});
/*jQuery(".open_edit").click(function(){
	var str = this.id;
	var splitdash = str.split("-");
	jQuery.post(jQuery("#"+this.id).attr('href'), function(data) {
		jQuery("#editbox-"+splitdash[1]).html(data);
	});
	return false;
});*/
jQuery(".edit_link").click(function(){
	jQuery("#"+this.id).fancybox({
			type: "iframe",
			width: "300px",
			height: "300px"
		});
});
</script>

