<div class="popup_class_area">
	<img src="<?php echo $this->getSkinUrl('images/newadc_look.jpg'); ?>">
</div>
<div class="popupBox">
	<div class="closeBtn">X</div>
	<a href="<?php echo  Mage::getBaseUrl(); ?>">
		<img src="<?php echo $this->getSkinUrl('images/new_adc_theme.jpg'); ?>" >
	</a>
</div>
<div class="popupCover">	
</div>

<script type="text/javascript">
jQuery(document).ready(function() {

	jQuery(".popup_class_area").click(function(){
		jQuery(".popupCover, .popupBox").fadeIn(400);
	});
	jQuery(".closeBtn, .popupCover").click(function(){
		jQuery(".popupCover, .popupBox").fadeOut(400);
	})

});
</script>

<style>
.popup_class_area {
	position: absolute;
	top: 450px;
	right: 0px;
	background-url
	height:100px;
}
.popupCover {
  width: 100%;
  height: 100%;
  background: rgba(0,0,0,0.8);
  position: fixed;
  left: 0;
  top: 0;
  text-align: center;
  padding: 5% 0;
  display: none;
  z-index: 1000;
}
.popupBox {
  width: 80%;
  height: auto;
  background: #fff;
  position: absolute;
  padding: 9px;
  box-sizing: border-box;
  margin-left: -40%;
  left: 50%;
  border-radius: 7px;
  top: 10%;
  z-index: 1011;
  display: none;
}
.popupBox img {
	width: 100%;
	border: 1px solid #eee;
}
.closeBtn {
	width: 25px;
	height: 25px;
	text-align: center;
	color: green;
	padding-top: 3px;
	box-sizing: border-box;
	font-weight: bold;
	position: absolute;
	right: -12px;
	top: -8px;
	border-radius: 50%;
	border: 2px solid #D1CBCB;
	background: #fff;
	box-shadow: 0px 0px 2px #000;
	cursor: pointer;
}
</style>
