<div class="below_banner_main_area">
	<div class="below_banner_area">
		<div class="how_to_order">
			<img src="<?php echo $this->getSkinUrl('images/home/adc_cart_banner.png');?>" alt="" class="cart_img"/>
			<div class="content_order">
				<h1>How to Order</h1>
				<p>
					1. Select the product from Brand, Generic or you can search the product by clicking on "Search" option.</p>
				<a href="<?php echo $this->getBaseUrl();?>content/88-order-online/" class="readmore" target="_blank"><span>Read More</span></a>
			</div>
		</div>
		

	<!-- 	<div class="echeck">
			<div class="echeck_inner">
				<img src="<?php //echo $this->getSkinUrl('images/home/checkmoneyorder.png');?>" alt="" class="echeck_img"/>
				<div class="content_order">
					<h1>Pay by Check/Money Order and Wire Transfer & get a</h1>
					<h2>Discount of US $ 5.00*</h2>
					<div class="app_term">*Applicable on more than US $30.00 purchase.</div>
					<br/>				
			
				</div>
			</div>
		</div> -->
		<div class="echeck">
			<div class="echeck_inner">
				<img src="<?php echo $this->getSkinUrl('images/home/echeck.jpg');?>" alt="" class="echeck_img"/>
				<div class="content_order">
					<h2>Pay by eCheck & get a</h2>
					<h2>Discount of US $10.00*</h2>
					<!-- <h1>Pay by eCheck or Online Bank Transfer & get a</h1> -->
					<!-- <h2>Free Shipping</h2> -->
					<h3>Pay Instantly. No verification calls.</h3>
					<div class="app_term app_term_text">*Applicable on more that US $100.00 purchase.</div>
					<a href="<?php echo $this->getBaseUrl();?>content/114-echeck/" class="readmore" target="_blank"><span>Learn More</span></a>
					
				</div>
			</div>
		</div>
			<div class="combopack">
					<img src="<?php echo $this->getSkinUrl('images/home/combooffer2.png');?>" alt="" width="100%" class="combopack_img"/>
					<a class="comboclass" href="<?php echo $this->getBaseUrl().'contactcustom/index/combopack2';?>">
						<img src="<?php echo $this->getSkinUrl('images/home/buynow.png');?>" alt="" />
					</a>
					<ul class="productname">
						<li><span>4 Pills Tadacip 20 mg</span></li>
						<li><span>4 Pills Suhagra 100 mg</span></li>
					</ul>
					<span class="combo_price_label">Price</span>
					<span class="combo_price">US$15.00</span>
			</div>
	</div>
</div>
<script type="text/javascript">
//jQuery('.comboclass').click(function($){
// 	// alert('hiiiii');
// 	var url ="<?php echo $this->getBaseUrl().'contactcustom/index/combopack';?>";
// 	jQuery.post( url, function( data ) {
//   	//alert( "Data Loaded: " + data );
// });
// });
</script>
<style type="text/css">
/*start combo pack 2*/
.combopack{position: relative;}
.productname{position: absolute;top:67px;left:58px;color: #000;list-style: inherit; }
.productname{list-style:square;}
.productname li{color: #9DB501;}
.productname li span{color: #747474;font-size: 12px;}
.combo_price{position: absolute;top: 122px;color: #fff;font-size:13px;right: 45px;font-weight: bold;font-family: Arial bold;}
.combo_price_label{position: absolute;top: 102px;color: #fff;font-size:16px;right: 54px;font-weight: bold;font-family: Arial bold;}
/*start combo pack 2*/
.how_to_order {
padding: 30px 2%;
float: left;
background: none;
display: inline-block;
zoom: 1;
width: 28%;
}

.combopack {
padding: 20px 2%;
float: left;
display: inline-block;
zoom: 1;
width: 20%;
position: relative;
}

.echeck {
float: left;
display: inline-block;
zoom: 1;
width: 44%;
}
.header_link_wrapper, .below_banner_area, .adc_index_content, .main {
width: 95%;
max-width: 1150px;
margin: auto;
}
.below_banner_main_area .echeck h1 {
font-weight: normal;
color: #fff;
text-shadow: 1px 0px 1px #000;
margin-bottom: 5px;
text-align: left;
}
.below_banner_main_area .echeck h2 {
font-weight: bold;
color: #fcff00;
text-shadow: 1px 1px 1px #000;
line-height: 35px;
margin-bottom: 0px;
text-align: left;
}
.echeck_inner {
padding: 30px 4%;
background: none;
width: 100%;
}
.comboclass{position: absolute;
bottom: 21%;
left: 50px;}
.category_select {
float: right;
margin-right: 8%;
}
.app_term_text{
	padding-bottom: 10px;
}
</style>