<div style="border:1px solid #666;margin-bottom:10px;padding:10px;font-size:15px;">
	<p style="font-weight:bold;">AllDayChemist helps you get closer to your Valentine. Here's a <span style="font-size:17px;">15% discount*</span> coupon for all Men's Health products.</p><br>

	<p>Use coupon code: <span style="font-weight:bold;">MENSHEALTH15</span></p><br>

	<ul><span style="font-size:14px;color:red;">*Terms and Conditions</span>
		<li>• MENSHEALTH15 code is case sensitive</li>
		<li>• Minimum cart amount - 100$ (including shipping)</li>
		<li>• Valid only till February 23, 2014</li>
		<li>• Only logged in users can avail the offer</li>
		<li>• One time use</li>
	</ul>
</div>