<head>
<style>
.form-list1 li span
{ 
    float:left;
	font-weight: bold;
	margin-right:5px;
}
.form-list1 li
{
	list-style: disc outside none;
	margin: 0 0 7px 20px;
}
</style>
</head>
<fieldset class="form-list1" >
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
		<p style="color:red;">Discount:</p>
		
		   <?php //echo $this->__('Discount:');echo "<br>"; ?>
            <p style="font-weight: bold;">Offering US$ 5.00 discount if the order value is less than US$ 100.00 and if the order value is more than US$ 100.00 than US$ 10.00 discount. </p>
      	  
		   <p style="font-weight: bold;"><?php echo $this->__('Please make the Check / Pay Order / Bank Draft payable to DERRIC WOOD. Kindly ensure the following points before mailing the same:');echo "<br>"; ?></p>
            <?php //echo $this->__('To the Following Bank Account:') ?>
        		
		<li>
            <p>You have sufficient funds in your account (in case of check).</p>
        </li>
		<li>
            <p>Date should be in the format of MM/DD/YYYY</p>
        </li>
		<li>
            <p>It is in the favor of our company 'DERRIC WOOD'</p>
        </li>
		<li>
            <p>The amount in words and figures should match.</p>
        </li>
		<li>
            <p>You have signed the Check</p>
        </li>
		<li>
            <p>There is no over writing on the check.</p>
        </li>
		<li>
            <p>Please mail the Check / Pay Order / Bank Draft to:</p>
        </li>
		
           <p>M/S DERRIC WOOD</p>
			<p>UNIT NO. 702, 703, 704 GOPAL HEIGHTS</p>
			<p>PLOT NO D-9, NETAJI SUBHASH PLACE</p> 
			<p>PITAMPURA DELHI-110034</p>
			<p>INDIA</p>
        		
		
            <p style="color:red;">Please send the scan copy of your filled Check/ Money order to info@alldaychemist.com so that we can ensure that you have filled all the information correctly.</p> 
	   
     		 <p style="color:red;">This will help us to process your order as soon as possible.</p>
        		
		
			 <p>Regards</p>

			 <p>AllDayChemist Sales Team</p>
		
	</ul>
	
	














 



   
</fieldset>