<div class="below_banner_main_area">
	<div class="below_banner_area">
		<div class="home-banner-block">
			<a class="comboclass" href="<?php echo $this->getBaseUrl().'referral';?>">
				<img src="<?php echo $this->getSkinUrl('images/banner-block-1.jpg');?>" alt=""/>
			</a>
			
		</div>
		<div class="home-banner-block mid">
			<a class="comboclass" href="<?php echo $this->getBaseUrl().'';?>">
				<img src="<?php echo $this->getSkinUrl('images/banner-block-2.jpg');?>" alt=""/>
			</a>
			
		</div>
		
		<div class="home-banner-block third">
			<a class="comboclass" href="<?php echo $this->getBaseUrl().'content/88-order-online/';?>">
				<img src="<?php echo $this->getSkinUrl('images/banner-block-3.jpg');?>" alt=""/>
			</a>
			
		</div>
		<div class="home-banner-block last">
			<a class="comboclass" href="<?php echo $this->getBaseUrl().'';?>">
				<img src="<?php echo $this->getSkinUrl('images/banner-block-4.jpg');?>" alt=""/>
			</a>
			
		</div>
	</div>
</div>
