<?php
    // Check if current Magento version includes Persistent Shopping Cart Extension
    $isPersistantShoppingCartEnabled = Mage::getStoreConfigFlag('persistent/options/enabled');
    $isContextCheckout = 0;
    if ($isPersistantShoppingCartEnabled) {
        $html = $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml();
        $isContextCheckout = Mage::helper('checkout')->isContextCheckout();
    } else {
        $html = $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->toHtml();
    }
    if (Mage::app()->getStore()->isCurrentlySecure()) {
        $url_of_website = $this->getUrl('',array('_secure'=>true));
    }else{
        $url_of_website = $this->getUrl();
    }
?>

<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create a new Account') ?></h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('paypalauth.register'); ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate" onSubmit="return validateRecaptcha()">
        <div class="fieldset">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <!--Form Key-->
            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>

            <div class="create-acc-boxlft">
                <ul class="form-list">
                    <li class="fields">
                        <?php echo $html ?>
                    </li>
                            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                    <?php if ($_dob->isEnabled()): ?>
                        <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
                    <?php endif ?>
                    <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                    <?php if ($_taxvat->isEnabled()): ?>
                        <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
                    <?php endif ?>
                    <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                    <?php if ($_gender->isEnabled()): ?>
                        <li class="gender_field"><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
                    <?php endif ?>
                <!-- google reCaptcha start -->
                       <?php if($this->helper('recaptcha')->showOnRegister()){?>                          
                         <!-- <li id="rcode" class="fields">  
                            <label for="captcha" class="required"><?php //echo $this->__('Captcha') ?><em>*</em></label>
                            <div class="input-box">  
                                <div class="captcha">
                                    <div class="g-recaptcha" data-sitekey="<?php// echo$this->helper('recaptcha')->getKey(); ?>" data-theme="<?php //echo ($this->helper('recaptcha')->getTheme()); ?>"> </div>
                                </div>
                            </div>
                            <span id="captcha-required" style='display:none; color:#ff0000'><?php //echo $this->__('Please Fill Recaptcha To Continue'); ?></span>
                        </li> --> 
                            <div id="recaptcharegistration"></div>
                            <span id="captcha-required" style='display:none; color:#ff0000'><?php echo $this->__('Please Fill Recaptcha To Continue'); ?></span>
                             <input type="hidden" id="qt_hiddenRecaptcha_registration"/>
                         <?php } ?>
                    <!-- google reCaptcha end -->
                    <?php if ($this->isNewsletterEnabled()): ?>
                <li class="control">
                    <div class="is_subscribed_wrap">
                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                        <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                    </div>

                </li>
            <?php endif ?>
                </ul>
            </div>

            <div class="create-acc-boxrt">
                <ul class="form-list">
                <li>
                    <label for="email_address" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><?php echo $this->__('Password') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><?php echo $this->__('Confirm Password') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                    <!-- Captcha input -->
                    <!-- <div class="field">
                        <label for="register_captcha_code" class="required"><?php //echo $this->__('Captcha') ?><em>*</em></label>                        
                        <div class="input-box sinput">
                            <img src="<?php //echo $url_of_website.'register_captcha_file.php?rand='.rand();?>" id='register_captcha_img'/>                            
                            <br/><br/>
                            <input id="register_captcha_code" class="input-text required-entry validate_captcha sb_input_field" name="register_captcha_code" type="text">
                            <small>Click <a href='javascript: register_refresh_Captcha();'>here</a> to refresh Image !</small>
                            <input type="hidden" id="check-me" />
                        </div>                        
                    </div> -->
                    <!-- Captcha input ends -->
                </li>
                <!-- <br/> -->
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                </ul>
                <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
            </div>
            <div class="buttons-set">
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
           <!-- <ul class="form-list">
                 <li class="fields">
                    <?php //echo $html ?>
                </li> -->
                <!-- <li>
                    <label for="email_address" class="required"><em>*</em><?php //echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" value="<?php //echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" title="<?php //echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
            </ul> -->
        </div>
    <?php if($this->getShowAddressFields()): ?>
        <div class="fieldset">
            <input type="hidden" name="create_address" value="1" />
            <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" name="company" id="company" value="<?php echo $this->htmlEscape($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->htmlEscape($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" />
                        </div>
                    </div>
                </li>
                <li class="wide">
                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text required-entry" />
                    </div>
                </li>
            <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i?>" class="input-text" />
                    </div>
                </li>
            <?php endfor ?>
                <li class="fields">
                    <div class="field">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->htmlEscape($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text required-entry" id="city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->htmlEscape($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international required-entry" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                </li>
            </ul>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
        </div>
    <?php endif; ?>
        <!--<div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>
            <ul class="form-list">
                 <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?php //echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="<?php //echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?php //echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php //echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>
                <?php //echo $this->getChildHtml('persistent.remember.me'); ?>
            </ul>
            <?php //echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        </div>-->
        <!-- <div class="buttons-set">
            <p class="required"><?php //echo $this->__('* Required Fields') ?></p>
            <p class="back-link"><a href="<?php //echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php //echo $this->__('Back') ?></a></p>
            <button type="submit" title="<?php //echo $this->__('Submit') ?>" class="button"><span><span><?php //echo $this->__('Submit') ?></span></span></button>
        </div> -->
        <?php if ($isContextCheckout): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        // jQuery("#datepicker").datepicker("setDate", new Date());
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
    <!-- Captcha Validation on Form Submit-->
    <script type="text/javascript">
    /*var new_form = new VarienForm("form-validate");
    jQuery('#form-validate').submit(function(){
        var register_captcha_img =jQuery('#register_captcha_code').val();
        if(new_form.validator.validate()){
            jQuery.ajax({
                type : "POST",
                success:function(content){
                    jQuery('#register_captcha_code').val("")
                    register_refresh_Captcha();
                }
            }); 
        }
            
    });*/ 
</script>
<!-- Captcha Validation referesh -->
<script language='JavaScript' type='text/javascript'>
    /*function register_refresh_Captcha(){
        var img = document.images['register_captcha_img'];
        img.src = img.src.substring(0,img.src.lastIndexOf("?"))+"?rand="+Math.random()*1000;
        setTimeout('RegisterRefreshCaptcha()', 500);
    }*/
</script>
<!-- Captcha Validation to match the input with image -->
<script type="text/javascript">
    /*Validation.add('validate_captcha','Enter valid code',function(field_val){
       if(jQuery("#check-me").val() != "")   {
            var me = jQuery("#check-me").val().split("_");
            if(me[1] == field_val) {
                return true;
            }
            return false;
        }
        return false;
    });*/

    /*jQuery(window).load(function(){
        RegisterRefreshCaptcha();
    });
    function RegisterRefreshCaptcha(){
        jQuery.post("<?php //echo $url_of_website.'register_captcha_file.php?code='.rand();?>", function(captcha){
            if(captcha!=""){
                jQuery("#check-me").val(captcha);
                var split = captcha.split("_");
                var capValue =(split[1]);
                checkCaptcha(capValue);              
            }
        });
    }
    /*Captcha validation*/
    /*function checkCaptcha(capValue){
        jQuery.ajax({
                    type : "POST",
                    url : "<?php //echo $this->getUrl('frontend/index/captcha') ?>",
                    data : "captcha="+capValue,
                    success:function(result){
                    return result;
                    }
                });
    }*/
</script>
</div>
<script type="text/javascript">
  var onloadCallbackregistration = function() {
       widgetId3 = grecaptcha.render('recaptcharegistration', {
          'sitekey' : '<?php echo $this->helper('recaptcha')->getKey(); ?>',
          'theme' : '<?php echo $this->helper('recaptcha')->getTheme();?>',
          'callback' : correctCaptcha_quoteonregistration,
        });
  };
  var correctCaptcha_quoteonregistration = function(response) {
    document.getElementById("qt_hiddenRecaptcha_registration").value = response;
};
</script>
<script type="text/javascript">
    function validateRecaptcha(){
                <?php if($this->helper('recaptcha')->showOnRegister()){ ?>
                    if (document.getElementById("qt_hiddenRecaptcha_registration").value != ""){
                        document.getElementById("captcha-required").style.display = "none";
                        return true;
                    } else {
                        document.getElementById("captcha-required").style.display = "block";
                        return false;
                    }
                <?php } else { ?>
                    return true;
                <?php } ?>
            }
</script>
<script src="https://www.google.com/recaptcha/api.js?onload=onloadCallbackregistration&render=explicit"async defer></script> <!-- google reCaptcha end -->