<!-- <div class="page-title"><h1>Coupons & Offers</h1></div> -->

<ul class="coupons-offers">


<!-- <li>
<div class="offer-text">
<h2>Flat 20% off on Acne products </h2>
<p>On minimum purchase of $500. Terms & Conditions Apply.</p>
</div>
<a href="" class="back">Shop Now</a>
</li> -->

<!-- <li>
<div class="offer-text">
<h2>Pay by eCheck & get a Discount of US $10.00</h2>
<p>Pay by eCheck & get a Discount of US $10.00.</p>
</div>
<a href="" class="back">Shop Now</a>
</li> -->

<li>
<div class="offer-text">
<h2>ED Trial Pack at Price US $15.00.</h2>
<p>Get ED Trial Pack at Price US $15.00</p>
</div>
<a href="<?php echo Mage::getUrl('contactcustom/index/combopack2')?>" class="back">Shop Now</a>
</li>
<li>
<div class="offer-text">
<h2>Pay By Wire Transfer and Get US$ 5.00 discount on order value.</h2>
<p>Pay By Wire Transfer and Get US$ 5.00 discount on order value.</p>
</div>
<a href="" class="back">Shop Now</a>
</li>
<li>
<div class="offer-text">
<h2>Pay By Check/ Money Order and Get US$ 5.00 discount on order value.</h2>
<p>Pay By Check/ Money Order and Get US$ 5.00 discount on order value</p>
</div>
<a href="" class="back">Shop Now</a>
</li>
<li>
<div class="offer-text">
<h2>Pay by eCheck and Get US$ 10.00 discount on order value.</h2>
<p>Pay by eCheck and Get US$ 10.00 discount on order value (For USA clients only).</p>
</div>
<a href="" class="back">Shop Now</a>
</li>
<!-- <li>
<div class="offer-text">
<h2>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</h2>
<p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
</div>
<a href="" class="back">Shop Now</a>
</li> -->


</ul>
