<?php $_product = $this->getProduct(); ?>
<?php //@nil for tabular packsize ?>
            <?php
			if($_product->isConfigurable()) {
				//$productModel = Mage::getModel('catalog/product');
				
				$proModel = Mage::getModel('catalog/product');
				$cartHelper = Mage::helper('checkout/cart');
				$conProduct = $proModel->load($_product->getId());
				$currencyFormat = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
				$childProducts = Mage::getModel('catalog/product_type_configurable')->getUsedProducts(null, $conProduct);
				$attr = $proModel->getResource()->getAttribute("pharmaceutical_form");
				$attrPackSize = $proModel->getResource()->getAttribute("pack_size");
				$url = $this->getUrl();
				foreach($childProducts as $child) {
					if($child->getData('status')) {
						$newChildProducts[$attrPackSize->getSource()->getOptionText($child->getData('pack_size'))] = $child;
					}
				}
				ksort($newChildProducts);
				echo "<table class=\"new_product_list\"><tr><td style=\"width:105px\"><strong>Pack Size</strong></td><td><strong>Price</strong></td><td><strong>Qty</strong></td><td style=
				\"width:92px\"></td></tr>";
				$i=0;
				echo "<pre>";
				foreach($newChildProducts as $child) {
					//print_r();
					if ($attr->usesSource()) {
						$pharmaceuticalForm = $attr->getSource()->getOptionText($conProduct->getData('pharmaceutical_form'));
					}
					if ($attrPackSize->usesSource()) {
						$packSizeLabel = $attrPackSize->getSource()->getOptionText($child->getData('pack_size'))." ".$pharmaceuticalForm."&nbsp;";
					}
					if($child->getData('bonus')) {
						$packSizeLabel = $child->getData('bonus')." + ".$packSizeLabel." Free";
					}
					$priceLabel = $currencyFormat."&nbsp;".number_format($child->getPrice(), 2, '.', '');
					if($child->getSpecialPrice()) {
						$priceLabel = '<span class="old-price">'.$currencyFormat."&nbsp;".number_format($child->getPrice(), 2, '.', '').'</span>
								<span class="special-price">'.$currencyFormat."&nbsp;".number_format($child->getSpecialPrice(), 2, '.', '').'</span>';
					}
					if($i==count($newChildProducts)) {
						echo "<tr class=\"last\">";
					} else {
						echo "<tr>";
					}
					echo "<td>".$packSizeLabel."</td>";
					echo "<td>".$priceLabel."</td>";
					echo "<td><select id='p-".$child->getId()."'>";
					for($i=1; $i<=5; $i++) {
						echo "<option value='$i'>$i</option>";
					}
					echo "</select></td>";
					echo '<td><a id="s-'.$child->getId().'" class="related-buy-now" href="'.$url.'checkout/cart/add/product/'.$child->getId().'/?super_attribute[140]='.$child->getPackSize().'&mainid='.$conProduct->getId().'">Add to cart</a><br/><a class="refill_reminder_open" href="refillreminder?product_id='.$child->getId().'">Add to Reminder</a></td>';
					echo "</tr>";
				}
				echo "</table>";
			}
			?>
			<script type="text/javascript">
				jQuery(document).ready(function(){
					jQuery(".related-buy-now").click(function(event){
						var id = this.id.split("-");
						var value = jQuery("#p-"+id[1]).val();
						event.preventDefault();
						window.location.href = jQuery(this).attr("href")+"&qty="+value;

					});
					jQuery(".refill_reminder_open").fancybox({
						type: "iframe",
						width: "300px",
						height: "300px"
					});
				});
			</script>
			<?php //@nil for tabular packsize end ?>