<div class="faq-content-wrapper">
<script type="text/javascript"><!--
//faq script start
var accordion=function(){
	var tm=sp=10;
	function slider(n){this.nm=n; this.arr=[]}
	slider.prototype.init=function(t,c,k){
		var a,h,s,l,i; a=document.getElementById(t); this.sl=k?k:'';
		h=a.getElementsByTagName('dt'); s=a.getElementsByTagName('dd'); this.l=h.length;
		for(i=0;i<this.l;i++){var d=h[i]; this.arr[i]=d; d.onclick=new Function(this.nm+'.pro(this)'); if(c==i){d.className=this.sl}}
		l=s.length;
		for(i=0;i<l;i++){var d=s[i]; d.mh=d.offsetHeight; if(c!=i){d.style.height=0; d.style.display='none'}}
	}
	slider.prototype.pro=function(d){
		for(var i=0;i<this.l;i++){
			var h=this.arr[i], s=h.nextSibling; s=s.nodeType!=1?s.nextSibling:s; clearInterval(s.tm);
			if(h==d&&s.style.display=='none'){s.style.display=''; su(s,1); h.className=this.sl}
			else if(s.style.display==''){su(s,-1); h.className=''}
		}
	}
	function su(c,f){c.tm=setInterval(function(){sl(c,f)},tm)}
	function sl(c,f){
		var h=c.offsetHeight, m=c.mh, d=f==1?m-h:h; c.style.height=h+(Math.ceil(d/sp)*f)+'px';
		c.style.opacity=h/m; c.style.filter='alpha(opacity='+h*100/m+')';
		if(f==1&&h>=m){clearInterval(c.tm)}else if(f!=1&&h==1){c.style.display='none'; clearInterval(c.tm)}
	}
	return{slider:slider}
}();
//faq script stop
// --></script>



			<!-- <h2>FAQs/HELP</h2> -->
<div id="accordion"><dl id="slider" class="accordion">
<div>
<h1 class="faq-title">Questions About Our Company</h1>
<dt>
<p><strong>Q.1 <span style="text-decoration: underline;">About the Company?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>AllDayChemist.com is a professionally managed generic drugs distributor, supplying generic drugs and formulations to patients around the world. We offer great-value generics, without ever compromising on quality. The brands we offer are manufactured in facilities that have been approved by any / all of the following regulatory authorities:</p>

</li>
<li>1. Food and Drug Administration (FDA), US</li>
<li>2. Medicines Control Agency (MCA), UK</li>
<li>3. Therapeutic Goods Administration (TGA), Australia</li>
<li>4. Medicines Control Council (MCC), South Africa</li>
<li>5. National Institute of Pharmacy (NIP), Hungary</li>
<li>6. Pharmaceutical Inspection Convention (PIC), Germany</li>
<li>7. World Health Organisation (WHO)</li>

<p>The operations are always supervised by a team of qualified personnel including pharmacists. This helps us ensure that the drugs we source are not just inexpensive, but also conform to world-class standards of manufacturing and quality control. Dispensing is also done under the supervision of a pharmacist which ensures that the orders are packed and supplied as per the requirements in terms of both quality and quantity.  Most medications on this website will require a prescription from a licensed Doctor.</p>
</ul>
</dd> <dt>
<p><strong>Q.2 <span style="text-decoration: underline;">How do I know that you guys are a legitimate company? </span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>AllDayChemist.com is in business since 2002, our mission is to enforce consumer safety and confidence when they purchase their medications online. We subscribe to the services of both McAfee Secure and ControlScan, which are the industry gold-standards for all leading e-commerce sites. These services continuously monitor our site for any potential vulnerability. These vulnerabilities are reported to us and are immediately resolved by our team of IT specialists.</p>
<p>In addition, you will notice that all the pages which accept personal information are secure (SSL Certificate by GoDaddy) pages. A secure page means that the information transmitted through such pages is encrypted before transmission over the internet. You can thus try our service in confidence that you will always get what you pay for or your money back, guaranteed. We invite you to do your own due diligence on our company and suggest you start with our client testimonials or a search on the internet. Almost 50% of our new customers come from referrals of existing customers, try us once and you will see why we are the best online pharmacy.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.3 <span style="text-decoration: underline;">How long have you been in business? </span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>AllDayChemist.com  started in 2002 and since then we have been growing steadily.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.4 <span style="text-decoration: underline;">Do I require a prescription to order from your company? </span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>A prescription is needed for prescription medicines. The same may be sent by e-mail (as a scan) or by fax to our number +1-760-2845903.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.5 <span style="text-decoration: underline;">How much money will I save when I order from your company? </span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Most customers can save 40-90%, which can be hundreds of dollars per order. We also offer double pills offer on Men&rsquo;s Health products.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.6 <span style="text-decoration: underline;">Is my purchase through your company kept confidential? </span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Everything you submit to our company is done through SSL, which means that all your information is encrypted and confidential. We maintain our SSL to ensure that your privacy is guaranteed! Once your order is placed, your private information is encrypted in our database and accessible only to key staff and the pharmacy responsible for fulfilling your order. At no time is your information accessible by any party not involved in the fulfillment of your order. We do not sell, rent, or give away for free any information you provide us. Your order will always arrive discretely packaged to the name and address provided.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.7 <span style="text-decoration: underline;">Who do I contact about potential business opportunities with your company? </span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>General business inquiries can be forwarded by email to our business development manager at: <a href="mailto:info@alldaychemist.com"><span style="text-decoration: underline;">Click for Mail</span></a> Please be sure to include all relevant contact information, as well as a detailed proposal on how you wish to do business with our company so we can redirect your inquiry to the right individual.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.8 <span style="text-decoration: underline;">I am an affiliate or someone who wishes to affiliate with your company, how can I get more information on potential opportunities available to me? </span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>We have setup a special Affiliate Program that will detail the general affiliate programs we are currently offering. For larger scale affiliate opportunities, please contact our affiliate manager at&nbsp;<a href="mailto:info@alldaychemist.com"><span style="text-decoration: underline;">Click for Mail</span></a> Please be sure to include in your email the medications you are interested in selling as well as the estimated orders per month you are looking to generate. We are a discount online pharmacy who is more than happy to work with you.</p>
</li>
</ul>
</dd></div>
<div>

<h2>How ADC service works</h2>
<dt>
<p><strong>Step 1 &ndash; <span style="text-decoration: underline;">Navigating the website</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>The first step of the <strong>AllDayChemist</strong> is to determine if we have what you wish to order. You can do this by browsing through our US Brands , Generics or by simply using the search feature provided at the top of the page.</p>
<p>If you cannot find the product you want to order, please send us an e-mail to <a href="mailto:productenquiry@alldaychemist.com">productenquiry@alldaychemist.com</a></p>
<p>We take the risk out of placing your order online. Just take a look at a few of our customer <a href="testimonial.php"><span style="text-decoration: underline;">Testimonials.</span></a></p>
</li>
</ul>
</dd> <dt>
<p><strong>Step 2 &ndash; <span style="text-decoration: underline;">The Signup Page</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Once the product is selected, press &lsquo;add to cart&rsquo; button. This will open the 'Login / Register&rsquo; page. Here you can register as a new customer (by filling up your e-mail address) or login as an existing customer, if you already have an account with us. If you ever run into problems or have any questions when placing your order, be sure to <a href="contact.php"><span style="text-decoration: underline;">contact us</span></a> &ndash; we are available 24 hours a day 7 days a week to ensure that we are always there when you need us.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Step 3 &ndash; <span style="text-decoration: underline;">Dispensing Process</span> </strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Upon receipt of your order details they will fulfill and ship the order as fast as possible, but you must be aware that there may be product backorders or processing delays depending on the demand at the time. Our goal is to ensure that you have the order within our delivery guidelines and if we cannot achieve this goal for whatever reason we will inform you so that we can agree on how to proceed next &ndash; even if it is providing you with a full refund. Customer satisfaction is very important to us so never forget that we are working around the clock to ensure that everything goes smoothly.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Step 4 &ndash; <span style="text-decoration: underline;">In the Mail</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Once the pharmacy has shipped your order, they will update your account with the tracking and shipping details so that you may monitor the shipments until delivery. Please note that not every shipment is traceable, at least not right away. Shipments are generally traceable only after they have cleared your country's customs department.</p>
<p>Our pharmacy uses number of different shipping methods depending on where you reside and what products you are ordering. You should pay special attention to the date your order was shipped so that you can make an educated guess as to when it will be delivered. If the shipment has not arrived during our posted delivery times, then you should contact us so we can issue a trace and reship, or refund as per our guarantee.</p>
</li>
</ul>
</dd> <dt><p><strong>Step 5 &ndash; <span style="text-decoration: underline;">Successfully Delivered</span></strong></p></dt> <dd> 
<ul class="list">
<li>
<p>This is the final step to the AllDayChemist <strong>service</strong> process. You receive your product, we complete the <strong>service</strong>.</p>
<p>We absolutely love this step because it gives us so much pleasure in knowing that we have made such a difference in people&rsquo;s lives. It is here that we encourage you to please send us a <a href="testimonial.php"><span style="text-decoration: underline;">testimonial </span></a> and tell all your friends and family about our <strong>online drugstore</strong> service so that we can help them too!</p>
<p>If for any reason your order of <strong>prescription drugs</strong> is not successfully delivered, we will of course reship free of charge or provide you with a 100% refund as per our satisfaction guarantee. We rely on satisfied customers who use our <strong>online drugstore</strong> to stay in business, so you can be rest assured that we will do everything in our power to keep you happy and smiling every step of the way.</p>
</li>
</ul>
</dd></div>
<div>

<h2>Order Related Questions</h2>
<dt>
<p><strong>Q.1 <span style="text-decoration: underline;">How long does it take to ship the drugs to my home or office?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Please allow up to two weeks for delivery.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.2 <span style="text-decoration: underline;">Can I buy more than a three month supply at a time?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Yes and no. It depends on the medications that are being purchased online, their size, the destination country, and the stock situation at the point of purchase. In the majority of cases ordering a three, six, or even a nine month supply of medications will not pose a problem, but the pharmacy reserves the right to request additional shipping charges if the order is too large to be covered by their typical shipping fee, and as some countries limit a maximum import of three months&rsquo; supply at a time, the pharmacy may have to split the package into separate shipments to meet this regulation. In this event, we will contact you to confirm before the order is dispatched.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.3 <span style="text-decoration: underline;">Can I request specific expiration dates for the medications I order?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>All medications shipped out by the pharmacy have a minimum of six months expiry date from the time they are shipped. If you require a longer expiry then feel free to <a href="contact.php"><span style="text-decoration: underline;">Contact Us</span></a> and we will do our best to assist you with your requirements.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.4 <span style="text-decoration: underline;">Why your prices so low? </span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Please note that the product costs are based on their actual cost and our per unit cost is not highly inflated as is the case with other online pharmacies.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.5 <span style="text-decoration: underline;">Are the products mailed to me the same as what I get at my local pharmacy? </span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Yes and No. We deals in generic products and the product contains exactly the same active ingredient as their branded drug. You will get exactly the same product but the only difference is the name of the manufacturer.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.6 <span style="text-decoration: underline;">If I don't see my prescription medication on your price list, does that mean your company doesn't carry it?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>There are literally 1000's of medications available on the market and not all are listed on AllDayChemist.com. We do however list the most common medications and our partner pharmacies are frequently updating our website with what they are able to offer for sale. Please note: many times we list an online medication for sale but a customer does not know how to spell the medication name correctly and as a result, AllDayChemist.com&rsquo;s &lsquo;prescription drugs&rsquo; search engine may indicate that we don't carry it. When searching for an incorrect medication name, you will receive misleading results, so if you can't locate what you are looking for then please <a href="medicinessearch.php"><span style="text-decoration: underline;">contact us</span></a> and we will assist you in your search. In the event a medication is not listed we can also try to arrange the same if it not a controlled drug.</p>
<p>If you still can't find a particular medication online then be sure to fill out our medication request form so we can contact you when it becomes available.</p>
<p>Please note, we do not and will not sell any controlled substances.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.7 <span style="text-decoration: underline;">How do I place an order for multiple people living at the same household? </span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>To save on shipping and processing, AllDayChemist is more than happy to send multiple prescription medications to a single household address, even if the medications belong to different people. For example, a husband and wife could order both their medications at once and only pay the shipping and processing fee once.</p>
<p>The ordering process is the same whether you order for one person or many. You simply search for all the online medications you would like to order, follow the sign up instructions, and then fill out the address you would like them sent too. Remember, we are here to save you money any way we can!</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.8 <span style="text-decoration: underline;">What is your return policy?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>AllDayChemist has a 100% Satisfaction Guarantee.</p>
<p>If for some reason, your order does not show up or is damaged in transit, we will ship you another package or issue you a full refund as per your request. If however, you received a partial order, we will issue you a full refund, and then charge your Credit Card again for the remaining balance (so you are fully refunded, and then charged only for the product (s) you received).</p>
<p>We will ask you to first allow 30 business days from the day the order was shipped. If after those 30 days, you have not received the package, or if you received any notification that your package was on hold or returned to sender, please send us a ticket (Refund Section) and we will take care of your request promptly.</p>
<p>Please Note: If you have any queries regarding your transaction, please contact us by sending a mail or call us at 213-291-2588</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.9 <span style="text-decoration: underline;">What happens if I want to cancel my order?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>If your order has already been dispatched from the pharmacy, unfortunately we cannot issue a refund. If your order has not been dispatched you will be charged a $10.00 USD cancellation fee. If the reason for the cancellation is due to a shortage or backorder of a medication we will not charge you any cancellation fees.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.10 <span style="text-decoration: underline;">I wish my package to be sent discretely, can you arrange this?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>All packages are already sent discretely to protect your privacy. We do ship the consignments in small bubble envelopes or card boxes.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.11 <span style="text-decoration: underline;">What do I do if one of my products in my order is back-ordered?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>If any of your online medications are back ordered, you will be notified by our customer support center of the delay and the expected time the product will arrive in stock to the pharmacy. Please note that if the brand ordered by you is not available we will switch the brand to another reputed pharmacy brand. For example, if you order brand name Atorlip (manufactured by Cipla) we will only send you the same product manufactured by another leading pharma company.</p>
<p>In the event of any order change whereby the sale price differs, we will never charge you extra without your explicit consent. In most cases, if a product is not in stock where you ordered it from and is in stock somewhere else at a more expensive price, we will change the product and take the loss. It is only in special circumstances where we may need to charge you more and will always call you to confirm before doing so.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.12 <span style="text-decoration: underline;">I want to change my order after placing it, how can I do this? </span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>This is only possible if you contact us within 24 working hours. If the order has been sent to the physician or pharmacy it will not be possible to make any changes. We apologize in advance for this inconvenience.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.13 <span style="text-decoration: underline;">I want a copy of my receipt for a particular order, how can I get this mailed to me?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>This can be done by logging into your account and then going to &ldquo;My past order&rdquo;. Now you have the option to VIEW your order details in form of PDF file. Click on the PDF file and print the order option will open a  file with your online medication invoice that you can save and print directly from your computer.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.14 <span style="text-decoration: underline;">Will my insurance company reimburse me for the online medication I order through your company?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>This is best checked with your insurance company prior to placing your order. We will provide you with a legal invoice to submit to the insurance company and they are welcome to contact us to check on certain details. It is important to note however that we will never release personal information about you or your order history without your prior consent, so you must tell us in advance before you submit your details so that we can place a note on your account that verification with XYZ insurance company will be allowed, otherwise the only information we will release to a third party will be our company information for their records.</p>
</li>
</ul>
</dd></div>
<div>

<h2>Order Status Related Questions</h2>
<dt>
<p><strong>Q.1 <span style="text-decoration: underline;">Why is my order on "Awaiting payment process" or "Preparation in progress" or "Payment error"?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>When a order is in this status, it means that it has not yet been approved and your card has not been charged. You may simply ignore the order if you want to cancel the same.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.2 <span style="text-decoration: underline;">Why is my order on "Dispensing"?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>When a order is in this status, it means that the order has been given to our pharmacist and after reviewing the order details the order will give to our dispatch department to ship.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.3 <span style="text-decoration: underline;">Why is my order on "Hold order"?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Your order may be on "Hold" for any of the following reasons:</p>

<ol>
<li>One of the product/s is out of stock.</li>
<li>Prescription copy has not been received.</li>
<li>You had made a request to add or remove product/s from your order.</li>
<li>Any other issue.</li>
</ol>

<p>If you ever see your order on this status please give us a call or send the <a href="mailto:info@alldaychemist.com"><span style="text-decoration: underline;">Click for Mail</span></a> to sort out issue.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.4 <span style="text-decoration: underline;">Why is my order showing as "Cancelled" or "Declined"?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Your order is on this status because your payment initially failed when placing your order. You need to try again or if you have a VISA card, you can place the order over the phone at 213 291 2588.</p>
<p>All our transactions are done on a secure page and the card details would be destroyed after completion of the transaction.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.5 <span style="text-decoration: underline;">Why is my order on "Awaiting check payment" or "Awaiting bank wire payment"?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Your order is on this status because you have chosen to pay through Check / Money order or Wire Transfer. Your order would be shipped as soon as we receive the payment of your order.</p>
</li>
</ul>
</dd></div>
<div>

<h2>Payment Related Questions</h2>
<dt>
<p><strong>Q.1 <span style="text-decoration: underline;">What is the CVV number you ask for on your sign up page? Where can I find it?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>CVV is an anti-fraud security feature to help verify that you are in possession of your credit card. For Visa/MasterCard, the three-digit CVV number is printed on the signature panel on the back of the card immediately after the card's account number. For American Express, the four-digit CVV number is printed on the front of the card above the card account number.</p>
<p>
<table border="0" cellspacing="2" cellpadding="2" width="100%">
<tbody>
<tr>
<td><strong>Visa/MasterCard</strong></td>
<td><strong>American Express</strong></td>
</tr>
<tr>
<td><img src="images/master.jpg" border="0" /></td>
<td><img src="images/american.jpg" border="0" /></td>
</tr>
<tr>
<td>A 3-digit number in reverse italic on the back of your credit card</td>
<td>A 4-digit number on the front, just above your credit card number</td>
</tr>
</tbody>
</table>
</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.2 <span style="text-decoration: underline;">What payment methods will your company accept?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>We accepts Visa, Check/ Money Orders. For larger orders (more than $1,000 USD), we also consider the use of a Wire Transfer/ Check/ Money order however you should <a href="contact.php"><span style="text-decoration: none;">contact us</span></a> <a href="mailto:info@alldaychemist.com"><span style="text-decoration: underline;">Click for Mail</span></a> before placing such an order.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.3 <span style="text-decoration: underline;">If I send in a check or money order how long will it take for you to receive it and process my order?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Sending in a check or money order for your online medication is the slowest way to send us payment and as a result it will affect the speed of your order. We will be unable to process the order until payment has been received and depending on the country you are sending the payment from and whether you are a new or existing customer, there may be even further delays while we wait for the payment to clear. We recommend that if you are sending payment for your medication by mail, you should always use a registered service preferably with a tracking number so we can trace it in case of delays.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.4 <span style="text-decoration: underline;">My credit card was refused, why?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Credit cards can be refused for a number of reasons, many of which are out of both your and our control. When you place an order with a credit card, the information you submit goes directly to our merchant bank at which point it is tested through various fraud. The following are the main reasons of decline transactions:</p>
<p>If the Billing and shipping address are different: In this situation, the card-issuing Bank may stop the transaction to avoid suspect Fraud cases. In such a case, please inform your Bank that you are expecting a charge from &rdquo;AllDayChemist,  &ldquo;MEDS&rdquo; , &ldquo;Money Booker&rdquo; or &ldquo;TitanMoneyExpress.&rdquo;Once you do this, you may try again or if you have a VISA card you may place the order with us over the phone at 213-291-2588 (If dialing from outside the US, please dial +1-213-291-2588).</p>
<p>If you are using a card from a different state (or country) where the card was actually issued: This happens if your card was issued at your address but you are using the same from a different state or country. In such a case, you may contact us (by phone) and place the order.</p>
<p>As you can see, there are many channels your transaction must pass through before it is accepted and if there is a problem with even one of them your entire transaction for your online medication will be declined. In the event it is declined, please give us a call to confirm the order.  Please note that some banks will require your authorization after they accept the charge from our company. For example, if you normally use your card only in USA and your bank suddenly sees a transaction from overseas they may think that the transaction is suspicious and wish to speak with you before allowing it to go through. In this case, they may call you to confirm or you may need to call and alert them of your approval. We recommend you check with your bank after placing an order just to make sure everything went through successfully. It is important to note that all credit card processing through our company is done outside the USA and Canada.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.5 <span style="text-decoration: underline;">I don't recognize the charge on my card, is it from your company?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Our charge will appear in the name of 'MEDS', 'PHARMACY', 'RX-MEDS'.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.6 <span style="text-decoration: underline;">The amount charged on my card doesn't match my order amount, why is this?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>This is quite possible and the reason why is because some of our banks do not charge in US dollars but rather in other currencies such as the Euro. Because the currency exchange rates fluctuate daily, the amount charged will not exactly equal what it shows on your invoice. In fact, in many cases it will show less as each day we undervalue the exchange rate to give you a slight discount before charging you. Of course, some banks also like to take their commission for these multi-currency transactions and if your bank is like this they may charge you extra fees as well. Unfortunately we can't do anything to avoid this but if for some reason your credit card shows that you were charged much more than the amount you paid please <a href="mailto:info@alldaychemist.com"><span style="text-decoration: underline;">contact us</span> </a> and send in a copy of the statement (fax or email) and will we do our best to rectify the matter by applying an account credit.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.7 <span style="text-decoration: underline;">I was double charged, who do I contact about this? </span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>If you were double charged please accept our sincerest apologies. Sometimes there is a communication error between our website and the bank and as a result the website will automatically try again causing a double charge. Many times we will notice this before you do and refund you immediately, however if you notice the error before us then let us know and we will issue the refund without delay.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.8 <span style="text-decoration: underline;">My refund hasn't showed up on my credit card yet, how long should it take?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>It can take up to seven to ten business days for your refund to show up on your credit card. Many times it will show up in only three business days but sometimes there are bank delays that are out of our control and for this we apologize in advance. If you have not received your refund in seven to ten business days then please be sure to <a href="mailto:info@alldaychemist.com"><span style="text-decoration: none;">contact us </span></a> right away so we can follow up with the bank and find out why.</p>
</li>
</ul>
</dd></div>
<div>

<h2>Account Related Questions</h2>
<dt>
<p><strong>Q.1 <span style="text-decoration: underline;">How can I update my shipping address or contact information?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Simply login to your account and visit the "Account Information" page whereby you will be able to update your contact information. Please note that if you need to change your shipping address in the middle of an order you should contact us immediately so that we can stop the order before shipment.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.2 <span style="text-decoration: underline;">How can I change my password?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Simply login to your account and visit the "Change Password" page. We recommend you choose a strong password for your account so as to increase the security.</p>
<p>Common guidelines for choosing good passwords are designed to make passwords less easily discovered by intelligent guessing:</p>

</li>
<li>Include numbers, symbols, upper and lowercase letters in passwords</li>
<li>Password length should be around 5 to 14 characters</li>
<li>Avoid any password based on repetition, dictionary words, letter or number sequences, usernames, relative or pet names, or biographical information (eg, dates, ID numbers, ancestors names or dates, ...).</li>
<li>If the system is case sensitive use capital and lower-case letters</li>
<li>Password should be easy to remember for the user</li>

</ul>
</dd> <dt>
<p><strong>Q.3 <span style="text-decoration: underline;">Examples of weak passwords</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>As with any security measure, passwords vary in effectiveness (i.e., strength); some are weaker than others. For example, the difference in weakness between a dictionary word and a word with obfuscation (i.e., letters in the password are substituted by, say, numbers -- a common approach) may cost a password cracking device a few more seconds. The examples below illustrate various ways weak passwords might be constructed, all of which are based on simple patterns which result in extremely low entropy:</p>

</li>
<li>Default Passwords (as supplied by the system vendor and meant to be changed at installation time): password, default, admin, guest, etc.</li>
<li>Dictionary words: chameleon, RedSox, sandbags,bunnyhop! IntenseCrabtree etc</li>
<li>Words with number substitutions: password1, deer2000, john1234, etc</li>
<li>Words with simple obfuscation: p@ssw0rd, l33th4x0r, g0ldf1sh, etc</li>
<li>Doubled words: crabcrab, stopstop, treetree, etc</li>
<li>Common sequences: qwerty, 12345678, mnbvcxz, etc</li>
<li>Numeric sequences based on well known numbers such as 911, 314159, or 27182, etc</li>
<li>Identifiers: jsmith123, 1/1/1970, 555-1234, "your username", etc</li>
<li>Anything personally related to you: license plate number, Social Security number, current or past telephone number, student ID, address, birthday, relatives' or pets' names/nicknames/birthdays/initials, etc.</li>

<p>There are many other ways a password can be weak, corresponding to the strengths of various attack schemes; the core principle is that a password should have high entropy (usually taken to be equivalent to randomness) and not be readily derivable by any "clever" pattern, nor should passwords be mixed with information identifying the user.</p>
<p>If you ever lose your password you may click on &ldquo;Forgot Password&rdquo; in login area or <a href="contact.php">contact us</a> and we will be glad to assist.</p>
</ul>
</dd> <dt>
<p><strong>Q.4 <span style="text-decoration: underline;">How can I order a refill of a previous order?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Simply login to your account and visit the "My Past Orders" page. Once you are at this page you will see that every order you have ever ordered will be displayed in a convenient list whereby you can select which ones you wish to refill and then press the &ldquo;Reorder&rdquo; button.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.5 <span style="text-decoration: underline;">I am not receiving emails you sent me, what is the problem?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>If you are having problems receiving email from us please try the following:</p>
<ol>
<li>Ensure your email address is correct in your account</li>
<li>Check your SPAM filters and junk mail box</li>
<li>Add us to your mail server's white list</li>
<li>Try using another email address from a different service provider (ie: if you are using Hotmail, try using Yahoo!)</li>
</ol>

<p>If you have checked all of the above and are still having problems receiving our emails then <a href="contact.php">contact us </a>and we will be glad to help your solve the problem.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.6 <span style="text-decoration: underline;">I wish to cancel my account, is this possible?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>It is possible to cancel your account however for security reasons you must <a href="contact.php"><span style="text-decoration: underline;">contact us</span></a> to have this completed. As no card information is stored with the account, there may not be any reason for exercising this option.</p>
</li>
</ul>
</dd></div>
<div>

<h2>Shipping Related Questions</h2>
<dt>
<p><strong>Q.1 <span style="text-decoration: underline;">My online medication order has not shipped yet, what is the delay?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>There are a number of reasons why your AllDayChemist order may not have shipped yet and the easiest way to learn why is just to <a href="contact.php"><span style="text-decoration: underline;">contact us</span></a> and ask. For quick reference however your best indication of why your order hasn't been shipped is to check the order status and for the most part it is pretty self explanatory. For example, if the status is <strong>" Awaiting payment process "</strong> there is a problem with your payment and you must <a href="contact.php"><span style="text-decoration: underline;">contact us</span></a> to resolve the problem, or we are still waiting for your payment to arrive in the mail. For a more detailed explanation of the various drug delivery status codes, please see our <a href="cms.php?id_cms=92"><span style="text-decoration: underline;">order status FAQ</span></a>.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.2 <span style="text-decoration: underline;">My online medication order was shipped but the tracking numbers are not yet showing up in the courier service, what is the problem?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>When tracking information is sent to you, it is important to note that it may not show up in the courier's website until many days after the pharmacy has shipped your order. In most cases, the package must reach the destination country (your country) before any tracking will be displayed. As such, you must be patient while your order makes its way around the world to you. If tracking is not showing up seven business days after it is entered in your account then we ask you to please <a href="contact.php"><span style="text-decoration: underline;">contact us</span></a> so that we may pass a query onto the courier to make sure there are no unexpected delays.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.3 <span style="text-decoration: underline;">My order was refused by customs, what do I do now?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>We have prepared a small write-up to explain the process of what happens when customs refuses entry of your order, please read it carefully first and don't hesitate to <a href="contact.php"><span style="text-decoration: underline;">contact us</span></a> for any clarifications or further information.</p>
<p>Why would Customs return my package?</p>
<p>For those who are new to ordering their medications from abroad, it is important to know that all packages are subject to refusal when entering a country&rsquo;s border. This is by no means a cause for concern. It is your customs' job to accept or deny the mail coming into the country and medications are no exception. As there is no way for them to know whether the medications are legitimate, the customs' officer will usually return all medications to the origin pharmacy as a precaution.</p>
<p>Could my medications be fake or inferior?</p>
<p>This is a common question asked by our new customers and it is very important they understand how AllDayChemist works when compared to all the other online pharmacies on the Internet. When you place an order with our service, we not only protect you from online fraud, we also protect you from the fears of receiving fake or inferior products. All our products are manufactured by leading Indian Pharmacies and their facilities are approved by USFDA or other respected government authorities.</p>
<p>What will happen to my order now?</p>
<p>Our guarantee states that you will get your products and a refused package from customs is no exception. Simply contact us and we send you a free reshipment of your order and depending on the availability of your products in stock, we will have your new tracking number sent to you right away.</p>
<p>How long will it take to receive my reshipment order?</p>
<p>The reshipment may takes 10-20 days to deliver.</p>
<p>Will my order be refused again upon the reshipment?</p>
<p>There is always a possibility that your order could be refused again but the chances are very slim. Typically less than 1% of the orders we ship are refused by customs.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.4 <span style="text-decoration: underline;">If my online medication order is returned to the pharmacy, can it be reshipped?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Yes, the reshipment will be issued to you and we will inform the tracking number.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.5 <span style="text-decoration: underline;">I am out of medications and need priority processing, can I get this?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>You should call us in advance to let us know you require priority shipment of your order. Alternatively, you can e-mail us when you place your order. Although we do not ship it any other method than the one that we are currently doing, we can ensure your order jumps to the top of the queue and is shipped right away to try to save you a few days on the fulfillment time. Please note that although we can guarantee that the order will ship right away (assuming that the products are in stock), we cannot guarantee that the shipping company will bring it to you without delay. Once we place the order in the mail, it really is out of our control.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.6 <span style="text-decoration: underline;">My online medication order is later than the listed shipping times, why is this?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>This could result in an order being refused by customs or an unforeseen delay with the shipping company. Please do not wait too long for your package to arrive. If it is outside the listed shipping times, contact us so we can investigate further.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.7 <span style="text-decoration: underline;">I want to cancel my order after it has been shipped, is this possible?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Unfortunately you cannot. You may only cancel your order before it has been shipped from the pharmacy, and even that will be subject to <a href="cms.php?id_cms=91#10"><span style="text-decoration: underline;">cancellation fee</span></a>.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.8 <span style="text-decoration: underline;">What is Discreet Packaging and how does it work?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Please note that we do ship in small bubble envelopes or card boxes and do not enclose any literature about the products.</p>
</li>
</ul>
</dd></div>
<div>

<h2>Delivery Related Questions</h2>
<dt>
<p><strong>Q.1 <span style="text-decoration: underline;">How can I tell that the online medications I ordered are legitimate?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>All of our medications come with the original instructions and packaging that contains the lot number and expiry that can be cross checked with the manufacturer. Our generics also come in original packaging; however most of the generics from India come only as the blister packs with the manufacturer information printed directly on the reverse of the blister. You will never have to worry about the origin of the medications you order through AllDayChemist.com.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.2 <span style="text-decoration: underline;">I received only part of my order, where is the rest of it?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>When you have a very large order, we may split the order into two or more separate shipments spaced roughly 2-3 days in which case you will receive the remainder of your order shortly after the first part has arrived.</p>
<p>As always, if you have any questions you may always <a href="contact.php"><span style="text-decoration: underline;">contact us</span></a> and we will be glad to clarify things for you.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.3 <span style="text-decoration: underline;">The medication that I ordered online looks different than what I am used to, why is this?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>This can and will happen when you order medication online from different countries, especially when you are ordering generics which can be manufactured by several different manufacturers. Because a generic medication can be manufactured by any company, each company will use the exact same active ingredients but the process of creating them may differ and thus the shape, color, and size of the tablets or capsules may differ slightly to distinguish them from their competitors. This in no way affects the efficacy of the medications. All the medications listed / supplied by us are chosen after a rigorous auditing process.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.4 <span style="text-decoration: underline;">I was unable to pickup my parcel and it was returned to the pharmacy, what do I do now?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>If your parcel was returned to the pharmacy for any reason, we can charge you shipping again and reship out your package but as we do not keep the card details of our client, you need to call us to pay the shipping cost. If the consignment was returned to the pharmacy due to our fault, we will re-ship it without any charges. Please get in touch with us in either of the cases.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.5 <span style="text-decoration: underline;">Can I return my medication after it has been delivered?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>The only instance in which you can return a medication after it has been delivered to you is if the pharmacy sent you the wrong medication or if the medication arrived damaged. In the event of either of these scenarios, the pharmacy will promptly reship the medication to rectify the mistake.</p>
<p>Under no other circumstances can we allow a product to be returned or refunded outside these scenarios.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.6 <span style="text-decoration: underline;">I received the wrong dosage of medication, what do I do?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Please <a href="contact.php"><span style="text-decoration: underline;">contact us</span></a> immediately so we can inform the pharmacy. The correct medication will be promptly sent to you.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.7 <span style="text-decoration: underline;">The medications in my order were damaged during transit, what do I do?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Please <a href="contact.php"><span style="text-decoration: underline;">contact us</span></a> immediately so we can inform the pharmacy. Your medication will be promptly resent to you.</p>
</li>
</ul>
</dd></div>
<div>

<h2>Other Questions</h2>
<dt>
<p><strong>Q.1 <span style="text-decoration: underline;">I am having trouble ordering. Do you have detailed ordering instructions?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>

<ol>
<li> Search for the medicine using our brand / generic search option on the home page. Or browse through categories through the &lsquo;Categories&rsquo; section. You may also use the brand / generic search option in the &lsquo;Product Search &rsquo; section. Once you have found your product / s, click on it and you will be taken to the next level of the Shopping Cart . </li>
<li>Add the desired quantity of the desired product in the box</li>
<li>Click On &lsquo;Add to Cart&rsquo; button</li>
<li>Repeat steps 1-3 For more selections</li>
<li>Once the selection is complete, click on Checkout and provide personal information and shipping information</li>
</ol>

</li>
</ul>
</dd> <dt>
<p><strong>Q.2 <span style="text-decoration: underline;">I am not comfortable in using credit card online? Can I fax my credit card information?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>We value the security of our site. Our user information page and credit card information page are secure pages. You will notice 'https:' instead of the usual 'http:' in the address bar of your browser. We also have ControlScan certifications (leading certifications for e-commerce sites). We however understand that there may be some people who are still uncomfortable in sending their credit card details over the net. <a href="fax.php"><span style="text-decoration: underline;">Please click here for the 'Fax Order Form.'</span></a> This form can be used for both ordering and re-ordering. You can mail us at <a href="mailto:info@alldaychemist.com"><span style="text-decoration: underline;">Click for Mail</span></a> for any clarifications.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.3 <span style="text-decoration: underline;">Do I need a prescription to purchase drugs online?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>A. A prescription is needed for prescription medicines. The same may be sent by e-mail (as a scan) or by fax to our number +1-760-2845903.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.4 <span style="text-decoration: underline;">Why should I purchase from you versus another online pharmacy?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>We are the only online pharmacy that supplies drugs from the top pharmaceutical firms of the United States from outside of the United States where these drugs are sold at a much lower price. We may also provide medicines which are made by leading manufacturers who export to most countries.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.5 <span style="text-decoration: underline;">The drugs that you sell, are they from reputable drug firms?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Yes, the majority of firms selling drugs to other countries are the same firms selling these drugs in the USA. Generally, they may call the drug another brand name, but they are the same drug generically.</p>
<p>In addition we also supply medications manufactured by leading Indian manufacturers. The Indian pharma industry is the fourth largest in the world in terms of volume. The top fifty manufacturers in terms of value are:</p>
<table border="1" width="100%">
<tbody>
<tr>
<td>Ranbaxy Laboratories Ltd.</td>
<td><a href="http://www.ranbaxy.com/"><span style="text-decoration: underline;">http://www.ranbaxy.com/</span></a></td>
</tr>
<tr>
<td>Cipla Ltd.</td>
<td><a href="http://www.cipla.com/"><span style="text-decoration: underline;">http://www.cipla.com/</span></a></td>
</tr>
<tr>
<td>Dr. Reddy'S Laboratories Ltd.</td>
<td><a href="http://www.drreddys.com/index.html"><span style="text-decoration: underline;">http://www.drreddys.com/index.html</span></a></td>
</tr>
<tr>
<td>Nicholas Piramal India Ltd.</td>
<td><a href="http://www.piramalhealthcare.com/"><span style="text-decoration: underline;">http://www.piramalhealthcare.com/</span></a></td>
</tr>
<tr>
<td>Aurobindo Pharma Ltd.</td>
<td><a href="http://www.aurobindo.com/"><span style="text-decoration: underline;">http://www.aurobindo.com/</span></a></td>
</tr>
<tr>
<td>Glaxosmithkline Pharmaceuticals Ltd.</td>
<td><a href="http://www.gsk-india.com/"><span style="text-decoration: underline;">http://www.gsk-india.com/</span></a></td>
</tr>
<tr>
<td>Lupin Ltd.</td>
<td><a href="http://www.lupinworld.com/"><span style="text-decoration: underline;">http://www.lupinworld.com/</span></a></td>
</tr>
<tr>
<td>Cadila Healthcare Ltd.</td>
<td><a href="http://www.cadilapharma.com/"><span style="text-decoration: underline;">http://www.cadilapharma.com/</span></a></td>
</tr>
<tr>
<td>Sun Pharmaceutical Inds. Ltd.</td>
<td><a href="http://www.sunpharma.com/"><span style="text-decoration: underline;">http://www.sunpharma.com/</span></a></td>
</tr>
<tr>
<td>Wockhardt Ltd.</td>
<td><a href="http://www.wockhardtin.com"><span style="text-decoration: underline;">http://www.wockhardtin.com</span></a></td>
</tr>
<tr>
<td>Aventis Pharma Ltd.</td>
<td><a href="http://www.aventispharmaindia.com/"><span style="text-decoration: underline;">http://www.aventispharmaindia.com/</span></a></td>
</tr>
<tr>
<td>Orchid Chemicals &amp; Pharmaceuticals Ltd.</td>
<td><a href="http://www.orchidpharma.com/"><span style="text-decoration: underline;">http://www.orchidpharma.com/</span></a></td>
</tr>
<tr>
<td>Ipca Laboratories Ltd.</td>
<td><a href="http://www.ipcalabs.com/"><span style="text-decoration: underline;">http://www.ipcalabs.com/</span></a></td>
</tr>
<tr>
<td>Alembic Ltd.</td>
<td><a href="http://www.alembic-india.com/"><span style="text-decoration: underline;">http://www.alembic-india.com/</span></a></td>
</tr>
<tr>
<td>Pfizer Ltd.</td>
<td><a href="http://www.pfizerindia.com"><span style="text-decoration: underline;">http://www.pfizerindia.com</span></a></td>
</tr>
<tr>
<td>Morepen Laboratories Ltd.</td>
<td><a href="http://www.morepen.com/"><span style="text-decoration: underline;">http://www.morepen.com/</span></a></td>
</tr>
<tr>
<td>U S V Ltd.</td>
<td><a href="http://www.usvindia.com/"><span style="text-decoration: underline;">http://www.usvindia.com/</span></a></td>
</tr>
<tr>
<td>Matrix Laboratories Ltd.</td>
<td><a href="http://www.matrixlabsindia.com/"><span style="text-decoration: underline;">http://www.matrixlabsindia.com/</span></a></td>
</tr>
<tr>
<td>Biocon Ltd.</td>
<td><a href="http://www.biocon.com/"><span style="text-decoration: underline;">http://www.biocon.com/</span></a></td>
</tr>
<tr>
<td>Novartis India Ltd.</td>
<td><a href="http://www.novartis.com/"><span style="text-decoration: underline;">http://www.novartis.com/</span></a></td>
</tr>
<tr>
<td>Torrent Pharmaceuticals Ltd.</td>
<td><a href="http://www.torrentpharma.com/"><span style="text-decoration: underline;">http://www.torrentpharma.com/</span></a></td>
</tr>
<tr>
<td>Abbott India Ltd.</td>
<td><a href="http://www.abbott.co.in/"><span style="text-decoration: underline;">http://www.abbott.co.in/</span></a></td>
</tr>
<tr>
<td>Cadila Pharmaceuticals Ltd.</td>
<td><a href="http://www.cadilapharma.com/"><span style="text-decoration: underline;">http://www.cadilapharma.com/</span></a></td>
</tr>
<tr>
<td>Merck Ltd.</td>
<td><a href="http://www.merck.co.in"><span style="text-decoration: underline;">http://www.merck.co.in</span></a></td>
</tr>
<tr>
<td>Unichem Laboratories Ltd.</td>
<td><a href="http://www.unichem.com/"><span style="text-decoration: underline;">http://www.unichem.com/</span></a></td>
</tr>
<tr>
<td>Glenmark Pharmaceuticals Ltd.</td>
<td><a href="http://www.glenmarkpharma.com"><span style="text-decoration: underline;">http://www.glenmarkpharma.com</span></a></td>
</tr>
<tr>
<td>Wyeth Ltd.</td>
<td><a href="http://www.wyethindia.com/index.asp"><span style="text-decoration: underline;">http://www.wyethindia.com/index.asp</span></a></td>
</tr>
<tr>
<td>Divi'S Laboratories Ltd.</td>
<td><a href="http://www.divislabs.com/"><span style="text-decoration: underline;">http://www.divislabs.com/</span></a></td>
</tr>
<tr>
<td>J B Chemicals &amp; Pharmaceuticals Ltd.</td>
<td><a href="http://www.jbcpl.com/"><span style="text-decoration: underline;">http://www.jbcpl.com/</span></a></td>
</tr>
<tr>
<td>F D C Ltd.</td>
<td><a href="http://www.fdcindia.com/"><span style="text-decoration: underline;">http://www.fdcindia.com/</span></a></td>
</tr>
<tr>
<td>Emcure Pharmaceuticals Ltd.</td>
<td><a href="http://www.emcure.co.in/"><span style="text-decoration: underline;">http://www.emcure.co.in/</span></a></td>
</tr>
<tr>
<td>Panacea Biotec Ltd.</td>
<td><a href="http://www.panacea-biotec.com/"><span style="text-decoration: underline;">http://www.panacea-biotec.com/</span></a></td>
</tr>
<tr>
<td>Strides Arcolab Ltd.</td>
<td><a href="http://www.stridesarco.com/"><span style="text-decoration: underline;">http://www.stridesarco.com/</span></a></td>
</tr>
<tr>
<td>Shasun Chemicals &amp; Drugs Ltd.</td>
<td><a href="http://www.shasun.com/"><span style="text-decoration: underline;">http://www.shasun.com/</span></a></td>
</tr>
<tr>
<td>Elder Pharmaceuticals Ltd.</td>
<td><a href="http://www.elderindia.com/"><span style="text-decoration: underline;">http://www.elderindia.com/</span></a></td>
</tr>
<tr>
<td>Macleods Pharmaceuticals Ltd.</td>
<td><a href="http://www.macleodspharma.com/"><span style="text-decoration: underline;">http://www.macleodspharma.com/</span></a></td>
</tr>
<tr>
<td>Aarti Drugs Ltd.</td>
<td><a href="http://www.aartidrugs.com/"><span style="text-decoration: underline;">http://www.aartidrugs.com/</span></a></td>
</tr>
<tr>
<td>Dabur Pharma Ltd.</td>
<td><a href="http://www.dabur.com/default.aspx"><span style="text-decoration: underline;">http://www.dabur.com/default.aspx</span></a></td>
</tr>
<tr>
<td>Nectar Lifescience Ltd.</td>
<td><a href="http://www.neclife.com/"><span style="text-decoration: underline;">http://www.neclife.com/</span></a></td>
</tr>
<tr>
<td>Ind-Swift Ltd.</td>
<td><a href="http://www.indswift.com/"><span style="text-decoration: underline;">http://www.indswift.com/</span></a></td>
</tr>
<tr>
<td>Astrazeneca Pharma India Ltd.</td>
<td><a href="http://www.astrazenecaindia.com/"><span style="text-decoration: underline;">http://www.astrazenecaindia.com/</span></a></td>
</tr>
<tr>
<td>Unimark Remedies Ltd.</td>
<td><a href="http://www.unimarkremedies.com/"><span style="text-decoration: underline;">http://www.unimarkremedies.com/</span></a></td>
</tr>
<tr>
<td>Jagsonpal Pharmaceuticals Ltd.</td>
<td><a href="http://www.jagsonpal.com/"><span style="text-decoration: underline;">http://www.jagsonpal.com/</span></a></td>
</tr>
<tr>
<td>Organon (India) Ltd.</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>Surya Pharmaceutical Ltd.</td>
<td><a href="http://www.suryapharma.com/pages/index.htm"><span style="text-decoration: underline;">http://www.suryapharma.com/pages/index.htm</span></a></td>
</tr>
<tr>
<td>Ind-Swift Laboratories Ltd.</td>
<td><a href="http://www.indswiftlabs.com/"><span style="text-decoration: underline;">http://www.indswiftlabs.com/</span></a></td>
</tr>
<tr>
<td>Kopran Ltd.</td>
<td><a href="http://www.kopran.com/"><span style="text-decoration: underline;">http://www.kopran.com/</span></a></td>
</tr>
<tr>
<td>K D L Biotech Ltd.</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>T T K Healthcare Ltd.</td>
<td><a href="http://www.ttkhealthcare.com/"><span style="text-decoration: underline;">http://www.ttkhealthcare.com/</span></a></td>
</tr>
<tr>
<td>Neuland Laboratories Ltd.</td>
<td><a href="http://www.neulandlabs.com/"><span style="text-decoration: underline;">http://www.neulandlabs.com/</span></a></td>
</tr>
</tbody>
</table>
</li>
</ul>
</dd> <dt>
<p><strong>Q.6 <span style="text-decoration: underline;">How long does it take to ship the drugs to my home or office?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>Please allow up to two weeks for delivery.</p>
</li>
</ul>
</dd> <dt>
<p><strong>Q.7 <span style="text-decoration: underline;">How do I return something to AllDayChemist.com?</span></strong></p>
</dt> <dd> 
<ul class="list">
<li>
<p>We don't accept returns on prescription items, because it's illegal for us to reuse or resell them. If your prescription order was damaged in shipping or if the incorrect item was shipped, please e-mail us immediately at <a href="mailto:info@alldaychemist.com"><span style="text-decoration: underline;">Click for Mail</span></a> . Please include your order tracking number in your e-mail so that we may assist you more quickly.</p>
</li>
</ul>
</dd></div>
</dl></div>
	<br />
<!--<p><a href="" title=""><img src="icon/home.gif" alt="" class="icon" /></a><a href="" title=""></a></p>
-->
</div>

<script type="text/javascript">
	
var slider1=new accordion.slider("slider1");
slider1.init("slider");

</script>