<?php
/**
 * @category     Inchoo
 * @package     Inchoo Featured Products
 * @author        Domagoj Potkoc, Inchoo Team <web@inchoo.net>
 * @modified    Mladen Lotar <mladen.lotar@surgeworks.com>, Vedran Subotic <vedran.subotic@surgeworks.com>
 */
?>
<?php $image_size = (int) Mage::getStoreConfig("featuredproducts/cmspage/max_image_dimension") ?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <h3><?php echo $this->__($this->getBlockLabel()) ?></h3>
    <table border="0" cellspacing="0" class="home_product">

        <tbody>

            <?php
            $i = 0;
            $row = 0;
            foreach ($_products->getItems() as $_product):
                ?>

                    <?php if ($i == 0): ?>
                        <?php $row++; ?>
                    <tr class="<?php echo (($row % 2) > 0) ? 'odd' : 'even' ?>">
        <?php endif; ?>
                    <td style="width:152px !important;">

                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                            <img class="product-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($image_size, $image_size) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                        </a>
                        <div class="product-description">
                            <p class="fproduct_name">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>)">
                            <?php echo $this->htmlEscape($_product->getName()) ?>
                                </a>
                            </p>
							<!--coded by nilesh-->
							<?php
								$childProducts = Mage::getModel('catalog/product_type_configurable')->getUsedProducts(null, $_product);
								$child = $childProducts[0];
								$pack_size = $child->getResource()->getAttribute('pack_size')->getFrontend()->getValue($child);
								if($pack_size != "NA" && !empty($pack_size))
								{
									echo '<p class="custom_price">';
										echo '<span class="custom_child_1">'.$child->getResource()->getAttribute('pack_size')->getFrontend()->getValue($child).'</span>';
										echo '<span class="custom_child_2"> '.$_product->getResource()->getAttribute('pharmaceutical_form')->getFrontend()->getValue($_product).'</span>';
										echo '<span class="custom_child_3"> - US$ '.number_format($child->getPrice(), 2, '.', '').'</span>';
									echo "</p>";
								}
							?>
							<!--end--->
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>

                            <?php if (Mage::getStoreConfig('featuredproducts/general/price_visible')): ?>

                                <?php //Remove by programmer echo $this->getPriceHtml($_product, true, '-new')  ?>

                                <?php if ($_product->isSaleable()): ?>
                                    <button type="button" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <?php else: ?>
                                    <div class="out-of-stock"><?php echo $this->__('Out of stock') ?></div>
                                <?php endif; ?>

        <?php endif; ?>

                        </div>
                    </td>

                    <?php $i++;
                    if ($i == $this->getItemsPerRow()):
                        ?>
                    <?php $i = 0; ?>
                    </tr>
        <?php endif; ?>
    <?php endforeach; ?>

        </tbody>

    </table>
<?php endif; ?>