<!-- <div class="page-title">
	<h1>Referral System</h1>
</div> -->
<div class="referral-wrap">
	<div class="share-to-earn">
		<img src="<?php echo $this-> getSkinUrl('images/Infographic_Banner_01.jpg');?>">
	</div>
	<div class="content_wrap">
		<div class="how-it-works">
			<div class="outer_area">
				<div class="img_area">
					<img src="<?php //echo $this-> getSkinUrl('images/Infographic_Banner_01.jpg');?>">
				</div>
				<div class="desc_area"></div>
			</div>
		</div>
		<div class="this-doesnt-end-here">
			<div class="outer_area">
				<div class="img_area">
					<img src="<?php //echo $this-> getSkinUrl('images/Infographic_Banner_01.jpg');?>">
				</div>
				<div class="desc_area"></div>
			</div>
		</div>
	</div>
	<div class="whom-to-invite">
		<img src="<?php echo $this-> getSkinUrl('images/Infographic_Banner_02.jpg');?>">
	</div>
	<div class="rewards">
		<img src="<?php echo $this-> getSkinUrl('images/Infographic_Banner_03.jpg');?>">
	</div>
	<div class="invalide-invities">
		<p>If you don’t receive a notification about your referral bonus,
it’s probably because one or more of the below listed conditions were met:</p>
<p>•  The person didn’t use your referral code on signup.  
•  The person who clicked the link or used the code was already an All Day Chemist member.
•  The person did not complete his/her first purchase.
•  The referred person placed an eligible order, but the order got cancelled. 
•  Our fraud detection system rejected the candidate you referred.</p>
	<div class="refer-faq">Have more queries?  Refer to our Referral Rewards Program FAQ</div>
	</div>
	<div class="start-referring">
		<img src="<?php echo $this-> getSkinUrl('images/Infographic_Banner_01.jpg');?>">
		<button class="button" onclick="setLocation('<?php //echo $this->getUrl(''); ?>')">
			<span>
				<span>
					<?php echo $this->__('Start Referring');?>					
				</span>
			</span>
		</button>
	</div>		
<div class="social_btns">	
	<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('social/buttons.phtml')->toHtml(); ?>
</div>	
</div>