<?php $_product = $this->getProduct(); ?>
<?php //@nil for tabular packsize ?>
<?php


if($_product->isConfigurable()) {
	$_frontendHelper = $this->helper('frontend/data');
	/*To get the lowest unit price*/
	$getSimpleProductPrice = $_frontendHelper->allSimplePrice();
	//$productModel = Mage::getModel('catalog/product');

	$proModel = Mage::getModel('catalog/product');
	$cartHelper = Mage::helper('checkout/cart');
	$conProduct = $proModel->load($_product->getId());
	$customStockStatus = $conProduct->getCustomStockStatus();
	$attributeText = $proModel->getResource()->getAttribute('custom_stock_status');
    $attributeLabel = $attributeText->getSource()->getOptionText($customStockStatus);
    //Mage::log($attributeLabel,null,'coming_soon.log');
    //Mage::log($attributeText,null,'coming_soon_attributeText.log');
	$currencyFormat = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
	$childProducts = Mage::getModel('catalog/product_type_configurable')->getUsedProducts(null, $conProduct);
	$attr = $proModel->getResource()->getAttribute("pharmaceutical_form");
	$attrPackSize = $proModel->getResource()->getAttribute("pack_size");
	$url = $this->getUrl();
	foreach($childProducts as $child) {
			       $proChild = Mage::getModel('catalog/product')->load($child['entity_id']);
			       if($proChild->getData('status')==1) {
			           $newChildProducts[$attrPackSize->getSource()->getOptionText($child->getData('pack_size'))] = $proChild;
			       }
			   }

	ksort($newChildProducts);
	echo "<table class=\"new_product_list\" valign=\"center\">
			<tr>
				<th class=\"pack_size\"><strong>Pack Size</strong></th>
				<th class='qty'><strong>Qty</strong></th>
				<th class=\"price_per_pill\"><strong>Price Per Pill or Unit</strong></th>
				<th><strong>Price</strong></th>
				<th><strong>Discount</strong></th>
				<th><strong>Wishlist</strong></th>
				<th><strong>Cart</strong></th>
			</tr>";
	$i=0;
	$bestValue = $_product->getBestValue();
	//$bestValueListingOrder = Mage::getStoreConfig('custom_snippet/best_value/best_value_listing'); 
	$productCounter = 0;
	$backendSku = 0;
	// echo "<pre>";
	foreach($newChildProducts as $child) {
		//print_r();
		$childCategories = $child->getCategoryIds();
		if ($attr->usesSource()) {
			$pharmaceuticalForm = $attr->getSource()->getOptionText($conProduct->getData('pharmaceutical_form'));
		}
		if ($attrPackSize->usesSource()) {
			$packSizeLabel = $attrPackSize->getSource()->getOptionText($child->getData('pack_size'))." ".$pharmaceuticalForm."&nbsp;";
		}
		$packUnitsize = $attrPackSize->getSource()->getOptionText($child->getData('pack_size'));
		if($child->getData('bonus')) {
			//$packSizeLabel = $child->getData('bonus')." + ".$packSizeLabel." Extra";
			$bonusImage = $this->getSkinUrl().'images/double_pill.jpg';
			$packSizeLabel = '<span class="size_label">'.$packSizeLabel.'</span><img class="double_pill_img" src='.$bonusImage.'>';
			//$packUnitsize = $packUnitsize + $child->getData('bonus');
		}
		$childPrice = Mage::helper('core')->currency($child->getPrice(),true,false);
		$childSpecialPrice = Mage::helper('core')->currency($child->getSpecialPrice(),true,false);
		//$priceLabel = $currencyFormat."&nbsp;".number_format($child->getPrice(), 2, '.', '');
		if($child->getSpecialPrice()) {
			$priceLabel = '<span class="old-price">'.$childPrice.'</span>
					<span class="special-price">'.$childSpecialPrice.'</span>';
		}else{
			$priceLabel = '<span class="price">'.$childPrice.'</span>';
		}
		if($i==count($newChildProducts)) {
			echo "<tr class=\"last\">";
		} else {
			echo "<tr>";
		}
		if($child->getSpecialPrice()){
			$perUnit = $child->getSpecialPrice()/$packUnitsize;
		}else{
			$perUnit = $child->getPrice()/$packUnitsize;
		}
		$perUnitCost = Mage::helper('core')->currency($perUnit,true,false);
		/*New logic Recommended Starts*/
		$recommended = $recommendeclass = '';
		$lowestPrice = round($perUnit,2);
		$bestValueImage = Mage::getStoreConfig('custom_snippet/best_value_sku/sku_product');
		if($bestValueImage){
			$bestValueArr = explode(',', $bestValueImage);
			$bestValueArr=array_map('trim',$bestValueArr);
			$currSku = $child->getSku();

			if(in_array($currSku, $bestValueArr)){
				$backendSku = 1;
				$recommended = '<span class="recomend-text">( Recommended )</span>';
				$recommendeclass = 'packsize_recommended';
			}else{
				if($getSimpleProductPrice == $lowestPrice && $backendSku == 0 && $productCounter > 1){
				$recommended = '<span class="recomend-text">( Recommended )</span>';
				$recommendeclass = 'packsize_recommended';
			}
			}
		}

		//discount tag
		$discountTag = ' ';
		if($child->getSpecialPrice() != '' && $child->getData('discount_tag') != '' && ($child->isSaleable() || $child->getIsInStock()!=0)){
			$discountTag = '<span class="discount_tag">'.$child->getData('discount_tag').'</span>';
		}
		//discount tag

		/*New logic Recommended Ends*/
		// if(!empty($bestValue)){
		// 	if($productCounter==($bestValue-1)){
		// 		$recommended = '<span class="recomend-text">( Recommended )</span>';
		// 		$recommendeclass = 'packsize_recommended';
		// 	}
		// }else{
			// if($getSimpleProductPrice == $lowestPrice){
			// 	$recommended = '<span class="recomend-text">( Recommended )</span>';
			// 	$recommendeclass = 'packsize_recommended';
			// }
		//}
		$giftProds = Mage::getStoreConfig('ampromo/gift_product/gift_product_item');

		$giftSpan = '';
		if($giftProds){
			$giftProdsArr = explode(',', $giftProds);
			$giftProdsArr=array_map('trim',$giftProdsArr);
			
			$currSku = $child->getSku();
			if(in_array($currSku, $giftProdsArr)){
				$giftSpan = ' <span class="product_free_gift" title="Get a free gift">Will free gift</span>';
			}
		}
		echo "<td class='pack_size_value ".$recommendeclass."'>".$packSizeLabel.$recommended.$giftSpan."</td>";
		echo "<td class='qty_value'><span class='select_wrap'><select id='p-".$child->getId()."'>";
		for($i=1; $i<=5; $i++) {
			echo "<option value='$i'>$i</option>";
		}
		echo "</select></span></td>";
		echo "<td class='price_value'>".$perUnitCost."</td>";
		echo "<td class='price_value'>".$priceLabel."</td>";
		echo "<td class='discount_tag'>".$discountTag."</td>";
		echo '<td class="simple_wishlist"><a id="s-'.$child->getId().'" class="refill_reminder_open" 
		title="Add to Wishlist" href="'.$url.'wishlist/index/add/product/'.$child->getData('entity_id').'"></a></td>';
		if($attributeLabel == 'Coming Soon'){
			echo '<td class="pr-link-notify"><span class="coming_soon_btn">Coming Soon<span></td>';
		}else{
		echo '<td class="add_to_cart_button"><a id="s-'.$child->getId().'" class="related-buy-now" title="Add to cart" href="'.$url.'checkout/cart/add/product/'.$child->getId().'/?super_attribute[140]='.$child->getPackSize().'&mainid='.$conProduct->getId().'"> </a></td>';
		}
		//echo '<td class="simple_wishlist"><a class="refill_reminder_open" href="refillreminder?product_id='.$child->getId().'">Wishlist</a></td>';
		
		echo "</tr>";
		$productCounter++;
	}
	echo "</table>";
} else {
	echo $this->getChildHtml('', true, true);
}

?>
<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery(".related-buy-now").click(function(event){
			var id = this.id.split("-");
			var value = jQuery("#p-"+id[1]).val();
			event.preventDefault();
			window.location.href = jQuery(this).attr("href")+"&qty="+value;

		});
		var numItems = jQuery('.recomend-text').length;
		// jQuery(".refill_reminder_open").fancybox({
		// 	type: "iframe",
		// 	width: "300px",
		// 	height: "300px"
		// });
	});
</script>
<?php //@nil for tabular packsize end ?>
