<script language="javascript" type="text/javascript" src="//smarticon.geotrust.com/si.js"></script>
<div class="footer-payment-types">
	<span class="fpt1">&nbsp;</span>
	<span class="fpt2">&nbsp;</span>
	<span class="fpt3">&nbsp;</span>
	<span class="fpt4 last">&nbsp;</span>
</div>
<div class="footer-container">
    <div class="footer">
        <?php echo $this->getChildHtml() ?>
        <!-- <p class="bugs"><?php //echo $this->__('Help Us to Keep Magento Healthy') ?> - <a href="http://www.magentocommerce.com/bug-tracking" onclick="this.target='_blank'"><strong><?php //echo $this->__('Report All Bugs') ?></strong></a> <?php //echo $this->__('(ver. %s)', Mage::getVersion()) ?></p> -->
        <div class="mobile_footer">
            <div class="checkout-footer">
                <span class="ldetails-t">Toll Free Tel +1(855) 840-0584</span>
                <!-- <span class="ldetails-b">International Tel +1 (213) 814 1313 </span> -->
            </div>
                
            <div class="checkout-footer">
                <span class="rdetails-t">Customer Support Email ID:</span>
               <span class="rdetails-b"><a href="mailto:david@alldaychemist.com">david@alldaychemist.com</a></span>
            </div>
        </div>
        <!-- <address><?php //echo $this->getCopyright() ?></address> -->
        <address><?php echo "© ".date("Y")." AllDayChemist. All Rights Reserved." ?></address>
    </div>
</div>
