<?php
$OrderId = $this->getOrderId();
$orderModel = Mage::getModel('sales/order')->loadByIncrementId($OrderId);
$customerFirstname = $orderModel->getCustomerFirstname();
$customerLastname = $orderModel->getCustomerLastname();
$name = $customerFirstname.' '.$customerLastname;
?>
<div class="pr-row1">
            <div class="success-img">
                <img src="<?php echo $this->getSkinUrl('images/pr-success-icon.png') ?>" alt="" />
            </div>
            <div class="success-text">
                <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
                <h2 class="sub-title"><?php echo $this->__('Congratulations ').''.$name; ?></h2>
                <h2><?php echo $this->__('Your Order has been placed') ?></h2>
                <span>Thanks for Shopping with <span class="grn">AllDayChemist</span></span>
                <?php if ($this->getCutomOrderId()):?>
                <?php if ($this->getCanViewOrder()) :?>
                    <p class="order-id"><?php echo $this->__('Your order Id is: %s', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getCutomOrderId()))) ?></p>
                <?php  else :?>
                    <p class="order-id"><?php echo $this->__('Your Order Id is: %s', $this->escapeHtml($this->getCutomOrderId())) ?></p>
                <?php endif;?>
                    <p><?php echo $this->__('You will receive a confirmation email shortly') ?></p>
                <?php //if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
                    <!-- <p>
                        <?php //echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $this->getPrintUrl()) ?>

                    </p> -->
                <?php //endif;?>

                <?php endif;?>
            </div>
</div>

        <div class="pr-row2"><?php echo $this->getChildHtml('checkout.onepage.heared4us') ?></div>

        <?php if ($this->getAgreementRefId()): ?>
            <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
        <?php endif;?>

        <?php if ($profiles = $this->getRecurringProfiles()):?>
        <p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
        <ul class="disc">
        <?php foreach($profiles as $profile):?>
        <?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
            <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
        <?php endforeach;?>
        </ul>
        <?php endif;?>