<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>All Day Chemist</title>
</head>

<style type="text/css">
	body{
		margin: 0;
		padding: 0;
		font-family:'Trebuchet MS', Arial, Helvetica, sans-serif;
		letter-spacing:2px;
	}
	.main{
		max-width: 1000px;
		margin: 0 auto;
	}
	.content{
		width: 100%;
		float: left;
		border-top: 1px solid #ccc;
		padding: 50px 0 0;
		text-align:center
	}
	.content h1{
		color:#8ba01f;
	}

	@media(max-width:720px){
		.content h1{
			font-size:25px;
		}
	}
	
</style>
<body style="text-align:center">
<div class="main">
	<div class="logo">
	<img src="images/logo.jpg" style="max-width:100%;" />
	</div>
	<div class="content">
		<h1>Thank You</h1>
	</div>
</div>
</body>
</html>
