<div id="co-billing-form">
    <h3><?php echo $this->__('Billing Address')?></h3>
    <ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
        <li class="wide">
            <label for="billing-address-select" class="notice logged-in-notice"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
            <div class="input-box billing-address-loggedin">
                <?php echo $this->getAddressesHtmlSelect('billing') ?>
            </div>
        </li>
    <?php endif; ?>
    <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
        <fieldset>
            <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
            <ul>
            <div class="billing_part1">
                <li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?></li>
                <div class="clear"></div>
                <?php if(!$this->isCustomerLoggedIn()): ?>
                <li class="fields">
                    <div class="field">
                        <label for="billing:email" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                        </div>
                    </div>
                 </li>
                <?php endif; ?>
                <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                 <?php if ($_dob->isEnabled()): ?>
                    <li class="fields">
                        <div class="field">
                            <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                        </div>
                    </li>
                <?php endif; ?>
                 <li class="fields">
                    <div class="field">
                        <label for="billing:telephone" class="required"><?php echo $this->__('Mobile no.') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="text" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('telephone') ?>" id="billing:telephone" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="billing:company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('company') ?>" />
                        </div>
                    </div>   
                </li>   
                <div class="clear"></div>
        <?php $_streetValidationClass = $this->helper('opc')->getAttributeValidationClass('street'); ?>
                <li class="wide">
                    <label for="billing:street1" class="required"><?php echo $this->__('Address') ?><em>*</em></label>
                    <div class="input-box">
                        <!-- <input type="text" title="<?php //echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php //echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php //echo $_streetValidationClass ?>" /> -->
                        <textarea title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" class="input-text <?php echo $_streetValidationClass ?>"> <?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?></textarea>
                    </div>
                </li>
        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
        <?php endfor; ?>
                <?php if ($this->helper('opc')->isVatAttributeVisible()) : ?>
                <li class="wide">
                    <label for="billing:vat_id"><?php echo $this->__('VAT Number') ?></label>
                    <div class="input-box">
                        <input type="text" id="billing:vat_id" name="billing[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('vat_id') ?>" />
                    </div>
                </li>
                <?php endif; ?>
                </div>
                <div class="billing_part2">
                  <li class="fields">
                    <div class="field">
                        <label for="billing:postcode" class="required"><?php echo $this->__('Zip') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('opc')->getAttributeValidationClass('postcode') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="billing:country_id" class="required"><?php echo $this->__('Country') ?><em>*</em></label>
                        <div class="input-box">
                        <?php $loginAsCustomer = Mage::getModel('core/cookie')->get('login_admin');
                            if($loginAsCustomer){
                                $countryCollection = Mage::helper('overrides')->getAllCountryCollection();?>
                           <?php $_countries = Mage::getResourceModel('directory/country_collection')
                                    ->loadData()
                                    ->toOptionArray(false) ?>
                            <?php if (count($_countries) > 0): ?>
                                <select name="billing[country_id]" id="billing:country_id" class="validate-select" title="Country">
                                    <option value="">-- Please Select --</option>
                                    <?php foreach($_countries as $_country): ?>
                                        <option value="<?php echo $_country['value'] ?>">
                                            <?php echo $_country['label'] ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            <?php endif; ?>
                        <?php }else{
                                echo $this->getCountryHtmlSelect('billing');
                            } ?>
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="billing:city" class="required"><?php echo $this->__('City') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('city') ?>" id="billing:city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="billing:region_id" class="required"><?php echo $this->__('State') ?><em>*</em></label>
                        <div class="input-box">
                            <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                            //]]>
                            </script>
                            <?php $loginAsCustomer = Mage::getModel('core/cookie')->get('login_admin');
                            if($loginAsCustomer){?>
                            <input type="text" id="billing:region" name="billing[region]" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('region') ?>" style="display:none;" />
                            <?php }else{?>
                            <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('region') ?>" style="display:none;" />
                            <?php } ?>
                        </div>
                    </div>
                </li>
              
                <li class="fields">                 
                    <div class="field">
                        <label for="billing:fax"><?php echo $this->__('Fax') ?></label>
                        <div class="input-box">
                            <input type="text" name="billing[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('fax') ?>" id="billing:fax" />
                        </div>
                    </div>
                </li>
                <?php if(!$this->isCustomerLoggedIn()): ?>

                    <?php //$_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                    <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>

                    <?php if ($_gender->isEnabled()): ?>
                       <li class="fields">        
                        <div class="field">
                            <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                        </div>
                    </li>
                    <?php endif ?>
                <div class="clear"></div>

                    <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                    <?php if ($_taxvat->isEnabled()): ?>
                            <li>
                                <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                            </li>
                    <?php endif ?>

                    
                <?php endif; ?>
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                    <div class="clear"></div>
                    <li class="control">
                        <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="billing:save_in_address_book" class="save-add-book"><?php echo $this->__('Save in address book') ?></label>
                    </li>
                <?php else:?>
                    <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
                <?php endif; ?>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
                </div>
            </ul>
        </fieldset>
    </li>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('checkout.onepage.billing.extra')?>
    <?php if(!$this->isCustomerLoggedIn()): ?>
    
        <?php
        $guest_allowed = $this->getQuote()->isAllowedGuestCheckout();
        if($guest_allowed): ?>
        <li class="control">
                <input type="checkbox" name="billing[create_account]" id="billing:create_account" value="1" title="<?php echo  $this->__('Create an account for later use') ?>"  class="checkbox" /><label for="billing:create_account" class="create-acc-for-later"><?php echo  $this->__('Create an account for later use') ?></label>
        </li>
        <?php else:?>
            <input type="hidden" name="billing[create_account]" id="billing:create_account" value="1" />
        <?php endif;?>
        
        <li class="fields <?php if($guest_allowed):?>hidden<?php endif;?>" id="register-customer-password">
            <div class="field">
                <label for="billing:customer_password" class="required"><?php echo $this->__('Password') ?><em>*</em></label>
                <div class="input-box">
                    <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text validate-password <?php if(!$guest_allowed):?>required-entry<?php endif;?>" autocomplete="off"/>
                </div>
            </div>
            <div class="field">
                <label for="billing:confirm_password" class="required"><?php echo $this->__('Confirm Password') ?><em>*</em></label>
                <div class="input-box">
                    <input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text validate-cpassword <?php if(!$guest_allowed):?>required-entry<?php endif;?>" autocomplete="off"/>
                </div>
            </div>
        </li>
        <div class="clear"></div>
    
    <?php endif;?>
    
    <?php if ($this->canShip()): ?>
        <li class="control <?php if (!Mage::helper('opc')->isShowShippingForm()):?>hidden<?php endif;?>">
            <input type="checkbox" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1"<?php if ($this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo  $this->__('Ship to this address') ?>" class="checkbox   " /><label for="billing:use_for_shipping_yes" class="ship-to-this-address"><?php echo  $this->__('Ship to this address') ?></label>
        </li>
    <?php endif; ?>

    <!--Start of preferable_time_to_call -->
        <li class="fields">
            <div class="time_to_call">
                <label for="billing:timetocall">
                <?php echo $this->__('Preferable Time to Call') ?><em>*</em></label>
                <div class="input-box" >
                    <?php 
                        $customer_data=Mage::getSingleton('customer/session')->getCustomer();
                        $timetocallArray = explode(' - ',$this->escapeHtml($customer_data->getData('timetocall')));
                    ?>
                    <div class="time-from">
                        <select class="required-entry validate-select" id="timeval1">
                            <?php $timecounter = 1;
                                echo   '<option value=""></option>';
                                for($time=1; $time <=24 ; $time++) { 
                                    // $timelap ='AM'
                                    if($timecounter <=12) {
                                        $newtime =$time;
                                        $timelap ='AM';
                                    }
                                    else {
                                        $newtime =$time-12;
                                        $timelap ='PM';
                                    }
                                    
                                    $selectedval='';
                                    $timeoptionval = $newtime.' '.$timelap;
                                    
                                    if($timetocallArray[0]==$timeoptionval) {
                                        $selectedval ='selected=selected';
                                    }
                                    else {
                                        $selectedval='';
                                    }

                                    echo '<option value="'.$timeoptionval.'" '.$selectedval.'>'.$timeoptionval.'</option>';
                                    $timecounter++;
                                }
                            ?>
                        </select>
                    </div>
                    
                    <span class="from_to"><?php echo $this->__('To') ?></span>
                    
                    <div class="time-to">
                        <select class="required-entry validate-select" id="timeval2">
                            <?php $timecounter = 1;
                                echo   '<option value=""></option>';
                                for($time=1; $time <=24 ; $time++) { 
                                    // $timelap ='AM'
                                    if($timecounter <=12){
                                        $newtime =$time;
                                        $timelap ='AM';
                                    }
                                    else{
                                        $newtime =$time-12;
                                        $timelap ='PM';
                                    }

                                    $timeoptionval = $newtime.' '.$timelap;
                                    $selectedval='';
                                    
                                    if(isset($timetocallArray[1])==$timeoptionval) {
                                        $selectedval ='selected=selected';
                                    }
                                    else {
                                        $selectedval='';
                                    }

                                    echo '<option value="'.$timeoptionval.'" '.$selectedval.'>'.$timeoptionval.'</option>';
                                    $timecounter++;
                                }
                            ?>
                        </select> 
                    </div>
                    <div class="time-zone">
                        <select class="required-entry validate-select" id="timezone">
                            <option value=""></option>
                            <option value="CST" <?php if(isset($timetocallArray[2])=='(CST)'){echo $selectedval ='selected=selected';} ?>>CST</option>
                            <option value="EST" <?php if(isset($timetocallArray[2])=='(EST)'){echo $selectedval ='selected=selected';} ?>>EST</option>
                            <option value="MST" <?php if(isset($timetocallArray[2])=='(MST)'){echo $selectedval ='selected=selected';} ?>>MST</option>
                            <option value="PST" <?php if(isset($timetocallArray[2])=='(PST)'){echo $selectedval ='selected=selected';} ?>>PST</option>
                            <option value="GMT" <?php if(isset($timetocallArray[2])=='(GMT)'){echo $selectedval ='selected=selected';} ?>>GMT</option>
                            <option value="AEST" <?php if(isset($timetocallArray[2])=='(AEST)'){echo $selectedval ='selected=selected';} ?>>AEST</option>
                            <option value="ACST" <?php if(isset($timetocallArray[2])=='(ACST)'){echo $selectedval ='selected=selected';} ?>>ACST</option>
                            <option value="ASWT" <?php if(isset($timetocallArray[2])=='(ASWT)'){echo $selectedval ='selected=selected';} ?>>ASWT</option>
                            <option value="AEDT" <?php if(isset($timetocallArray[2])=='(AEDT)'){echo $selectedval ='selected=selected';} ?>>AEDT</option>
                        </select> 
                    </div>
                    <input type="hidden" id="billing_timetocall" name="billing[timetocall]" value="<?php echo $this->escapeHtml($customer_data->getData('timetocall')) ?>" title="<?php echo $this->__('Preferable Time to Call') ?>" class="input-text" id="timetocall" />
                </div>             
            </div>       
        </li>
    <!--End of preferable_time_to_call -->

    </ul>
    <?php if (!$this->canShip()): ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1" />
    <?php endif; ?>

</div>
<script type="text/javascript">
//<![CDATA[
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
//]]>
</script>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery("#timezone,#timeval1,#timeval2").change(function(){
           var timeval1 = jQuery("#timeval1").val();
           var timeval2 = jQuery("#timeval2").val();
           var timezone = jQuery("#timezone").val();
           if(timeval1 == ''){
            ("#timeval1").focus();
           }
           else if(timeval2 == ''){
            ("#timeval2").focus();
           }
           else if(timezone == '')
           {
            ("#timezone").focus();
           }
           else {
            var timetocall = timeval1+' - '+timeval2+' - ('+timezone+')';
            jQuery("#billing_timetocall").val(timetocall);
        } 
        })
    })

</script>
