<div id="complete_address">
	
</div>
<button class="btn btn-primary" id="confirm_address_edit"><span><span>Edit</span></span></button>
<br><br>
<span id='check_error_message'></span>
<script type="text/javascript">
jQuery(document).ready(function($){
	$('#confirm_address_step').hide();
	$('#confirm_address_check').hide();
	$('#check_error_message').hide();
	$('#medical_nextbtn').click(function(e){
		IWD.OPC.Checkout.showLoader();
		IWD.OPC.Checkout.lockPlaceOrder();
		$.ajax({
		        url: "<?php echo $this->getUrl("onepage/json/getcustomAddresstep")?>",
		        type: "get",
		        success: function (response) {
		        	IWD.OPC.Checkout.hideLoader();
					IWD.OPC.Checkout.unlockPlaceOrder();
		        	$('#complete_address').html(response);
		        	$('#confirm_address_step').show();
		        	$('#confirm_address_check').show();
		        }
		    });
	})
	$('#confirm_address_step').click(function(e) {

		var valueText = $( "#dropdown option:selected" ).text();
		var valueId = 	$( "#dropdown option:selected" ).val();

		if(valueText == "Others"){
		var message = $("#others_textbox").val();
			if(message == ""){
				e.stopPropagation();
	    		$('#check_textbox').text('Cannot be empty').show();
	    		return;
			}else{
				$('#check_textbox').hide();
				$.ajax({
				    url: "<?php echo $this->getUrl('overrides/account/hearfromus') ?>",
				    type: "POST",
				    data: {attribute: valueId,message:message},
				    success: function(data){
				    	/*IWD.OPC.Checkout.hideLoader();
				    	IWD.OPC.Checkout.unlockPlaceOrder();*/
					}
				});
			}
		}
		$('#check_error_message').hide();
	    if(!$("#confirm_address_check").is(':checked')){
	    	e.stopPropagation();
	    	$('#check_error_message').text('Please Confirm').show();
	    	return;
		}
	});
	$('#confirm_address_edit').click(function(e) {
    	$('#tab-1').hide();
		$('#tab-3').hide();
		$('#tab-4').hide();
		$('#tab-2').show();
		$('.checkoutstep-2').removeClass('pass');
		$('.checkoutstep-2').addClass('current');
		$('.checkoutstep-3').removeClass('pass');
		$('.checkoutstep-4').removeClass('current');
	});
	
})
	
</script>

<!--textbox area-->
<div id="textbox_values">
<textarea id="others_textbox" rows="4" cols="50">
</textarea>
<span id='check_textbox'></span>
</div>

<?php
$customer = Mage::getSingleton('customer/session')->getCustomer();
$customerId = Mage::getSingleton('customer/session')->getId();
$customerModel  = Mage::getModel('customer/customer')->load($customerId);
$AtributeValue=Mage::getResourceModel('customer/customer')
        ->getAttribute('find_us')
        ->getSource()
        ->getAllOptions();
 
 // print_r($AtributeValue);
$labelValues = $customerModel->getResource()->getAttribute('find_us')->getStoreLabel();
?>
<label><?php echo $labelValues; ?></label>

<select class="myselect" id="dropdown">
        <?php
        foreach($AtributeValue as $each){
        ?>
        <option value="<?php echo $each['value']?>"><?php echo $each["label"]?></option>
        <?php
        }
        ?>
</select>
<br><br>

<label for="confirm_address_check">
	<input type="checkbox" name="confirm_address_check" id="confirm_address_check" value="1">I confirm that the address given above is correct
</label>

<script type="text/javascript">
jQuery(document).ready(function($){
	$("#textbox_values").hide();
	$('#dropdown').change(function(){
		var valueText = $("#dropdown option:selected").text();
		var valueId = $("#dropdown option:selected").val();

		if(valueText == "Others"){
            $("#textbox_values").show();
        }else{
        	$("#textbox_values").hide();
			$.ajax({
			    url: "<?php echo $this->getUrl('overrides/account/hearfromus') ?>",
			    type: "POST",
			    data: {attribute: valueId},
			    success: function(data){
				   // echo "hello"
				}
			});		
        }
	});
});


</script>

