<script type="text/javascript">
//<![CDATA[
    var quoteBaseGrandTotal = <?php echo (float)$this->getQuoteBaseGrandTotal(); ?>;
    var checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
    var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment', array('_secure' => $this->getRequest()->isSecure())) ?>');
    var lastPrice;
//]]>
</script>
<div class="trust_banner">
    <span class="banner-1">
        <?php $payment_banner1 = Mage::getStoreConfig('payment/allpayment/payment_banner_1');?>
        <a href="https://www.mcafeesecure.com/RatingVerify?ref=www.alldaychemist.com" id="mcaffee_logo" onclick="window.open(this.href, 'mcafee_new','width=1000,height=500,toolbar=1,resizable=0'); return false;" rel="nofollow">
        <span class="op1"></span>
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'paymentbanner/'. $payment_banner1; ?>"/>  
        </a>
    </span>
    <span class="banner-2">
        <?php $payment_banner2 = Mage::getStoreConfig('payment/allpayment/payment_banner_2');?>
        <a class="footer_logos" href="https://seal.godaddy.com/verifySeal?sealID=516304681046fb4bc11011f1400b8da37d719429464659303720420694" id="godaddy_logo" onclick="window.open(this.href, 'godaddy_new','width=700,height=500,toolbar=1,resizable=0'); return false;" rel="nofollow" style="cursor: pointer;"> <span class="op2"></span>
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'paymentbanner/'. $payment_banner2; ?>"/>
        </a>  
    </span>
    <span class="banner-3">
        <?php $payment_banner3 = Mage::getStoreConfig('payment/allpayment/payment_banner_3');?>
        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'paymentbanner/'. $payment_banner3; ?>"/>
    </span>
    <span class="banner-3_message" style="display: none;">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('payment_banner_message')->toHtml(); ?>
    </span>
</div>
<form action="" id="co-payment-form">	
    <fieldset id="checkout-payment-method-load">
        <?php echo $this->getChildHtml('methods') ?>
    </fieldset>
</form>
<div class="tool-tip" id="payment-tool-tip" style="display:none;">
    <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
    <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
</div>
<script type="text/javascript">
//<![CDATA[
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)-560)+'px'//,
                //left: (Event.pointerX(event)+100)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
    payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
//]]>

</script>
