<!-- <div class="page-title">
        <h1> FAQs/HELP</h1>
    </div> -->
<?php
$storeid = Mage::app()->getStore()->getStoreId(); 
$faqsection = Mage::getModel('faqsection/faqsection')->getCollection()->addFieldToFilter('store_id',$storeid)->getData();
$questionModel = Mage::getModel('faqsection/faqquestions')->getCollection()->addFieldToFilter('store_id',$storeid)->addOrder('sections_id','asc');
$html ='';
foreach ($faqsection as $key => $value) {
	$i = 1;
	$html.= '<div class="faqaccordion vertical">';	
	$html.= '<h1 class="type_title" id="section_'.$value['sections_typeid'].'">'.$value['type_title'].'</h1>';
		foreach ($questionModel->getData() as $key => $questionlist) {
			if($value['sections_typeid']==$questionlist['sections_id']):
				// print_r($value);
				if($value['sections_typeid']==2){
					$stepi = 'Step '.$i;
				}else{
					$stepi ='Q '.$i;
				}
				$html.= '<section id="'.$questionlist['question_id'].'">
					<h2 class="question_tag" id="answer_'.$questionlist['question_id'].'">'.$stepi.'. <a class="question">'.$questionlist['question'].'</a></h2>';
				$html.= '<div class="answers answer_'.$questionlist['question_id'].'">'.$questionlist['answer'].'</div>';
				$html.= '</section>';
				$i = $i+1;
			endif;
		}
		$html.= '</div>';
}
echo $html;

?>
<style type="text/css">

</style>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('.question_tag').click(function(){
		// alert(this.id);
		if(!jQuery('.'+this.id).hasClass('current')){
			jQuery('.answers').slideUp('1000');
			jQuery('.'+this.id).animate().slideDown('1000');
			jQuery('.'+this.id).addClass('current');
		}else{
			jQuery('.'+this.id).removeClass('current');
			jQuery('.answers').removeClass('current');
			jQuery('.answers').slideUp('1000');
			jQuery('.'+this.id).animate().slideDown('3000');
		}
	
	});
});
</script>
<style type="text/css">
.type_title{margin:10px 0px 15px 0px;color: #9eb501;font-weight: bold;}
.question_tag{background-color: #eee;border:2px solid #eee;padding: 5px;width: 100%;cursor:pointer;}
.answers{padding-bottom: 10px;margin-top: 20px;display: none;}
.faqaccordion ul{padding:10px 0px 10px 0px;list-style-type: disc;margin-left: 25px;}
.faqaccordion ul li{padding:5px 0px 5px 0px;}
.faqaccordion a.question:hover{color: #444;}
.answers{color: #000;}
</style>