<?php
	$right_banner_1 = Mage::getStoreConfig('homepage_conf/common_group/sidebar_image_1');
		$right_banner_1_url = Mage::getStoreConfig('homepage_conf/common_group/sidebar_image_1_url');
	$right_banner_2 = Mage::getStoreConfig('homepage_conf/common_group/sidebar_image_2');
		$right_banner_2_url = Mage::getStoreConfig('homepage_conf/common_group/sidebar_image_2_url');
	 $right_banner_3 = Mage::getStoreConfig('homepage_conf/common_group/sidebar_image_3');
	 	$right_banner_3_url = Mage::getStoreConfig('homepage_conf/common_group/sidebar_image_3_url');
	$right_banner_4 = Mage::getStoreConfig('homepage_conf/common_group/sidebar_image_4');
		$right_banner_4_url = Mage::getStoreConfig('homepage_conf/common_group/sidebar_image_4_url');
	$image_above_trusted = Mage::getStoreConfig('homepage_conf/common_group/image_above_trusted');
		$image_above_trusted_url = Mage::getStoreConfig('homepage_conf/common_group/image_above_trusted_url');
?>
<div class="below_banner_main_area">
	<div class="below_banner_area">
		<div class="iframe_wrap">
			<iframe scrolling="no" width="100%" height="0" frameborder="0" src="<?php echo $this->getUrl('frontend/index/allbrands', array(
			            '_secure' => Mage::app()->getFrontController()->getRequest()->isSecure()
			        ));?>"></iframe>
		</div>

		<div class="new_year_countdown">
			<div class="container">
            <div class="countdown_text">
            	<div class="countdown_left">
            	<span class="txt1">new year</span><span class="txt2">countdown </span></div>	
	            <div class="countdown_right">
	                <div class="cube-wrap example1">
	                    <div class="cube_left" style="float:left;">201</div>
	                    <div class="cube_right">
	                        <div class="cubBrd">7</div>
	                        <div class="cubT">8</div>
	                    </div>
	                </div>
	            </div>
            </div>
	            <div class='countdown' data-date="2018-01-01"></div>
	        </div>
		</div>
		<?php if($image_above_trusted):?>
		<div class="home-banner-block">
			<a class="comboclass" href="<?php echo $image_above_trusted;?>">
				<!-- <img src="<?php //echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'sidebanner/'. $image_above_trusted; ?>"/> -->

				<img class="lazy" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'sidebanner/'. $image_above_trusted; ?>"
					src="<?php echo $this->getSkinUrl('images/loading_1.gif') ?>"/>
			</a>			
		</div>
		<?php endif;?>
       <!--  <div class="trustedcompany-widget">
			<div id="TRUSTEDCOMPANY_widget_86428">
				<script async src="https://d3643s33l1rfut.cloudfront.net/js/widget?w=BQYHDBEcXh4BFAMkFgoRGR0LEhgAFkIHHQJYU0JcV08"
				></script>
			</div>
		</div> -->
		<div class="trustpilot-widget" data-locale="en-US" data-template-id="53aa8807dec7e10d38f59f32" data-businessunit-id="4c180e9d00006400050d44c2" data-style-height="150px" data-style-width="100%" data-theme="dark" style="background: #000000; padding-top: 20px;">
			<a href="https://www.trustpilot.com/review/alldaychemist.com" target="_blank">Trustpilot</a>
		</div>
		<?php if($right_banner_1):?>
		<div class="home-banner-block">
			<a class="comboclass" href="<?php echo $right_banner_1_url;?>">
				<!-- <img src="<?php //echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'sidebanner/'. $right_banner_1; ?>"/> -->

				<img class="lazy" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'sidebanner/'. $right_banner_1; ?>" src="<?php echo $this->getSkinUrl('images/loading_1.gif') ?>"/>
			</a>			
		</div>
		<?php endif;?>
		<?php if($right_banner_2):?>
		<div class="home-banner-block mid">
			<a class="comboclass" href="<?php echo $right_banner_2_url;?>">
				<!-- <img src="<?php //echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'sidebanner/'. $right_banner_2; ?>"/> -->

				<img class="lazy" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'sidebanner/'. $right_banner_2; ?>" src="<?php echo $this->getSkinUrl('images/loading_1.gif') ?>"/>
			</a>
		</div>		
		<?php endif;?>
		<?php if($right_banner_3):?>
		<div class="home-banner-block third">
			<a class="comboclass" href="<?php echo $right_banner_3_url;?>">
				<!-- <img src="<?php //echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'sidebanner/'. $right_banner_3; ?>"/> -->

				<img class="lazy" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'sidebanner/'. $right_banner_3; ?>" src="<?php echo $this->getSkinUrl('images/loading_1.gif') ?>"/>
			</a>			
		</div>
		<?php endif;?>
		<?php if($right_banner_4):?>
		<div class="home-banner-block forth">
			<a class="comboclass" href="<?php echo $right_banner_4_url;?>">
				<!-- <img src="<?php //echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'sidebanner/'. $right_banner_4; ?>"/> -->

				<img class="lazy" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'sidebanner/'. $right_banner_4; ?>" src="<?php echo $this->getSkinUrl('images/loading_1.gif') ?>"/>
			</a>			
		</div>
		<?php endif;?> 		
	</div>
</div>



<script type="text/javascript">
jQuery(document).ready(function(){
	//alert(34);
	jQuery("img.lazy").lazy();
});


</script>


<style type="text/css">
.cube-wrap {
    transform: scale(0.8);
    -ms-transform: scale(0.8);
    -webkit-transform: scale(0.8); 
    -moz-transform: scale(0.8); 
    -o-transform: scale(0.8); 
}
.cube_right{
	float: left;
    position: absolute;
    left: 55px;
    top: -17px;
}
.cubT, .cubBrd{
	display: block;
	width: 100%;
    font-size: 25px;
    color: #c4e304;
}
.cubBrd{
	border-bottom: 2px solid #fff;
	color: #7a9801;
}
.newCub{
	top: 0;
    left: 51px;
}
.newCub .cubBrd{
	display: none;
}
.newCub .cubT{
	font-size: 30px;
}

.example1 .cube-right {
    transform: rotateY(90deg) translateZ(0);
    -moz-transform: rotateY(90deg) translateZ(0);
    -webkit-transform: rotateY(90deg) translateZ(0);
    -o-transform: rotateY(90deg) translateZ(0);
    -ms-transform: rotateY(90deg) translateZ(0);
    background-color: blue;
    right: 0;
}

</style>