<div class="below_banner_main_area">
	<div class="below_banner_area">
		<iframe scrolling="no" width="100%" height="0" frameborder="0" src="<?php echo $this->getUrl('frontend/index/allbrands', array(
            '_secure' => Mage::app()->getFrontController()->getRequest()->isSecure()
        ));?>"></iframe> 
		 <div class="home-banner-block">
			<a class="comboclass" href="<?php //echo $this->getBaseUrl().'referral';?>">
				<!-- <img src="<?php //echo $this->getSkinUrl('images/banner-block-1.jpg');?>" alt=""/> -->
				<img src="<?php echo $this->getSkinUrl('images/adcshipping-block-1.jpg');?>" alt=""/>
			</a>
			
		</div>
		<div class="home-banner-block mid">
			<a class="comboclass" href="<?php echo $this->getBaseUrl().'content/114-echeck/';?>">
				<img src="<?php echo $this->getSkinUrl('images/echeck-banner_update.jpg');?>" alt=""/>
			</a>
		</div>
		
		<div class="home-banner-block third">
			<a class="comboclass" href="<?php echo $this->getBaseUrl().'content/88-order-online/';?>">
				<img src="<?php echo $this->getSkinUrl('images/banner-block-3.jpg');?>" alt=""/>
			</a>
			
		</div> 
		<div class="home-banner-block last">
			<a class="comboclass" href="<?php echo $this->getBaseUrl().'';?>">
				<img src="<?php echo $this->getSkinUrl('images/banner-block-4.jpg');?>" alt=""/>
			</a>			
		</div>
		<div class="trustedcompany-widget">
			<div id="TRUSTEDCOMPANY_widget_86428"><script async
			src="https://d3643s33l1rfut.cloudfront.net/js/widget?w=BQYHDBEcXh4BFAMkFgoRGR0LEhgAFkIHHQJYU0JcV08"
			></script></div>
		</div>
	</div>
</div>
