<?php	
	$popularCategories = Mage::helper('configurehomepage')->popularCategoryData();
	$bestSellingProducts = Mage::helper('configurehomepage')->getBestSellingData();
	$bestSellingTitle = Mage::getStoreConfig('homepage_conf/guest_group/best_selling');
	$onlinePharmacyTitle = Mage::getStoreConfig('homepage_conf/guest_group/online_pharmacy');
	$popularCategoryTitle = Mage::getStoreConfig('homepage_conf/guest_group/popular_category_label');
	$banner_1 = Mage::getStoreConfig('homepage_conf/guest_group/leading_image_1');
	$banner_2 = Mage::getStoreConfig('homepage_conf/guest_group/leading_image_2');
	$banner_3 = Mage::getStoreConfig('homepage_conf/guest_group/leading_image_3');
	$banner_1_url = Mage::getStoreConfig('homepage_conf/guest_group/leading_image_1_url');
	$banner_2_url = Mage::getStoreConfig('homepage_conf/guest_group/leading_image_2_url');
	$banner_3_url = Mage::getStoreConfig('homepage_conf/guest_group/leading_image_3_url');
	$categoryDefaultImg = Mage::getStoreConfig('homepage_conf/guest_group/popular_category_default_placeholder');
	//var_dump($categoryDefaultImg);die;
?>
<div class="main_config_page">
<!-- Best Seller S-->
	<div class="best_seller">
		<div class="best_seller_title">
			<span><?php echo strtoupper($bestSellingTitle);?></span>
		</div>
		<div class="best_seller_data">
			<ul class="single-item">
				<?php
					$i = 0;
					foreach($bestSellingProducts as $bestProducts){
						$i++;
						$productName = $bestProducts->getName();
						$productGenericName = $bestProducts->getGenericName();
						$productUsBrandName = $bestProducts->getUsBrandName();
						$productUrl = $bestProducts->getProductUrl();
						$productImage = $this->helper('catalog/image')->init($bestProducts, 'image')->resize(150,200);
						if($i%2 != 0):?>
						<li>
							 <!-- freegifttext start -->
                            <?php
                            $giftProds = Mage::getStoreConfig('ampromo/gift_product/gift_product_item');
                            $giftSpan = '';
                            if($giftProds){
                             $giftProdsArr = explode(',', $giftProds);
                             $giftProdsArr=array_map('trim',$giftProdsArr);

                             if(in_array($bestProducts->getSku(), $giftProdsArr)){
                               echo $giftSpan = '<span class="" title="Get a free gift"> Free Gift</span>';
                           }
                       }
                       
                       ?>
                       <!-- freegifttext end -->
							
							<a href="<?php echo $productUrl;?>">
								<!-- discount tag-->
			                    <?php if ($bestProducts->getSpecialPrice() != '' && $bestProducts->getDiscountTag() != '' && ($bestProducts->isSaleable() || $bestProducts->getIsInStock()!=0)) :?>
			                    <span class="discount_tag"><?php echo $bestProducts->getDiscountTag() ?></span>
			                    <?php endif; ?>
			                    <!-- discount tag-->
								<img class="lazy" data-src="<?php echo $productImage; ?>" src="<?php echo $this->getSkinUrl('images/loading_1.gif') ?>" alt="<?php echo $productName;?>" />
								<span><?php echo $productName;?></span>
								<span><?php if($productUsBrandName): echo '<br>US BRAND NAME :'. $productUsBrandName; else: echo '<br>GENERIC FOR :'. $productGenericName;endif;?></span>
							</a>
						<?php else:?>												
							<a href="<?php echo $productUrl;?>">
								<!-- discount tag-->
			                    <?php if ($bestProducts->getSpecialPrice() != '' && $bestProducts->getDiscountTag() != '' && ($bestProducts->isSaleable() || $bestProducts->getIsInStock()!=0)) :?>
			                    <span class="discount_tag"><?php echo $bestProducts->getDiscountTag() ?></span>
			                    <?php endif; ?>
			                    <!-- discount tag-->
								<img class="lazy" data-src="<?php echo $productImage; ?>"
								src="<?php echo $this->getSkinUrl('images/loading_1.gif') ?>"
								 alt="<?php echo $productName;?>" />
								<span><?php echo $productName;?></span>
								<span><?php if($productUsBrandName): echo '<br>US BRAND NAME :'. $productUsBrandName; else: echo '<br>GENERIC FOR :'. $productGenericName;endif;?></span>
							</a>
						</li>
						<?php endif ?>
					<?php }
				?>
			</ul>
		</div>
	</div>
<!-- Best Seller E-->
<!-- Best Seller Mobile S-->
	<div class="mobile_best_seller">
		<div class="mobile_best_seller_title">
			<span><?php echo strtoupper($bestSellingTitle);?></span>
		</div>
		<div class="mobile_best_seller_data ">
			<ul class="single-item">
				<?php
					foreach($bestSellingProducts as $bestProducts){
						$productName = $bestProducts->getName();
						$productGenericName = $bestProducts->getGenericName();
						$productUsBrandName = $bestProducts->getUsBrandName();
						$productUrl = $bestProducts->getProductUrl();
						$productImage = $this->helper('catalog/image')->init($bestProducts, 'image')->resize(81,176);?>
						<li>

							 <!-- freegifttext start -->
                            <?php
                            $giftProds = Mage::getStoreConfig('ampromo/gift_product/gift_product_item');
                            $giftSpan = '';
                            if($giftProds){
                             $giftProdsArr = explode(',', $giftProds);
                             $giftProdsArr=array_map('trim',$giftProdsArr);
                             
                        // $currSku = $child->getSku();
                             if(in_array($bestProducts->getSku(), $giftProdsArr)){
                               echo $giftSpan = '<span class="" title="Get a free gift"> Free Gift</span>';
                           }
                       }
                       
                       ?>
                       <!-- freegifttext end -->
							<a href="<?php echo $productUrl;?>">
								<!-- discount tag-->
			                    <?php if ($bestProducts->getSpecialPrice() != '' && $bestProducts->getDiscountTag() != '' && ($bestProducts->isSaleable() || $bestProducts->getIsInStock()!=0)) :?>
			                    <span class="discount_tag"><?php echo $bestProducts->getDiscountTag() ?></span>
			                    <?php endif; ?>
			                    <!-- discount tag-->
								<img class="lazy" data-src="<?php echo $productImage; ?>" src="<?php echo $this->getSkinUrl('images/loading_1.gif') ?>" alt="<?php echo $productName;?>" />
								<span><?php echo $productName;?></span>
								<span><?php if($productUsBrandName): echo '<br>US BRAND NAME :'. $productUsBrandName; else: echo '<br>GENERIC FOR :'. $productGenericName;endif;?></span>
							</a>
						</li>
					<?php }
				?>
			</ul>
		</div>
	</div>
<!-- Best Seller Mobile E-->
<!-- Popular categories S -->
	<div class="popular_categories">
		<div class="popular_categories_title">
			<span><?php echo strtoupper($popularCategoryTitle);?></span>
		</div>
		<div class="popular_categories_data">
		<?php
			foreach ($popularCategories as $_popularCat) {
			$popularCatName = $_popularCat->getName();
			$popularCatUrl = $_popularCat->getUrl();
			$popularCatImage = $_popularCat->getPopularBanner(); 
			//var_dump($popularCatImage);die;
		?>
		<?php $imageCategory = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/category/'.$popularCatImage;?>
		<li>
			<a href="<?php echo $popularCatUrl; ?>">
			<div class="popular_img_wrapper">
			<?php if($popularCatImage):?>

					<img class="lazy" data-src="<?php echo $imageCategory;?>"
					src="<?php echo $this->getSkinUrl('images/loading_1.gif') ?>"
					alt="<?php echo $imageCategory;?>" />

				<?php else:	?>
					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'onlinePharmacy/'. $categoryDefaultImg;?>">
				<?php endif;?>
			</div>
				<span class="popular_name"><?php echo $popularCatName; ?></span>
			</a>
		</li>
	<?php }
		?>
		</div>
	</div>
<!-- Popular categories E -->
<!-- Leading online pharmacy S -->	
	<div class="leading_online">
		<div class="leading_online_title">
			<span><?php echo strtoupper($onlinePharmacyTitle);?></span>
		</div>
		<div class="leading_online_data">
			<ul>
				<li class="leading_online_banner">
					<a href="<?php echo $banner_1_url;?>">
					<!-- <img src="<?php //echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'onlinePharmacy/'. $banner_1; ?>"/> -->

					<img class="lazy" 
					data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'onlinePharmacy/'. $banner_1; ?>"
					src="<?php echo $this->getSkinUrl('images/loading_1.gif') ?>"/>
					</a>
				</li>
				<li class="leading_online_banner">
					<a href="<?php echo $banner_2_url;?>">
					<!-- <img src="<?php //echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'onlinePharmacy/'. $banner_2; ?>"/> -->

					<img class="lazy" 
					data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'onlinePharmacy/'. $banner_2; ?>"
					src="<?php echo $this->getSkinUrl('images/loading_1.gif') ?>"/>
					</a>				
				</li>
				<li class="leading_online_banner">
					<a href="<?php echo $banner_3_url;?>">
					<!-- <img src="<?php //echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'onlinePharmacy/'. $banner_3; ?>"/> -->
					<img class="lazy" 
					data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'onlinePharmacy/'. $banner_3; ?>"
					src="<?php echo $this->getSkinUrl('images/loading_1.gif') ?>"/>
					</a>				
				</li>
			</ul>
		</div>		
	</div>
<!-- Leading online pharmacy E -->	
</div>
<script type="text/javascript">
	jQuery('.single-item').slick({
		responsive: [
	    {
	      breakpoint: 736,
	      settings: {
	        slidesToShow: 3,
	        slidesToScroll: 1
	      }
	    },
	    {
	      breakpoint: 630,
	      settings: {
	        slidesToShow: 2,
	        slidesToScroll: 1
	      }
	    },
	    {
	      breakpoint: 420,
	      settings: {
	        slidesToShow: 1,
	        slidesToScroll: 1
	      }
	    }
	  ]
	});
</script>
<script type="text/javascript">
jQuery(document).ready(function(){
	//alert(34);
	jQuery("img.lazy").lazy();
});


</script>
