<div style="border:1px solid #666;margin-top:-35px;margin-bottom:10px;padding:10px;font-size:15px;">
	<p style="font-weight:bold;">Women's Day Special <b>DISCOUNT OFFER</b><br/><br/>
		<span style="font-size:17px;">10% OFF*</span> on all Women's Health and Beauty Products!</p><br>

	<!-- <p>Use coupon code: <span style="font-weight:bold;">BEAUTIFUL10</span></p><br> -->

	<ul><span style="font-size:14px;color:red;">*Terms and Conditions</span>
		<li>• Minimum cart amount - 100$ (including shipping)</li>
		<li>• BEAUTIFUL10 code is case sensitive</li>
		<li>• Valid from 6th March till 20th March 2014 </li>
      	<li>• Only logged in users can use the coupon</li>
		<li>• One time use</li>
	</ul>
</div>