<?php
	$_helper = $this->helper('catalog/output');
	$_frontendHelper = $this->helper('frontend/data');
	$recentViewTitle = Mage::getStoreConfig('homepage_conf/guest_group/guest_home_slider');
	$recentViewCollection = Mage::helper('configurehomepage')->recentViewed();
	foreach ($recentViewCollection as $key) {
                $productsCollection = Mage::getModel('catalog/product')->load($key);}
?>
<!-- Recently Viewed item's S -->
<div class="mobile_stock">
    <a href="<?php echo $this->getUrl() ?>stock-clearance.html">
        <span class="stock-text"><b>Stock Clearance Sale</b></span><span class="stock-btn">View more</span>
    </a>              
</div>
<div class="recently_view_category_content">
<div class="register_user_categories">
	<div class="register_user_category_name">
		<span><?php echo strtoupper($recentViewTitle);?></span>
	</div>		
		<ul class="multiple-items">
				<?php foreach ($recentViewCollection as $key) { 
                $productsCollection = Mage::getModel('catalog/product')->load($key);
                ?>
            <div class="register_user_category_content">
                <li class="slick_list">
                    <!--lazy loading starts-->
            		<a href="<?php echo $productsCollection->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($productsCollection, 'small_image'), null, true) ?>" class="product_img">
                    <img class="lazy" src="<?php echo $this->getSkinUrl('images/loading_1.gif'); ?>" data-src="<?php echo $productsCollection->getImageUrl(); ?>" width="100" height="100" alt="<?php echo $productsCollection->getName();?>">
                    </a>
                    <!--lazy loading end-->
                    <?php if(!$productsCollection->isSaleable()):?>
                        <div class="stock_label">
                            <?php $custom_stock_status = $_frontendHelper->getCustomStockStatus($productsCollection);
                            if($custom_stock_status!='No' && $custom_stock_status!=''){ ?>

                                    <span><?php echo $this->__($custom_stock_status) ?></span>
                            <?php } else{ ?>
                                    <span><?php echo $this->__('Out of stock') ?></span>

                               
                            <?php } ?>
                        </div>
                    <?php endif; ?> 
                    <div class="product_desc">
                        <div class="product_name">
                            <a href="<?php echo $productsCollection->getProductUrl();?>">
                                <?php
                                    $pName = $_helper->productAttribute($productsCollection, $productsCollection->getName(), 'name');
                                    echo Mage::helper('core/string')->truncate($pName, 50);
                                ?>
                            </a>
                        </div>

                       <!-- <div class="desc std">
                            <?php //echo $_frontendHelper->getGenericInfo($productsCollection);?>                
                        </div>                    -->
                        <?php $usbrandName = $_frontendHelper->getUsBrandInfo($productsCollection);
                        if($usbrandName !='N/A' && $usbrandName !='No' ):?>
                        <div class="generic_name">
                            <?php                                
                                if(!empty($usbrandName)):
                                    echo $this->__('Generic for : ');
                                    echo $usbrandName;
                                endif;
                            ?>                    
                        </div>
                        <?php else:?><div class="generic_name"></div>
                        <?php endif;?>
                        <?php $manufacturedby = $_frontendHelper->getManufacturerInfo($productsCollection);
                        if($manufacturedby !='N/A' && $manufacturedby !='No'):?>                    
                        <div class="manu_name">
                            <div class="list-reviews grid-manufacturer">
                                <?php
                                    if(!empty($manufacturedby)):
                                        echo $this->__('Manufactured by : ');
                                        echo $manufacturedby;
                                    endif;
                                ?>                  
                            </div>
                        </div>
                        <?php else:?><div class="manu_name"></div>
                        <?php endif;?>
                    </div>
                    <?php
                        // $firstChildInfo = $_frontendHelper->getFirstChildPrice($productsCollection);
                        // if(!empty($firstChildInfo)):
                        //     echo $firstChildInfo;
                        // endif;
                    ?>
                </li>
            </div>
                <?php unset($productsCollection); } ?>
		</ul>
</div>
</div>
<!-- Recently Viewed item's E -->
<script type="text/javascript">
	jQuery('.multiple-items').slick({
	   dots: false,
	  infinite: true,
	  slidesToShow: 3,
	  slidesToScroll: 3,
	  responsive: [ 
    		{ 
                breakpoint: 630, 
                settings: { 
                slidesToShow: 2,
                slidesToScroll: 1, 
                infinite: false, 
                dots: false
    		} 
        },
        { 
                breakpoint: 420, 
                settings: { 
                slidesToShow: 1,
                slidesToScroll: 1
            } 
        }
        ] 
	});
    //lazyload function
</script>

<script type="text/javascript">
jQuery(document).ready(function(){
  jQuery('img.lazy').lazy({
   threshold : 5
});
   });
</script>