<div class="banner_below_sec" style="width:100%;overflow:hidden" >
	<div class="banner_below_sec_left" style="float:left">
		<?php $leftImagePath = Mage::Helper("configurehomepage")->registerLeftImage();?>
		<?php $leftImagePathUrl = Mage::Helper("configurehomepage")->registerLeftImageUrl();?>
		<a href="<?php echo $leftImagePathUrl;?>"><img src="<?php echo $leftImagePath;?>" width="100px" height="100px"></a>
	</div>	
	<div class="banner_below_sec_left" style="float:left">
		<?php $middleImagePath = Mage::Helper("configurehomepage")->registerMiddleImage();?>
		<?php $middleImagePathUrl = Mage::Helper("configurehomepage")->registerMiddleImageUrl();?>
		<a href="<?php echo $middleImagePathUrl;?>"><img src="<?php echo $middleImagePath;?>" width="100px" height="100px"></a>
	</div>	
	<div class="banner_below_sec_left" style="float:left">
		<?php $rightImagePath = Mage::Helper("configurehomepage")->registerRightImage();?>
		<?php $rightImagePathUrl = Mage::Helper("configurehomepage")->registerRightImageUrl();?>
		<a href="<?php echo $rightImagePathUrl;?>"><img src="<?php echo $rightImagePath;?>" width="100px" height="100px"></a>
	</div>	
</div>	