<div class="banner_below_content">
	<?php echo $this->getLayout()->createBlock("core/template")->setTemplate("homepage/register_banner_below.phtml")->toHtml();?>
</div>
<div class="mobile_stock">
	<a href="<?php echo $this->getUrl() ?>stock-clearance.html">
		<span class="stock-text"><b>Stock Clearance Sale</b></span><span class="stock-btn">View more</span>
	</a>              
	</div>
<div class="banner_below_category_content">
	<?php echo $this->getLayout()->createBlock("core/template")->setTemplate("homepage/register_banner_below_categoty.phtml")->toHtml();?>
</div>