

<div class="block block-list featured_products">
    <div class="block-title">
        <strong>
        	<span>Featured Products</span>
        </strong>
    </div>
    <div class="block-content featured-block-tab">
    	<div class="products-grid">
            <div class="item first">
                <a href="http://192.168.1.147/allday/eye-care/dorzox-t.html" title="Dorzox T  - 5 ml Eye Drop" class="product-image"><img class="lazy" src="http://192.168.1.147/allday/media/catalog/product/cache/1/small_image/100x/1023a0599857fc1de187ac9c9d2aa57d/s/k/sku_1031_1.jpg" width="100" height="100" alt="Dorzox T  - 5 ml Eye Drop" style="display: inline;"></a>

                <div class="pr-details-height">
                <h2 class="product-name"><a href="http://192.168.1.147/allday/eye-care/dorzox-t.html" title="Dorzox T  - 5 ml Eye Drop">Dorzox T  - 5 ml Eye Drop</a></h2>

                <div class="generic_name">
                            Dorzolamide Hydrochloride-Timolol Maleate
                        </div>

                        <div class="generic_for">
                            Generic for Cosopt
                        </div>
                 <div class="manufactured_by">
                    Manufactured by : Cipla, India                </div>
                <div class="first_child_info">
                    <p class="custom_price"><span class="custom_child_1">1</span><span class="custom_child_2"> Eye Drop</span><span class="custom_child_3"> - US$ 9.45</span></p>                </div>
                <div class="double_pill_offer">
                                    </div>
	 </div>


            </div>

             <div class="item second">
                <a href="http://192.168.1.147/allday/eye-care/dorzox-t.html" title="Dorzox T  - 5 ml Eye Drop" class="product-image"><img class="lazy" src="http://192.168.1.147/allday/media/catalog/product/cache/1/small_image/100x/1023a0599857fc1de187ac9c9d2aa57d/s/k/sku_1031_1.jpg" width="100" height="100" alt="Dorzox T  - 5 ml Eye Drop" style="display: inline;"></a>

                <div class="pr-details-height">
                <h2 class="product-name"><a href="http://192.168.1.147/allday/eye-care/dorzox-t.html" title="Dorzox T  - 5 ml Eye Drop">Dorzox T  - 5 ml Eye Drop</a></h2>


                        <div class="generic_name">
                            Dorzolamide Hydrochloride-Timolol Maleate
                        </div>

                        <div class="generic_for">
                            Generic for Cosopt
                        </div>
               
                 <div class="manufactured_by">
                    Manufactured by : Cipla, India                </div>
                    <div class="first_child_info">
                    <p class="custom_price">
                      <span class="custom_child_1">1</span>
                      <span class="custom_child_2"> Eye Drop</span>
                      <span class="custom_child_3"> - US$ 9.11</span></p>                
                  </div>

                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                </div>

            </div>
        </div>
        </div>
</div>


<script type="text/javascript">

  jQuery(document).ready(function($) {
    
        $('.featured_products .products-grid').slick({
        infinite: true,
        centerMode: false,
        slidesToShow: 1
        });  
  });

</script>
