<?php
/**
 * Product additional attributes template
 *
 * @see Mage_Catalog_Block_Product_View_Attributes
 */
?>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
    $category_id = Mage::getStoreConfig('general/herbalcategory/category_id',Mage::app()->getStore());
    $category_ids = $_product->getCategoryIds();
    $categoryCollection =array();
    foreach($category_ids as $cat){
        $parentcategoryid = Mage::getModel('catalog/category')->load($cat)->getParentCategory()->getId();
        array_push($categoryCollection,$parentcategoryid);
    }

    $attribute_list = Mage::getStoreConfig('hide_attribute_frontend/hide_attribute_additional/attribute_list',Mage::app()->getStore());
    $hideAttributeList = explode(',',$attribute_list);

?>
<?php if($_additional = $this->getAdditionalData()): ?>
<div class="box-collateral box-additional">
    <table class="data-table" id="product-attribute-specs-table">
        <col width="25%" />
        <col />
        <tbody>      
        <?php foreach ($_additional as $_data):    
            if(!in_array($category_id, $categoryCollection) && !in_array($_data['code'], $hideAttributeList)): ?>
            <tr>
                <th class="label"><?php echo $this->htmlEscape($this->__($_data['label'])) ?></th>
                <?php if(($_data["code"] == "shipped_from" && $_data['value'] == 'N/A') || ($_data["code"] == "shipped_from" && $_data['value'] == 'No')){ ?>
                <td class="data"><?php echo Mage::getStoreConfig('general/generalsetting/shippingfrom'); ?></td>
                <?php }elseif($_data['code']=='us_brand_name' && $_data['value'] == 'No') { 
                    $_data['value'] = $_product->getGenericName();
                    $_data['code'] = 'generic_name';
                ?>
                <td class="data"><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
                <?php }else{ ?>
                    <td class="data"><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td> 
                <?php } ?>
            </tr>
            <?php endif; ?> 
        <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('product-attribute-specs-table')</script>
</div>
<?php endif;?>
