<?php

$title = $this->getTitle();
$_frontendHelper = Mage::helper('frontend/data');
$cart = Mage::getModel('checkout/cart')->getQuote();
$current_product = Mage::registry('current_product');
if($current_product) {
  $productId = Mage::registry('current_product')->getId();
  $producsku = $this->getProduct()->getSku();
}
else {
  foreach ($cart->getAllItems() as $item) {
    $productId = $item->getProduct()->getId();
  }
}

$le = $this->getBoughtProducts($productId);

$lecount=count($le);
// Mage::log($le, null, 'productbought.log');
?>

<?php if($this->getEnable() && $lecount){ ?>
<div class="pr-similar-products">
<div class="block block-list block-compare bought-block-list">
  <div class="block-title" style="background-color:#FFFFFF;">
    <strong><span>
      <!-- SIMILAR PRODUCTS -->
      <?php echo $this->__('FREQUENTLY BOUGHT ALONG WITH THIS PRODUCT'); ?>
  </span></strong>

  </div>
    <?php if($lecount>0): ?>
  <div class="block-content bought-block-content">
    <ol id="wishlist-sidebar" class="bxslider mini-products-list bought-block-content-sidebar">
     <?php
     $productCount = 1;
     foreach ($le as $_index => $_item) {
       if($productCount%4==1) {
         echo "<li>";
       }
      $productUrl = $_item->getResource()->getAttribute('url_key')->getFrontend()->getValue($_item);
       ?>
       <div class="item">
        <div class="product-image">
          <a href="<?php echo $productUrl; ?>">
            <img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(200); ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" width="50" height="50" />
          </a>
        </div>
        <div class="product-details">
         <?php
           $strength = $_item->getData('configurable_attribute');
           $special_price = $_item->getData('special_price');
           $us_brand_name = $_item->getData('us_brand_name');
           $simpleProduct = $_frontendHelper->getFirstChildInfo($_item);
           $activeingredient = $_frontendHelper->getActiveIngredients($_item);
         ?>
         <a href="<?php echo $productUrl; ?>">
          <!--b><?php //echo $this->htmlEscape($_item->getName()).' '.$strength.'</b> <br/>'; ?> -->
          <b><?php echo $this->htmlEscape($_item->getName()).'</b> <br/>'; ?>
        </a>
         <span class="equivalentSty">(<?php echo 'Generic for '.' '.trim($us_brand_name)?>)</span>
         <a href="<?php echo $productUrl; ?>"><?php echo $this->htmlEscape($activeingredient) ?></a>
         <?php echo $simpleProduct; ?>
         <?php if($_item->isSaleable()): ?>
             <div class="clear"  ></div>
             <a href="<?php echo $this->getAddToCartUrl($_item) ?>" class="link-cart">
                <?php echo $this->__('View Details') ?>
            </a>
       <?php  endif; ?>
     </div>
   </div>
   <?php
   if($productCount==$lecount) {
     echo "</li>";
   }
   $productCount++;
 }
 ?>
</ol>

<?php else: ?>
  <div class="content"><p><?php echo $this->__('You have no items to bought.') ?></p></div>
<?php endif ?>
</div>
</div>
</div>
<?php } ?>

<script type="text/javascript">
// jQuery('.bxslider').bxSlider({
//   minSlides: 2,
//   maxSlides: 3,
//   slideMargin: 10,
//   pager: false,
//   infiniteLoop: false,
//   hideControlOnEnd: true
// });
</script>
