<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<script src='http://connect.facebook.net/en_US/all.js'></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl(); ?>/css/lp_style.css"/>
<link href='http://fonts.googleapis.com/css?family=Philosopher:700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Philosopher' rel='stylesheet' type='text/css'>

<div class="subscribe_block_outer" style="display:none;">
  <div class="subscribe_block_inner">
    <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml(); ?>
    <p class="close_inquiry"><img src="<?php echo $this->getSkinUrl('images/landing_Images/fancy_close.png'); ?>"/></p>
  </div>
</div>

<div class="landing_body">
  <div class="landing_content_top">
    <div class="landing_logo"> <a href="http://www.alldaychemist.com/" title="alldaychemist"> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/logo.png" alt="alldaychemist"> </a> </div>
    <div class="clear"></div>
    <div>
      <h1>Did you know these celebrities fought breast cancer?</h1>
      
      <p>Breast cancer, the most silent and the deadliest killer, spares no one. Behind the hard facts and statistics is a grim reality that it can hit anyone, and it is time to sit up and take notice. Social standing, economic status, general health - cancer cares for nothing. Awareness is imperative and a few celebrities have used their celebrity status for this magnanimous cause.</p>
      
      <p>Over the years, several celebrities have shared their cancer battle in public and the struggle, and their journey to overcome this condition. These celebrities have used their star power in the right way to spread awareness about breast cancer. They have empowered women all over the world to fight against this disease and survive it. </p>
      
      <!-- <p>Here are a few inspiring stories of well-known breast cancer survivors who took the bull by the horns. They not only moved on with their career but also provided motivation to women with breast cancer all over the world...</p> -->

      <p>The celebrities mentioned here are an exemplar of courage. So read on, be inspired. but don't stop there. Spread the awareness and do your bit.</p>
     
    </div>
  </div>
</div>
<div class="landing_content_bottom">
 
<ul>
      <li>
        <div class="story-para">
            <div class="image"> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/7.png" />
              <div class="c_name">Wanda Sykes</div>
            </div>
            <div class="content">
              <h2>The Hollywood funny-woman stood strong through her most difficult performance yet</h2>
              <p>While experiencing a successful career in films, she was diagnosed with DCIS (Ductal Carcinoma In Situ). Sykes, who had a breast cancer history on her mother’s side, did not want to run the risk of worsening her condition.</br> She had the option to have a mammogram and keep going back for MRI's every three months to keep the condition in check. However, she took the drastic step to have both her breasts removed so that she didn’t have to live with the fear of the cancer recurring at some point in her life. As tough as it was to go through bilateral mastectomy, Sykes got back to work soon after. She was back with a bang with her stand-up comedy tour just a month after the surgery. In 2011, she revealed her cancer story for the first time. Wanda Sykes credits her speedy recovery to her family, friends, husband and twin kids.</p>
              <div class="social_button">
                <div class="social_icon"> <a class="ld_facebook" href=""> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/fb.png" width="89" height="33"  alt=""/></a> </div>
                <div class="social_icon"> <a href="" class="ld_twitter" target="_BLANK"> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/twitter.png" width="89" height="33"  alt=""/></a> </div>
                <div class="clear"></div>
              </div>
              
            </div>
            <div class="clear"></div>
          <div class="bottom_line"></div>  
        </div>  
      </li>
      <li class="right-story">
        <div class="story-para">
            <div class="image"> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/6.png" />
              <div class="c_name">Peter Criss</div>
            </div>
            <div class="content">
              <h2>The Catman beats the odds</h2>
              <p>The rock star first noticed painful lumps in his chest in 2007, following which he got himself checked by a doctor. It was found that he has a nodule in his chest(the breast tissue) that was breast cancer. In 2008, Criss went through a surgery to remove the cancer. Fortunately, since the cancer had not spread, Criss escaped chemotherapy. It has not resurfaced since, and Criss gets mammograms on a monthly basis. Criss is an inspiration to all men dealing with a similar problem. His message to men is, “It's just important, just get it checked. It's not like you're going to lose your manhood."</p>
              <div class="social_button-left">
                <div class="social_icon"> <a class="ld_facebook" href=""> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/fb.png" width="89" height="33"  alt=""/></a> </div>
                <div class="social_icon"> <a href="" class="ld_twitter" target="_BLANK"> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/twitter.png" width="89" height="33"  alt=""/></a> </div>
              </div>
              <div class="clear"></div>
            </div>
            <div class="clear"></div>
          <div class="bottom_line"></div>
        </div>  
      </li>
      <li>
        <div class="story-para">
            <div class="image"> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/1.png" />
              <div class="c_name">Christina Applegate</div>
            </div>
            <div class="content">
              <h2>Accolades and perseverance: The Christina Applegate story</h2>
              <p>She is a breast cancer survivor and was diagnosed with it at a young age of 36. She initially lived with the disease quietly without telling anyone about it. However, she later opened up about her battle with cancer to make all the young women out there aware of the risks of breast cancer. She opted for a double mastectomy at the age of 36. Early detection and surgery saved her life. Christina founded the Right Action for Women, which aims at raising awareness and providing free MRI's to women at high risk for breast cancer.</p>
              <div class="social_button">
                <div class="social_icon"> <a class="ld_facebook" href=""> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/fb.png" width="89" height="33"  alt=""/></a> </div>
                <div class="social_icon"> <a href="" class="ld_twitter" target="_BLANK"> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/twitter.png" width="89" height="33"  alt=""/></a> </div>
              </div>
              <div class="clear"></div>
            </div>
            <div class="clear"></div>
        <div class="bottom_line"></div>
        </div> 
      </li>
      <li class="right-story">
        <div class="story-para">
            <div class="image"> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/2.png" />
              <div class="c_name">Giuliana Rancic</div>
            </div>
            <div class="content">
              <h2>An anchor in every way</h2>
              <p>The E! News host was informed that she has early-stage breast cancer in October 2011. This was when she was struggling with infertility and seeking IVF treatment to get pregnant. Her tumor was discovered when she got a mammogram right before a round of IVF treatment. She got many lymph nodes removed and got a double lumpectomy done, but that did not clear her cancer completely. So, in December 2011, Rancic has a double mastectomy and reconstructive surgery.</p>
              <div class="social_button-left">
                <div class="social_icon"> <a class="ld_facebook" href=""> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/fb.png" width="89" height="33"  alt=""/></a> </div>
                <div class="social_icon"> <a href="" class="ld_twitter" target="_BLANK"> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/twitter.png" width="89" height="33"  alt=""/></a> </div>
              </div>
              <div class="clear"></div>
            </div>
            <div class="clear"></div>
          <div class="bottom_line"></div>
        </div>
      </li>
      <li>
        <div class="story-para">
            <div class="image"> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/3.png" />
              <div class="c_name">Sheryl Crow</div>
            </div>
            <div class="content">
              <h2>The tough songbird</h2>
              <p>Sheryl Crow resorted to a minimally invasive surgery to save her life. She finds herself extremely lucky to have had her breast cancer diagnosed early enough to avoid chemotherapy. Seven weeks of radiation along with a lumpectomy helped her get to through the battle against breast cancer. However, she was diagnosed with a benign brain tumor after a yearly breast cancer checkup. Sheryl describes the noncancerous tumor as another“bump in the road” and is putting up a good fight. She is a true inspiration to women all around the world.</p>
              <div class="social_button">
                <div class="social_icon"> <a class="ld_facebook" href=""> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/fb.png" width="89" height="33"  alt=""/></a> </div>
                <div class="social_icon"> <a href="" class="ld_twitter" target="_BLANK"> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/twitter.png" width="89" height="33"  alt=""/></a> </div>
              </div>
              <div class="clear"></div>
            </div>
            <div class="clear"></div>
          <div class="bottom_line"></div>
        </div>
      </li>
      <li class="right-story">
        <div class="story-para">
            <div class="image"> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/4.png" />
              <div class="c_name">Cynthia Ellen Nixon</div>
            </div>
            <div class="content">   
              <h2>From actor to icon</h2>
              <p>Actress Cynthia Ellen Nixon is famous for playing Miranda Hobbes in Sex and the City, which is the popular series aired on HBO. She has won two Emmy awards, Tony and Grammy award for her excellent prowess in acting.</p>
              <p>At the age of 40, she was diagnosed with breast cancer when she was undergoing a routine mammogram. Initially, she tried to keep the disease under wraps on knowing about it in 2006. When Cynthia was just 12 years old, she saw her mother battle with cancer. After a mammogram, doctors found a small tumor. She underwent a lumpectomy and six weeks of radiation treatment. Cynthia opened up about her struggle with breast cancer later. She was chosen as an ambassador for Susan G. Komen, the biggest breast cancer organization in the world.</p>
              <div class="social_button-left">
                <div class="social_icon"> <a class="ld_facebook" href=""> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/fb.png" width="89" height="33"  alt=""/></a> </div>
                <div class="social_icon"> <a href="" class="ld_twitter" target="_BLANK"> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/twitter.png" width="89" height="33"  alt=""/></a> </div>
              </div>
              <div class="clear"></div>
            </div>
            <div class="clear"></div>
          <div class="bottom_line"></div>
        </div> 
      </li>
      <li style="margin-bottom:0px;">
        <div class="story-para">
            <div class="image"> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/8.png" />
              <div class="c_name">Carly Simon</div>
            </div>
            <div class="content">
              <h2>A fine display of strength and vitality</h2>
              <p>She chose to undergo chemotherapy to be on the safe side. The singer wanted to keep her battle with cancer under wraps. Following the advice of her doctor, she did not want to be a spokesperson while she was still undergoing treatment for cancer and kept her life uncomplicated. Even when she was undergoing chemotherapy, Simon continued to work on her new album. When she revealed her story of survival a year later, Carly Simon said, “I feel stronger and more vital than ever.”</p>
              <p>These stories are a real inspiration for every woman who is battling breast cancer. They also reveal that fame and money prove to be futile when it comes to breast cancer. Therefore, it is of utmost importance to be aware of breast cancer symptoms and survival tactics that can be used to battle it out.
              </p>
              <div class="social_button">
                <div class="social_icon"> <a class="ld_facebook" href=""> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/fb.png" width="89" height="33"  alt=""/></a> </div>
                <div class="social_icon"> <a href="" class="ld_twitter" target="_BLANK"> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/twitter.png" width="89" height="33"  alt=""/></a> </div>
              </div>
              <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </li>
    </ul>
  </div>
<div class="landing_footer">
  <div >Copyright © 2014 Alldaychemist. All right reserved.</div>
  <div style="margin-top:10px; padding: 0 0 3.5%;">
    <div class="social_icon"> <a href="https://www.facebook.com/alldaychemist2" target="_BLANK"> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/fb_small.png" /> </a> </div>
    <div class="social_icon"> <a href="https://twitter.com/alldaychemist1" target="_BLANK"> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/twitter_small.png" /> </a> </div>
    <div class="social_icon"> <a href="http://www.pinterest.com/alldaychemist" target="_BLANK"> <img src="<?php echo $this->getSkinUrl(); ?>images/landing_Images/pinterest_small.png" /> </a> </div>
  </div>
</div>
<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/subscription_landing.phtml')->toHtml(); ?>
<!-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script> -->
<script type="text/javascript">
jQuery(document).ready(function($){
    $(".ld_twitter").click(function(){
      var content = "few inspiring stories of well-known breast cancer survivors read more @ https://www.alldaychemist.com/breast_cancer";
      window.open('http://twitter.com/?status='+content,'_blank');
    });

    $(".ld_facebook").click(function(){
          var url = window.location;
          var fb = window.open('http://www.facebook.com/sharer.php?s=100&p[url]='+encodeURIComponent(url));
      fb.focus();
    });

    // if(getCookie("newsletter") != 'closed')  {
    //   setTimeout(function() {
    //         $('.subscribe_block_outer').fadeIn('fast');
    //       }, 30000);
    // }
    // $('#newsletter').attr('placeholder', 'Subscribe To Our Newsletter...');
    // $('.close_inquiry').click(function(){
    //     closeInquiry();
    // });

    // function closeInquiry(){
    //   $('.subscribe_block_outer').fadeOut('fast');
    // }

    // function getCookie(cname) {
    //     var name = cname + "=";
    //     var ca = document.cookie.split(';');
    //     for(var i=0; i<ca.length; i++) {
    //         var c = ca[i];
    //         while (c.charAt(0)==' ') c = c.substring(1);
    //         if (c.indexOf(name) != -1) {
    //             return c.substring(name.length, c.length);
    //         }
    //     }
    //     return "";
    // }

    // $('#newsletter-validate-detail').submit(function(e){
    //   if(newsletterSubscriberFormDetail.validator && newsletterSubscriberFormDetail.validator.validate()){
    //     document.cookie = "newsletter=closed";
    //     $('.subscribe_block_outer').hide();
    //   }
    // });
    $("#hello").html(window.location.protocol);
    var subsclose_val = get_cookie("subsclose");

    if(subsclose_val=="yes") {
        CloseSubscription(1);
    }
    $("#close_subs").click(function(){
        CloseSubscription();
    });
    $("#show_subs").click(function(){
        ShowSubscription();
    });

    $('#subscribebtn').click(function(){
        if($('#txtEmailDiv').val()==''){
            // alert('please enter the email id');
            $('#txtEmailDiv').val('Please enter your email-id here');
        }
        else{
            var emailid = $('#txtEmailDiv').val();
            var check = IsEmail(emailid);

            if(check){
                var url = 'http://' + window.location.hostname + '/';
                if (window.location.protocol === 'https:') {
                    url = 'https://' + window.location.hostname + '/';
                }
                var url = url+'newsletter/subscriber/newSub';
                $('.loader').show();

                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {email:emailid},
                    success: function(resultData) {
                    $('.subscribe').css('display','none');
                    $('.subscribe_msg').html(resultData).css('display','block');
                    $('.loader').hide();
                    setTimeout(function(){
                      $('.subscribe_msg').animate({display: "none"}, 500, function(){
                        $('.subscribe').show(); $('#toTop #txtEmailDiv').val('');
                        if(resultData == "Thank you for your subscription.") {
                            CloseSubscription();
                        }
                      });
                    }, 2000);
                    }
                });
            }
            else{
                alert("Please enter valid email-id");
                $('#txtEmailDiv').val('Please enter your email-id here').focus();
            }
        }
    });    
});

function IsEmail(email) {
    var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
    return regex.test(email);
}
function hideText(element, defaultVal) {
    if (element.value == defaultVal || element.value == "Invalid Email Address" || element.value == "Please enter a valid email-id" || element.value == "Thank You" || element.value == "Already Subscribed") {
        element.value = '';
    }
}
function showText(element, defaultVal) {
    if (element.value == '') {
        element.value = defaultVal;
    }
}
function CloseSubscription(val) {
        //alert(val);
        jQuery('#toTop .subscribe').hide(); jQuery('#toTop .subscribe_msg').hide();
        if(val==1) {
            jQuery('#toTop').css('width', '35px'); jQuery('#close_subs').hide(); jQuery('#show_subs').show();
        } else {
            jQuery('#toTop').animate({width: "35px"}, 500, function(){
                jQuery('#close_subs').hide(); jQuery('#show_subs').show();
            });
        }
        var cookie_status = get_cookie('subsclose');
        if(cookie_status != "yes") {
            var now = new Date();
            var time = now.getTime();
            time += 3600 * 1000 * 700;
            now.setTime(time);
            document.cookie = 
            'subsclose=yes' + 
            '; expires=' + now.toGMTString() + 
            '; path=/';
        }
    }
function ShowSubscription() {
    jQuery('#toTop').animate({width: window.innerWidth}, 500, function(){
        jQuery('#toTop .subscribe').show(); jQuery('#close_subs').show(); jQuery('#show_subs').hide();
    });
    document.cookie = 
    'subsclose=no' + 
    '; expires=Thu, 01 Jan 1970 00:00:01 GMT' 
    '; path=/';
}
function get_cookie(Name) {
    var search = Name + "="
    var returnvalue = "";
    if (document.cookie.length > 0) {
        offset = document.cookie.indexOf(search)
        // if cookie exists
        if (offset != -1) { 
            offset += search.length
            // set index of beginning of value
            end = document.cookie.indexOf(";", offset);
            // set index of end of cookie value
            if (end == -1) end = document.cookie.length;
            returnvalue=unescape(document.cookie.substring(offset, end))
        }
    }
    return returnvalue;
}
</script>
<style>
  *{margin:0px; padding:0px;}
body {margin: 0;padding: 0px!important;background-image: url('<?php echo $this->getSkinUrl("images/landing_Images/Bg1.png"); ?>')!important;}
.landing_body {width: 960px;margin:-15px auto;}
.landing_content_bottom ul {margin-top: 0px;}
.landing_logo {float: right;}
.clear {clear: both;}
.landing_content_top h1 {font-family: 'Philosopher', sans-serif;text-align: center;color: #970045;margin: 30px 0px 30px 0px;font-size: 32px;text-transform: uppercase;font-weight: 700;margin-right: 2%;}
.landing_content_top p {color: #333;font-family: 'Philosopher', sans-serif;margin: 0px 0px 30px 0px;display: inline-block;font-size:18px;line-height:26px;text-align: justify;background-image: url('<?php echo $this->getSkinUrl("images/landing_Images/Banner_divider1.png"); ?>');background-repeat:no-repeat;background-position:left top 5px;padding:0px 20px 0px 12px;}
.landing_content_bottom {padding: 0px;background-image: url('<?php echo $this->getSkinUrl("images/landing_Images/content-top.png"); ?>');background-repeat: no-repeat;background-size: 100%;margin:70px 0px 0px 0px;padding-top:5%;}
.landing_content_bottom ul {background-image: url('<?php echo $this->getSkinUrl("images/landing_Images/Bg2.jpg"); ?>');background-repeat: no-repeat;background-size: 100%;background-color:#fe99b9;padding: 0px 10px 0 30px;}
.landing_content_bottom li {list-style: none;margin:0px 0px 20px 0px;}
.story-para{width:960px; margin:0 auto }
.landing_content_bottom li .image {float: left;width: 285px;padding-bottom:25px;}
.landing_content_bottom li .content {float:left;vertical-align: top;margin:0px 20px 0px 20px;width:580px;padding:8px 0px 25px 0px;font-family:verdana;font-size:14px;color:#000;line-height:20px;}
.landing_content_bottom li .content p{margin:0px 0px 20px 0px; text-align: justify; color: #333;}
.landing_content_bottom li .bottom_line {background-image: url('<?php echo $this->getSkinUrl("images/landing_Images/divider.png"); ?>');height: 14px; background-position: center center;}
.landing_content_bottom li .content h2 {color: #970045;font-family: 'Philosopher', sans-serif;font-size:22px;font-weight:normal;font-size:24px;line-height:28px;margin-bottom:10px;font-weight: 700;}
.image .c_name {text-align: center;text-transform: uppercase;color: #970045;font-family: 'Philosopher', sans-serif;font-size:20px;margin:5px 0px 0px 0px;}
.social_icon {display: inline-block;}
.social_button {float: right;}
.social_button-left {float: left;}
.divider1 {background-image: url('<?php echo $this->getSkinUrl("images/landing_Images/Banner_divider1.png"); ?>');width: 4px;height: 48px;display: inline-block;}
.divider2 {background-image: url('<?php echo $this->getSkinUrl("images/landing_Images/Banner_divider2.png"); ?>');width: 4px;height: 48px;display: inline-block;}
.divider3 {background-image: url('<?php echo $this->getSkinUrl("images/landing_Images/Banner_divider3.png"); ?>');width: 4px;height: 31px;display: inline-block;}
.landing_head_para {}
.landing_footer {color: #909090;background-color:#fff;text-align: center;margin-top: -15px;padding:10px 0px;font-family:verdana;font-size:12px;}
.landing_content_bottom li.right-story .image{float:right}
.landing_content_bottom li..right-story .content{float:left}
.subscribe_block_outer { position: fixed !important;float: none !important; margin: 0 !important; top: 0; left: 0; right: 0; bottom: 0; z-index: 1000; height: 100%; width: 100% !important; background-color: rgba(0, 0, 0, 0.5); }
.subscribe_block_outer .subscribe_block_inner { background-image: url('<?php echo $this->getSkinUrl("images/landing_Images/Bg1.png"); ?>'); clear: both; padding: 20px; display: block; width: 35%; height: auto; margin: 15% auto; position: relative;overflow: visible;}
.subscribe_block_outer .subscribe_block_inner .close_inquiry {position: absolute; top: -15px; right: -15px; color: #f13333; cursor: pointer;font-size: 18px;font-weight: bold;}
.loader {position: absolute; top: 0; left: 0; right: 0; bottom: 0; background-color: #fff; z-index: 9999; opacity: .7;
background-image: url('<?php echo $this->getSkinUrl("images/landing_Images/loading.gif"); ?>'); background-repeat: no-repeat; background-position: 50% 50%;}
.subscribe_block_outer .block-title {display: none;}
.subscribe_block_outer .block-content {padding: 20px;}
.subscribe_block_outer .input-box {width: 75%; float: left;}
.subscribe_block_outer .input-box .input-text {background: #ddd !important;}
.subscribe_block_outer .actions {float: left; padding: 0;}
.subscribe_block_outer .block.block-subscribe {background: #f5f5f5; border: 1px solid #eee; border-radius: 6px; margin-bottom: 15px;}
::-webkit-input-placeholder  {color: #777;}
:-moz-placeholder  {color: #777;}
::-moz-placeholder  {color: #777;}
:-ms-input-placeholder {color: #777;}

/* Responsive css goes here */

@media screen and (max-width:900px){
body{overflow-x:hidden}
body div{width:95%!important;margin-left:auto!important;margin-right:auto!important;float:none!important;text-align:center!important;}
body div div{width:100%!important;display:block}
img{max-width:100%;height:auto}
.landing_content_bottom li .image {float: left !important;padding-bottom: 0px;width: 30% !important;
}
.landing_content_bottom li .content {float: left !important; margin-left: 2% !important;text-align: left !important;width: 65% !important;}
.social_button {text-align: right !important;}
.social_icon {width: auto !important;}
.social_button-left {text-align: left !important;}
}
@media screen and (max-width:640px){
.landing_content_bottom {margin: 3% 0 0;}
.landing_content_bottom li .image {float: none !important;padding-bottom: 0px;width:140px !important;}
.landing_content_bottom li .content {float: none !important; margin-left: 0% !important; text-align: left !important;width: 100% !important;}
.landing_content_bottom ul {padding: 0 3%; background-repeat:repeat; background-position:auto auto}
.social_button {text-align: left !important;}
.landing_content_top h1 {font-size: 34px; margin-bottom:10px;}
.landing_content_top p {margin: 0 0 20px; padding: 0 5px 0 12px;}
}
</style>