
<!-- <div style="position: fixed; right: 0px; top: 0px; z-index: 99"  class="bookMark_tag">
  <a href="#inline2" class="freeship_msg various" id="limited_offer_hangging">
    <img width="120px" src="<?php //echo $this->getSkinUrl('images/limited-offer.png'); ?>" />
  </a>
</div> -->
<div style="position: fixed; right: 0px; top: 0px; z-index: 100" class="bookMark">
	<a href="#" onclick="return add_favorite(this);">
		<img width="120px" src="<?php echo $this->getSkinUrl('images/bookmark_add.png'); ?>" />
	</a>
</div>

<script type="text/javascript">
function add_favorite( a ) { 
	title = document.title; 
	url = document.location; 
	try { 
// Internet Explorer 
window.external.AddFavorite( url, title ); 
} 
catch (e) { 
try { 
  // Mozilla 
  window.sidebar.addPanel( title, url, "" ); 
} 
catch (e) { 
  // Opera 
  if( typeof( opera ) == "object" ) { 
  	a.rel = "sidebar"; 
  	a.title = title; 
  	a.url = url; 
  	return true; 
  } 
  else { 
    // Unknown 
    alert( 'Press CTRL+D to add page to your bookmarks' ); 
} 
} 
} 
return false; 
}
</script>