<?php
    $str = $this->helper('catalogsearch')->getEscapedQueryText();
	$newstr = explode("-",$str);
	if(isset($newstr[1])&& $newstr[1] != "")
	{
	    $searchtxt = $newstr[0];
	}
	else
	{
		$searchtxt = $this->helper('catalogsearch')->getEscapedQueryText();
	}

?>


<form id="search_mini_form" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get">
    <div class="form-search">
        <label for="search"><?php echo $this->__('Drug Search&nbsp;') ?></label>
        <div class="search_area">
            <input id="search" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php echo $searchtxt; ?>"  class="input-text" />
            <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
        </div>
        <div id="search_autocomplete" class="search-autocomplete"></div>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__("Search your product here...") ?>');
    searchForm.initAutocomplete('<?php echo $this->helper("searchautocomplete")->getSuggestUrl() ?>', 'search_autocomplete');
    //]]>
</script>

<script>
jQuery(document).ready(function(){
  jQuery('#search').keydown(function(){
    if(event.which==40 || event.which==38) {
        if(jQuery('li.selected').length) {
          var search_string = jQuery('li.selected').html().replace(/<\/?[^>]+(>|$)/g, "").split("-");
           jQuery('#search').val(jQuery.trim(search_string[0]));
      }
    }
  });

});
</script>
