<?php $catalogSearchHelper =  $this->helper('catalogsearch');

?>
<form id="search_sidebar_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
<?php //$attribute = Mage::getModel('eav/config')->getAttribute('catalog_product', 'brand');?>
<?php 
$collection = Mage::getModel('catalog/product')
	->getCollection()
	->addAttributeToSort('name', 'ASC')
	->addAttributeToFilter(
    	'status', array('eq' => Mage_Catalog_Model_Product_Status::STATUS_ENABLED));
$collection->addAttributeToSelect('name');
$collection->addAttributeToSelect('us_brand_name');
$collection->addAttributeToSelect('active_ingridients');
$collection->addAttributeToSelect('generic_name');
$collection->addAttributeToFilter('type_id', array('eq' => 'configurable'));
//$collection->addAttributeToFilter('type_id', array('eq' => 'simple'));
/*echo "<pre>";
print_r($collection);
exit();*/
?>
<?php //$attribute = Mage::getModel('eav/config')->getAttribute('catalog_product', 'us_brand_name');?>
<?php //$generic = Mage::getModel('eav/config')->getAttribute('catalog_product', 'active_ingridients');?>

<div class="drugSearch">
	<ul>					
		<li><span>Brand</span> <br /> 
		<select id="dropdown1"> 
			<option value="Us">All US Brands</option>
			<?php $i=0;
				foreach ($collection as $product) {
											
						$data = $product->getData('us_brand_name');
						$data = str_replace('cream','',$data);
						$brand_active[]= trim($data);
						$finalBrand_active=array_unique($brand_active);
				}
				?>
			<?php //endforeach; 
			asort($finalBrand_active);?>
			<?php foreach($finalBrand_active as $names):?>
				<?php if($names != 'Latisse'): ?>
					<option value="Us"><?php echo $this->__($names); ?></option> 
				<?php endif; ?>
			<?php endforeach;?>
			
			<?php /*foreach ( $attribute->getSource()->getAllOptions(true, true) as $option):?>
			<?php if (!empty($option['label'])):?>			
			<option value="Us"><?php echo $option['label'];?></option> 
			<?php endif;?>
			<? endforeach;*/?>
		</select> 
		</li>
		<li><span>Active Ingredients </span><br /> 
		<select id="dropdown2"> 
			<option value="Us">Select Options</option> 
			<?php 
				foreach ($collection as $product) {
						$data = $product->getData('generic_name');
						$data = str_replace('cream','',$data);
						$active[]= trim($data);
				}
				$final_active=array_unique($active);
			?>
			<?php //foreach($final_active as $value):?>
				<?php //$active_names[]=$collection->getResource()->getAttribute('active_ingredients')->getSource()->getOptionText($value);?>
			<?php //endforeach; 
			asort($final_active);?>
			<?php foreach($final_active as $names):?>
				<option value="Us"><?php echo $this->__($names);?></option> 
			<?php endforeach;?>
		</select>
		</li>
		<li><span>Product Search <span><br /> <input type="text" id="searchtext"/></li>
		<input id="searchquery" type="hidden" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText(); ?>" >
		<li><button type="submit" title="<?php echo $this->__('Search') ?>" ><?php echo $this->__('Search') ?></button></li>
	</ul>
</div>
</form>
<script type="text/javascript">
	jQuery(document).ready(function($){
		var query = "";
		jQuery('#dropdown1').change(function(){	
			jQuery("#dropdown1 option:selected").each(function () {
				//jQuery('#searchquery').val($(this).text()+" -brand");
				jQuery('#searchquery').val($(this).text());
				//Code To submit form
				jQuery('#search_sidebar_form').submit();
				// if(query==""){
					// query += $(this).text() ;
				// }else{
						// query += " , " + $(this).text() ;
				// }
			});
			// $('#searchquery').val(query) ;
		});
		jQuery('#dropdown2').change(function(){	
			jQuery("#dropdown2 option:selected").each(function () {
				
				var active=$(this).text().split(' ');
				//alert(active[0]);
				//jQuery('#searchquery').val(active[0]);
				//jQuery('#searchquery').val($(this).text()+" -brand");
				jQuery('#searchquery').val($(this).text());
				//Code To submit form
				jQuery('#search_sidebar_form').submit();
				// if(query==""){
					// query += $(this).text() ;
				// }else{
						// query += " , " + $(this).text() ;
				// }
			});
			// $('#searchquery').val(query) ;
		});
		jQuery("#searchtext").keyup(function () {
				// if(query==""){
					// query += $(this).val();
				// }else{
					// query += " , " + $(this).val();
				// }
				 query = $(this).val();
				jQuery('#searchquery').val(query);							
		});
		
	})
</script>