<?php
$ruleName = array();
$ruleCollection = Mage::getModel('salesrule/rule');
// echo "<pre>";
// print_r($this->helper('checkout/cart')->getQuote()->getAppliedRuleIds());

 // echo "<pre>";  echo "salman"; print_r($this->helper('checkout/cart')->getQuote()->getData('rewardpoints')); exit;

$rewardpoints = $this->helper('checkout/cart')->getQuote()->getData('rewardpoints');
$appliedRules = $this->helper('checkout/cart')->getQuote()->getAppliedRuleIds();
$subtotal = $this->helper('checkout/cart')->getQuote()->getSubtotal();
$order_totals = $this->getTotal()->getValue();
$cartqty = $this->helper('checkout/cart')->getQuote()->getData('items_qty');


$cartItems = $this->helper('checkout/cart')->getQuote()->getAllItems();
foreach ($cartItems as $item)
{
    $productQty[] = $item->getQty();
}

foreach(explode(",",$appliedRules) as $ruleID){
    $rule = $ruleCollection->load($ruleID);
    if($rule->getDiscountAmount() > 0) { 
        $ruleNames[] = $rule->getName(); 
    }
    // if( $rule->getSimpleAction() != 'by_percent' ) {
    //     $dummyTotal += $rule->getDiscountAmount();
    // }
}
$ruleTitle = implode(',',$ruleNames);
?>
<tr>
    <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="totals-rewards">
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
        <?php //echo $this->escapeHtml($this->getTotal()->getTitle()); ?>
        <span class="dis_label">
            <?php 
                // if($this->getTotal()->getTitle() == 'Discount'){ 
            echo '<b>Discount('.$ruleTitle.')</b>';
                // } else { 
                    // echo $this->getTotal()->getTitle();
                // } ?></span>
                <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
            </td>
            <td style="<?php echo $this->getTotal()->getStyle() ?>">
                <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
                <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
                <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
            </td>
        </tr>
        <?php
        foreach(explode(",",$appliedRules) as $ruleID) {
            $rule = $ruleCollection->load($ruleID);
            $ruleAmount[] = $rule->getDiscountAmount();
            if( $rule->getSimpleAction() != 'by_percent' ) {
                $dummyTotal += $rule->getDiscountAmount();
            }
    // echo $dummyTotal;
        }

        $totals = Mage::getSingleton('checkout/session')->getQuote()->getTotals();
        $totalDiscount = abs(round($totals["discount"]->getValue(),2));
        $finalDiscount = Mage::helper('core')->currency($totalDiscount, true, false);
        ?>
        <tbody class="discount_block" style="display:none;">
            <?php if($rewardpoints): 
                $ruleTitle .=',Rewardpoints Discount';
            ?>
        <?php endif; ?>
            <tr>
                <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="label"><strong><?php if($rule->getDiscountAmount() > 0) { echo $ruleTitle; }?></strong></td>
            <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>">
                <?php 
                echo $finalDiscount;
                ?>
            </td>
        </tr>
    </tbody>
    <script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('#checkout-review-table .discount_block .label').attr("colspan", 3);
        var img_url = "<?php echo Mage::getDesign()->getSkinUrl('images',array('_area'=>'frontend')) ?>"+'/j2t_add_one.png';
        more_discount = jQuery(".totals-rewards").prepend('<span class="more_offers"><img src="'+img_url+'" style="height:100%; width:auto;"/></span>');
        jQuery('.totals-rewards').click(function(){
            jQuery('.discount_block').toggle();
        });
    });
    </script>
    <style type="text/css">
    .totals-rewards { cursor: pointer; }
    .totals-rewards .more_offers { height: 20px; width: 20px; display: inline-block; }
    </style>
