<?php
$_productCollection = $this->getLoadedProductCollection();	
//////////////////code added by sammeer for index navigation//////////////////////

$letarray = array('#','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z');
$let = array();
foreach ($letarray as $l) {$let[$l] = $l;}

$currentUrl = 'http://' . $_SERVER["SERVER_NAME"] . $_SERVER['REQUEST_URI'];
$without_query_string = explode('?', $currentUrl);
$init_url = $without_query_string[0] . '?';

$query = $_productCollection->getSelect();  //you can echo $query to see actual SQL
                                            //we then remove last part to get a query that will give us ALL product names
if (isset($_REQUEST['let'])) {$ipp = explode('WHERE',$query);} else {$ipp = explode('ORDER',$query);}
$query = $ipp[0];

$da_names = Mage::getSingleton('core/resource')->getConnection('core_read')->fetchAll($query);
foreach ($da_names as $dd) {
$_name = strtoupper($dd["name"]);
if ($_name[0] < 'A') {if ($let['#'] == '#') {$let['#'] = "<a href=\"$init_url" . 'let=1">#</a>';}} else {
if ($_name[0] == $let[$_name[0]])  {$let[$_name[0]] = "<a href=\"" . $init_url . 'let=' . $_name[0] . '">' . $_name[0] . '</a>';}}    
}
    
    if (isset($_REQUEST['let'])) {
    if ($_REQUEST['let'] == '1') {$let['#'] = '<li style="color : red; font-weight: bold">#</li>';}
    else {$let[$_REQUEST['let']] = '<li style="color : red; font-weight: bold">'. $_REQUEST['let'] .'</li>';}
    }
  
$sto = '<ol><li><a href="' . $without_query_string[0] . '">ALL</a></li><li>|</li>' . "\n";
foreach ($letarray as $l) {$sto .= "<li>" . $let[$l] . "</li>\n";}
$sto .= "</ol>\n";
//////////////////////////////////////////////////////////////////////////////////
	
	 $_helper = $this->helper('catalog/output');
	
?>
<?php if(!$_productCollection->count()): ?>

<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products"> <?php echo $this->getToolbarHtml() ?>
  <?php $cat_id = Mage::getModel('catalog/layer')->getCurrentCategory()->getId();?>
  <?php// List mode ?>
  <?php if($this->getMode()!='grid'): ?>
  <?php $_iterator = 0; ?>
  <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product):

	 ?>
    <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
      <?php // Product Image ?>
      <div class="list-inner"> <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img class="pr-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(170); ?>" width="170" height="170" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> </a><!--a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' data-fancybox-group="gallery" class='fancybox' id='fancybox<?php echo $_product->getId()?>' style=''><?php echo $this->__('Quick View') ?></a--></div>
      <?php // Product description ?>
      <div class="product-shop">
	  	 <?php  $messagebox=trim($_helper->productAttribute($_product, $_product->getGenericName(), 'generic_name'));
				if(stripos($messagebox, "Tadalafil") !== false){
				echo '<p style="color:red;padding-bottom:10px;">Tadalafil is not for consumption in United States</p>';
				}   
		  
		 ?>
        <div class="f-fix">
	
          <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
          <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name')." ". $_helper->productAttribute($_product, $_product->getConfigurableAttribute() , 'configurable_attribute'); ?></a></h2>
          <!-- div class="desc std"> <?php //echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?> <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a> </div -->
          <div class="desc std"> <?php echo $_helper->productAttribute($_product, $_product->getGenericName() , 'generic_name'); ?></div>
        <div class="wrapper">
                 <div class="list-reviews" style="float:left;text-align: left;margin-bottom:5px;"> <?php  if($_product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_product) != "No"){ echo  "Manufactured by :".$_product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_product); } ?><?php //echo $this->getReviewsSummaryHtml($_product) ?> </div></div><br/>
				 <!--coded by nilesh-->
					<?php
						$childProducts = Mage::getModel('catalog/product_type_configurable')->getUsedProducts(null, $_product);
						$child = $childProducts[0];
						$pack_size = $child->getResource()->getAttribute('pack_size')->getFrontend()->getValue($child);
						if($pack_size != "NA" && !empty($pack_size))
						{
							echo '<p class="custom_price">';
								echo '<span class="custom_child_1">'.$child->getResource()->getAttribute('pack_size')->getFrontend()->getValue($child).'</span>';
								echo '<span class="custom_child_2"> '.$_product->getResource()->getAttribute('pharmaceutical_form')->getFrontend()->getValue($_product).'</span>';
								echo '<span class="custom_child_3"> - US$ '.number_format($child->getPrice(), 2, '.', '').'</span>';
							echo "</p>";
						}
					?>
					<!--end--->
				 <?php echo  "Equivalent to ".$_helper->productAttribute($_product, $_product->getUsBrandName(), 'us_brand_name');?> <br><?php //echo $this->getPriceHtml($_product, true) ?>
				 <p style="color:red;font-weight: bold;">
				 <?php 
				   if($_product->getBonus() != "")
				   {
						echo  "Double Pills Offer";
				   }
				   
				?>
				</p>
				 
				<?php /* if($cat_id == '59') {?>
					<div>
						<p style="color:red;">
							<?php
							 echo "Tadalafil is not for consumption in United States";
							?>
						</p>
					</div>
				<?php } */ ?>
				
		  <?php if($_product->isSaleable()): ?>
          <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
          <div class="row-list">
            <p class="list-btn">
              <!--button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button-->
              <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><button type="button" title="<?php echo $this->__('View Details') ?>" class="button btn-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('View Details') ?></span></span></button></a>
            </p>
            <span id='ajax_loader<?php echo $_product->getId()?>' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>
            <?php } else { ?>
            <!--button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button-->
			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><button type="button" title="<?php echo $this->__('View Details') ?>" class="button btn-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('View Details') ?></span></span></button></a>
			<span id='ajax_loader<?php echo $_product->getId()?>' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>
            <?php }  ?>
            <?php else: ?>
            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <p class="request-for-quote"><a href="<?php echo $this->getBaseUrl().'contacts/'.'?productid='.$_product->getId().'&queryid=1'?>"><?php echo $this->__('Request for Product') ?></a></p>
            <?php endif; //onclick='ajaxWishlist("echo $this->helper('wishlist')->getAddUrl($_product) "," echo $_product->getId()");return false;'?>
            <ul class="add-to-links">
              <?php if ($this->helper('wishlist')->isAllow()) : ?>
              <li><a href="/index.php/wishlist/index/add/product/<?php echo $_product->getId(); ?>" title="<?php echo $this->__('Add to Wishlist') ?>"  class="link-wishlist tooltips"><?php echo $this->__('Add to Wishlist') ?></a></li>
              <?php endif; ?>
			  <?php //onclick='ajaxCompare(" echo $_compareUrl "," echo $_product->getId()");return false;'?>
              <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
              <li><span class="separator">|</span> <a href="/index.php/catalog/product_compare/add/product/<?php echo $_product->getId()?>" title="<?php echo $this->__('Add to Compare') ?>"  class="link-compare tooltips"><?php echo $this->__('Add to Compare') ?></a>
                <div id="results"></div>
              </li>
              <?php endif; ?>
            </ul>
            <span id='ajax_loading<?php echo $_product->getId()?>' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>
     
          </div>
        </div>
        
    </li>
    <?php endforeach; ?>
  </ol>
  <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
  <?php else: ?>
  <?php // Grid Mode ?>
  <?php $_collectionSize = $_productCollection->count() ?>
  <?php $_columnCount = $this->getColumnCount(); 
  	$category_id = Mage::getModel('catalog/layer')->getCurrentCategory()->getId();
	//echo "ttt---".$category_id;exit;
  ?>
 
  <?php $i=0; foreach ($_productCollection as $_product):
	/*echo "<pre>";
	print_r($_product->getData());exit;*/
	//$attr = $model->getResource()->getAttribute("inkfruit_brand");
 	//$Brandid = $attr->getSource()->getOptionId($InkfruitBrand);
	
	//exit;
  //exit;
   ?>
   	<?php 
		$productName  = $_product->getName();
		$classNameIndex = strtolower($productName[0]);
	?>
  <?php if ($i++%$_columnCount==0): ?>
  <ul class="products-grid">
    <?php endif ?>
    <li class="item <?php if(($i-1)%$_columnCount==0): ?> first <?php elseif($i%$_columnCount==0): ?> last <?php endif; echo $classNameIndex;?>">
	        

      <div class="grid-inner"> <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img class="pr-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(203); ?>" width="203" height="203" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a> 
      <a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' data-fancybox-group="gallery" class='fancybox1' id='fancybox1<?php echo $_product->getId()?>' style=''><?php //echo $this->__('Quick View') ?></a></div>
      <h2 class="product-name product-name-height"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name')." ". $_helper->productAttribute($_product, $_product->getConfigurableAttribute() , 'configurable_attribute'); ?> <?php //if($_product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_product) != "No"){ echo  $_product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_product); }?></a></h2>
	        
      <div class="desc std"> 
		  <?php /* $small_description = strip_tags( $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'));
	           if (strlen($small_description) < '75') echo($small_description);
	         	else {
		          echo substr($small_description, 0, 80);
		          echo '...';
	         }*/
		  ?>
		  
		  <?php echo $_helper->productAttribute($_product, $_product->getGenericName(), 'generic_name'); ?><br>
		  
		  <?php  if($_product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_product) != "No"){ echo  "Manufactured by :".$_product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_product); } ?>
      </div>
	  <!--coded by nilesh-->
					<?php
					if($_product->getTypeId()=='configurable'){
						$childProducts = Mage::getModel('catalog/product_type_configurable')->getUsedProducts(null, $_product);
						$child = $childProducts[0];
						$pack_size = $child->getResource()->getAttribute('pack_size')->getFrontend()->getValue($child);
						if($pack_size != "NA" && !empty($pack_size))
						{
							echo '<p class="custom_price">';
								echo '<span class="custom_child_1">'.$child->getResource()->getAttribute('pack_size')->getFrontend()->getValue($child).'</span>';
								echo '<span class="custom_child_2"> '.$_product->getResource()->getAttribute('pharmaceutical_form')->getFrontend()->getValue($_product).'</span>';
								echo '<span class="custom_child_3"> - US$ '.number_format($child->getPrice(), 2, '.', '').'</span>';
							echo "</p>";
						}
					}
					?>
					<!--end -->
      <div class="product-box-2"> 
	     <div class="product-atr-height">
		 <?php  //if($_product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_product) != "No"){ echo  "Manufactured by :".$_product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_product); } ?>
		   <?php echo  "Equivalent US Brand - ". $_helper->productAttribute($_product, $_product->getUsBrandName(), 'us_brand_name');?><br>
		   <p style="color:red;font-weight: bold;">
				   <?php 
				   if($_product->getBonus() != "")
				   {
						echo  "Double Pills Offer";
				   }
				   ?>
		   </p>
			 <?php //echo $this->getPriceHtml($_product, true) ?> 
			 <?php //echo $this->getReviewsSummaryHtml($_product, 'short') ?>
         </div>
		 <?php /* if($category_id == '59') {?>
			<div>
				<p style="color:red;">
					<?php
					 echo "Tadalafil is not for consumption in United States";
					?>
				</p>
			</div>
		 <?php }  */?>
		 
		  <?php  $messagebox=trim($_helper->productAttribute($_product, $_product->getGenericName(), 'generic_name'));
				if(stripos($messagebox, "Tadalafil") !== false){
				echo '<p style="color:red;">Tadalafil is not for consumption in United States</p>';
				}   
		  
			?>
		 
        <div class="actions">
          <?php if($_product->isSaleable()): ?>
          <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
          <!--button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button-->
		  <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><button type="button" title="<?php echo $this->__('View Details') ?>" class="button btn-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('View Details') ?></span></span></button></a>
          <span id='ajax_loader<?php echo $_product->getId()?>' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span> 
          <a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox1' id='fancybox1<?php echo $_product->getId()?>' style=''></a>
          <?php } else { ?>
          <!--button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button -->
		  <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><button type="button" title="<?php echo $this->__('View Details') ?>" class="button btn-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('View Details') ?></span></span></button></a>
          <?php }  ?>
          <?php else: ?>
          <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
          <?php endif; //onclick='ajaxWishlist(" echo $this->helper('wishlist')->getAddUrl($_product) ","echo $_product->getId()");return false;'?>
          <ul class="add-to-links">
            <?php if ($this->helper('wishlist')->isAllow()) : ?>
            <li><a href="/index.php/wishlist/index/add/product/<?php echo $_product->getId(); ?>" title="<?php echo $this->__('Add to Wishlist') ?>"  class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
            <?php endif; ?>
			<?php //onclick='ajaxCompare(" echo $_compareUrl "," echo $_product->getId()");return false;'?>
            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
            <li><span class="separator">|</span> <a title="<?php echo $this->__('Add to Compare') ?>" href="/index.php/catalog/product_compare/add/product/<?php echo $_product->getId()?>"  class="link-compare"><?php echo $this->__('Add to Compare') ?></a>
              <div id="results"></div>
            </li>
            <?php endif; ?>
          </ul>
        </div>
        <span id='ajax_loading<?php echo $_product->getId()?>' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span> </div>
    </li>
    <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
  </ul>
  <?php endif ?>
  <?php endforeach ?>
  <script type="text/javascript">
  	//decorateGeneric($$('ul.products-grid'), ['odd','even','first','last']) 
  </script>
  <?php endif; ?>
  <div class="toolbar-bottom"> <?php echo $this->getToolbarHtml() ?> </div>
</div>
<?php endif; ?>

<!--<script type="text/javascript">

jQuery(document).ready(function() {
 var vmcartck = jQuery('.block-cart .block-content');
 //alert(vmcartck);
 vmcartck.top = vmcartck.offset().top();
 vmcartck.left = vmcartck.offset().left();
 jQuery('.btn-cart').click(function() {
   var el = jQuery(this);
   var imgtodrag = jQuery('.rwerwe:first');
   if (!imgtodrag.length) {
    elparent = el.parent();
    while (!elparent.hasClass('item')) {
     elparent = elparent.parent();
    } 
    imgtodrag = elparent.find('img.pr-img');
   }
   if (imgtodrag.length) {
    var imgclone = imgtodrag.clone()
     .offset({ top: imgtodrag.offset().top, left: imgtodrag.offset().left })

  .css({'opacity': '0.7', 'position': 'absolute' , 'height':'150px' , 'width': '150px','z-index': '1000'})
     .appendTo(jQuery('body'))
     .animate({
      'top': vmcartck.top-40,
      'left': vmcartck.left+40,
      'width':55,
      'height':55
     },1000, 'linear');
    imgclone.animate({
     'width': 0,
     'height': 0
    });
   }
 });  
 	var maxHeight = 0;
	function setHeight(column) {
		column = jQuery(column);
		column.each(function() {       
			if(jQuery(this).height() > maxHeight) {
				maxHeight = jQuery(this).height();;
			}
		});
		column.height(maxHeight);
	}
	setHeight('.product-name-height');
	setHeight('.product-atr-height');
	
});

</script>-->
<script type="text/javascript">
	jQuery.noConflict();
	jQuery(document).ready(function(){
		jQuery('.fancybox').fancybox(
			{
			   hideOnContentClick : true,
			   width:800,
			   autoDimensions: true,
               type : 'iframe',
			   showTitle: true,
			   scrolling: 'no',
			   onComplete: function(){
				jQuery('#fancybox-frame').load(function() { // wait for frame to load and then gets it's height
					jQuery('#fancybox-content').height(jQuery(this).contents().find('body').height()+30);
					jQuery.fancybox.resize();
				 });

			   }
			}
		);
	});
	function showOptions(id){
		jQuery('#fancybox'+id).trigger('click');
	}
	function setAjaxData(data,iframe){
		if(data.status == 'ERROR'){
			alert(data.message);
		}else{
			if(jQuery('.block-cart')){
	            jQuery('.block-cart').replaceWith(data.sidebar);
	        }
									if(jQuery('.block-cart-header')){
	            jQuery('.block-cart-header').replaceWith(data.sidebar_header);
	        }
	        if(jQuery('.header .links')){
	            jQuery('.header .links').replaceWith(data.toplink);
	        }


		}
	}
	function setLocationAjax(url,id){
		url += 'isAjax/1';
		url = url.replace("checkout/cart","ajax/index");
		jQuery('#ajax_loader'+id).show();
		try {
			jQuery.ajax( {
				url : url,
				dataType : 'json',
				success : function(data) {
					jQuery('#ajax_loader'+id).hide();
					if(data.status == 'ERROR'){
									jQuery('body').append('<div class="alert"></div>');
						jQuery('.alert').slideDown(400);
							jQuery('.alert').html(data.message).append('<button></button>');
				jQuery('button').click(function () {
                jQuery('.alert').slideUp(400);
                 });	
				 			jQuery('.block-cart-header .cart-content').hide();
			jQuery('.block-cart-header  .amount-2 a').hover(function(){
				jQuery('.block-cart-header .cart-content').stop(true, true).slideDown(400);
			},function(){
				jQuery('.block-cart-header .cart-content').stop(true, true).delay(400).slideUp(300);
			}); 
					jQuery('.alert').slideDown('400',function(){
									 	setTimeout(function(){
											jQuery('.alert').slideUp('400',function(){jQuery(this).slideUp(400)});
										},7000)
									 });
		}else{
			
						jQuery('body').append('<div class="alert" ></div>');
						jQuery('.alert').slideDown(400);
				jQuery('.alert').html(data.message).append('<button></button>');
				jQuery('button').click(function () {
                jQuery('.alert').slideUp(400);
                 });	
					jQuery('.alert').slideDown('400',function(){
									 	setTimeout(function(){
											jQuery('.alert').slideUp('400',function(){jQuery(this).slideUp(400)});
										},7000)
									 });
									 			jQuery('.block-cart-header .cart-content').hide();
			jQuery('.block-cart-header  .amount-2 a').hover(function(){
				jQuery('.block-cart-header .cart-content').stop(true, true).slideDown(400);
			},function(){
				jQuery('.block-cart-header .cart-content').stop(true, true).delay(400).slideUp(300);
			}); 
			if(jQuery('.block-cart')){
	            jQuery('.block-cart').replaceWith(data.sidebar);
	        }
						if(jQuery('.block-cart-header')){
	            jQuery('.block-cart-header').replaceWith(data.sidebar_header);
	        }
	        if(jQuery('.header .links')){
	            jQuery('.header .links').replaceWith(data.toplink);
	        }

		}
         	      
				}
			});
		} catch (e) {
		}
	}
	jQuery(".add-to-links li a.tooltips").easyTooltip();
		jQuery(".products-grid .add-to-links .link-wishlist").easyTooltip();
		jQuery(".products-grid .add-to-links .link-compare ").easyTooltip();
		
		
		
</script>
