<div class="trustedcompany-widget">
  <iframe id="trustedcompany-widget" width="100%" height="114" frameborder="0" scrolling="no"></iframe>
  <a href="http://trustedcompany.com/us/alldaychemist.com-reviews" target="_blank" title="Alldaychemist Reviews"></a>
  <script>(function(){document.getElementById('trustedcompany-widget').src='//trustedcompany.com/embed/widget/v2?domain=alldaychemist.com&type=d&review=1&text=a';})();</script>
</div>

<?php 
	/* system configuration is defined in Manoj_Abondent Model */
	$univesalBannerStatus = Mage::getStoreConfig('general/categorybanner/categorybanner_status');
	$univesalBannerImage = Mage::getStoreConfig('general/categorybanner/logo');
?>

<div class="category_banner">
	<?php
		
		/* Universal Banner for Category Page*/
		if($univesalBannerStatus==1){
			if($univesalBannerImage!=""){
				$category_banner = Mage::getBaseUrl('media').'theme/'.$univesalBannerImage;
				$bannerHtml = '<img src="'.$category_banner.'" />';				
			}
		}

		/* Category Banner(Thumbnail Image) for Category Page*/
		if(Mage::registry('current_category')){
				$category = Mage::registry('current_category');
				$thumbnail_image = $category->getThumbnail();
				if($thumbnail_image!=""){
					$category_banner = Mage::getBaseUrl('media').'catalog/category/'.$thumbnail_image;
					$bannerHtml = '<img src="'.$category_banner.'" />';	
			}
		}

		echo $bannerHtml;
	?>
</div>
<style>
.category_banner{
	margin-bottom: 30px;
}
</style>