<?php
$results=$this->getSuggestProducts();
$suggests=Mage::helper('catalogsearch')->getSuggestCollection();//->addFieldToFilter('status', array('eq'=>1))->getSelect();

$flag = 0;
?>
<ul class="ajaxsearch" ><li style="display:none"></li>
<?php
if($this->enabledSuggest())
{  
	//code commeted
	/*foreach($suggests as $_suggest)
	{
	  $flag = 1;
	  echo "<li class=\"suggest\" >{$_suggest->getQueryText()} <span class=\"amount\">{$_suggest->getNumResults()}</span></li>";
	}
	*/
}
$q = Mage::app()->getRequest()->getParam('q');
if($results->count()&&$this->enabledPreview())
{

  foreach($results as $_pro)
  {
    $flag = 1;
    $pro=Mage::getModel('catalog/product')->load($_pro->getId());
	if($pro->getStatus()==1)
	{
    echo "<li class=\"preview\" ><a href=\"{$pro->getProductUrl()}\">";
    if($this->isShowImage())
    {
    echo "<img src=\"{$this->helper('catalog/image')->init($pro, 'small_image')->resize($this->getImageWidth(),$this->getImageHeight())}\"  />";
    }
    if($this->isShowName())
    {
	  //$st = strpos($pro->getName(),$q);
	  $name = "/\b(".$q.".+?)\b/i";
	  preg_match($name,$pro->getName(),$matches1);
	  //echo "----".strtolower($pro->getName())."----".$matches1[1];
	  if($matches1[1] != NULL || strtolower($pro->getName()) == strtolower($q))
	   {
		echo "{$pro->getName()}"." ".$pro->getConfigurableAttribute();
		//echo "{$pro->getName()}";
	  }
	  else
	  {
	    $name = "/\b(".$q.".+?)\b/i";
		preg_match($name,$pro->getUsBrandName(),$matches2);
	    if($matches2[1] != NULL || strtolower($pro->getUsBrandName()) == strtolower($q))
		{
			echo "{$pro->getUsBrandName()}"." ".$pro->getConfigurableAttribute();
			//echo "{$pro->getUsBrandName()}";
		}
		else
		{
			echo "{$pro->getGenericName()}"." ".$pro->getConfigurableAttribute();
			//echo "{$pro->getGenericName()}";
		}
	  }
	}

 
    if($this->isShowDescription())
    {
        $description=substr($pro->getDescription(),0,$this->getNumDescriptionChar());
        $description=strip_tags(substr($description,0,strrpos($description,' ')));
        echo "<div class=\"description\">$description...</div>";
    }
    echo "</a></li>";
	}
  }
}
    if($flag == 0){
	echo "<a href='#'><li style='cursor: default;'>No data found</li></a>";
	}
		 
  
?>
</ul>
<style>
.ajaxsearch{border:solid <?php echo $this->getBorderColor().' '.$this->getBorderWidth().'px';?>}
.ajaxsearch .suggest{background:<?php echo $this->getSuggestBackground();?>; color:<?php echo $this->getSuggestColor();?>}
.ajaxsearch .suggest .amount{color:<?php echo $this->getSuggestCountColor();?>}
.ajaxsearch .preview {background:<?php echo $this->getPreviewBackground();?>}
.ajaxsearch .preview a {color:<?php echo $this->getProductNameColor();?>}
.ajaxsearch .preview .description {color:<?php echo $this->getProductDescriptionColor();?>}
.ajaxsearch .preview img {border:solid <?php echo $this->getImageBorderWidth().'px '.$this->getImageBorderColor();?> }
.header .form-search .ajaxsearch li.selected {background-color:<?php echo $this->getHoverBackground();?>}
</style>
