<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php 
// $_outofstockHelper = Mage::helper('notifyoutofstock');
// if(!$_product->isSaleable()){
//     $_outofstockHelper->notifyOutofStock($_product);
// }
$arrParams = Mage::app()->getRequest()->getParams();

?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">

    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="img_gal_area">
	        <div class="product-img-box">
	            <?php echo $this->getChildHtml('media') ?>
	        </div>
    	</div>

        <div class="product-shop">
            <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h1>
            </div>
            <?php if (trim($_product->getShortDescription())):?>
                <div class="short-description" style="max-height:236px;overflow:auto;">
                    <h2><?php echo $this->__('Quick Overview') ?></h2>
                    <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                </div>
            <?php endif;?>
            
      
            <?php echo $this->getChildHtml('alert_urls') ?>
            <?php 
                $custom_stock_status = $_product->getResource()->getAttribute('custom_stock_status')
                ->getFrontend()->getValue($_product);
                if($custom_stock_status!='No' && $custom_stock_status!=''){
                    // echo '<p class="red_text">';
                    // echo $this->__('Availability : ');
                    // echo '<span>';
                    // echo $this->__($custom_stock_staus);
                    // echo '</span></p>';
                }
                else{  
                    echo $this->getChildHtml('product_type_data');
                } 
            ?>
            <?php echo $this->getTierPriceHtml() ?>
            <?php echo $this->getChildHtml('extrahint') ?>

            <?php if (!$this->hasOptions()):?>
                <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                            <span class="or"><?php echo $this->__('OR') ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
                <?php echo $this->getChildHtml('extra_buttons') ?>
            <?php endif; ?>
    
            <?php echo $this->getChildHtml('other');?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>  
			<div class="row-product">
			<?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
            
			<?php if ($this->canEmailToFriend()): ?>
                <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
            <?php endif; ?>

        </div>
                <div class="share bordercolor"><!-- AddThis Button BEGIN -->
			<div class="addthis_toolbox addthis_default_style ">
				<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
				<a class="addthis_button_tweet"></a>
				<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
				<a class="addthis_counter addthis_pill_style"></a>
			</div>
			<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4f419f410efe76d3"></script>
		</div>

        <?php  if($custom_stock_status!='No' && $custom_stock_status!=''):?>
            <h1 class="red_text bold_text padding_top10">This Product has been Discontinued</h1>
        <?php else:?>
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>         
            <?php endif;?>
        <?php endif;?>
        </div>             

    <div class="clearer"></div>
        
    </form>
    <script type="text/javascript">
	jQuery(function($){
		$('#addtocart').click(function(){
		     var val = $('#attribute140').val();
			 var qty = $('#qty').val();
			 var n=val.split("-");
			 var update = '<?php echo $arrParams['update'];?>';
			 var id = '<?php echo $arrParams['id'];?>';
			 //return;
			 if(val != "")
			 {
			    if(update != "")
				 {
				    $(this).closest("form").submit();					
				 }
				 else
				 {
				
					window.location.href='/checkout/cart/add/product/'+n[1]+'/?super_attribute[140]='+n[0]+'&qty='+qty+'&mainid='+id;
     			  }

			 }
			 else
			 {
				alert("Please select the Pack size!");
			 }
			
		});
});   

    </script>
    </div>
    <?php echo $this->getChildHtml('bought.product.wrapper'); ?>
    
    <?php //echo $this->getChildHtml('long_description');?>

    <div class="product-collateral">
<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
        <div class="box-collateral <?php echo "box-{$alias}"?>">
            <?php if ($title = $this->getChildData($alias, 'title')):?>
            <h2><?php echo $this->escapeHtml($title); ?></h2>
            <?php endif;?>
            <?php echo $html; ?>
        </div>
<?php endforeach;?>
       
        <?php echo $this->getChildHtml('product_additional_data') ?>
         <?php $attStuff= $_product->getData(); ?>
  		<?php if( !empty( $attStuff['videoid'] ) ): ?>        
		<div class="video">
			 <p><span>Video review of:</span> Lorem ipsum dolor sit amet conse ctetur adipisicing elit</p>
			 <iframe src="<?php echo $attStuff['videoid']; ?>" frameborder="0" allowfullscreen></iframe>
		</div>
		<?php endif; ?>
         
    </div>
</div><?php echo $this->getChildHtml('upsell_products') ?>
