<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php

$arrParams = Mage::app()->getRequest()->getParams();
$custom_stock_status = $_product->getResource()->getAttribute('custom_stock_status')
                ->getFrontend()->getValue($_product);
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">

    <div class="product-essential">

    <?php if($_product->stock_item->is_in_stock == 1) { ?>
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <?php } ?>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="img_gal_area">
            <div class="product-img-box">
                <?php echo $this->getChildHtml('media') ?>
            </div>
        </div>

        <div class="product-shop">
            <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h1>
            </div>
            <?php if (trim($_product->getShortDescription())):?>
                <div class="short-description" style="max-height:236px;overflow:auto;">
                    <h2><?php echo $this->__('Quick Overview') ?></h2>
                    <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                </div>
            <?php endif;?>


            <?php echo $this->getChildHtml('alert_urls') ?>
            <?php
                 
                if($custom_stock_status!='No' && $custom_stock_status!=''){
                    echo '<p class="availability out-of-stock">';
                    echo $this->__('Availability : ');
                    echo '<span>';
                    echo $this->__($custom_stock_status);
                    echo '</span></p>';
                }
                else{
                    echo $this->getChildHtml('product_type_data');
                }
            ?>
            <?php echo $this->getTierPriceHtml() ?>
            <?php echo $this->getChildHtml('extrahint') ?>

            <?php if (!$this->hasOptions()):?>
                <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                        <?php //echo $this->getChildHtml('addtocart') ?>
                        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                            <span class="or"><?php echo $this->__('OR') ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php //echo $this->getChildHtml('addto') ?>
                </div>
                <?php echo $this->getChildHtml('extra_buttons') ?>
            <?php endif; ?>

            <?php echo $this->getChildHtml('other');?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>
            <div class="row-product">
            <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>

            <?php if ($this->canEmailToFriend()): ?>
                <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
            <?php endif; ?>

        </div>
        <div class="share bordercolor"><!-- AddThis Button BEGIN -->
            <div class="addthis_toolbox addthis_default_style ">
                <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
                <a class="addthis_button_tweet"></a>
                <a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
                <a class="addthis_counter addthis_pill_style"></a>
            </div>
            <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4f419f410efe76d3"></script>
        </div>
        <?php if($_product->isSaleable()): ?>
            <?php echo $this->getChildHtml('addtocart') ?>
            <?php echo $this->getChildHtml('addto') ?>
        <?php endif; ?>

        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
    </div>


    <?php
        $configValue = Mage::getStoreConfig('outofstocksubscription/mail/active');
    ?>

     <?php if(!$_product->stock_item->is_in_stock == 1 && $configValue == '1' && ($custom_stock_status=='No' || $custom_stock_status=='')): ?>
        <div class="product-options">
            <form  method="post" id="userform" name="userform">
              <fieldset>
                <ul>
                 <li>
                <div class="notify_alert">
                    <div class="notify_heading">Out of Stock!</div>
                    <div class="notify_text"><?php echo $this->__('This item is Out of Stock') ?></div>
                </div>
                    <div class="subscription_text"><?php echo $this->__("Notify me when this product is in stock") ?></div>
                    <div class="notify_tab">
                        <label class="email_label">Email:</label>
                        <input type="email" id="subscription_email" name="subscription_email" placeholder="Please enter your Email Id" class="email input-text required-entry validate-email">
                    </div>
                    <div class="notify_tab2">
                        <input id="notify_submit" class="btn-cart" type="submit" value="NOTIFY ME" />
                    </div>
                    <div class="invalid_email"></div>
                 </li>
                 <li>
                    <input type="hidden" id="product_sku" name="product_sku" value="<?php echo $_product->getSku(); ?>">
                    <input type="hidden" id="product_name" name="product_name" value="<?php echo $_product->getName(); ?>">
                    <input type="hidden" id="product_status" name="product_status" value="<?php echo $_product->getData('custom_stock_status'); ?>">
                    <input type="hidden" id="product_url" name="product_url" value="<?php echo $_product->getData('url_path'); ?>">
                </li>
              </ul>
             </fieldset>
        </form>
        </div>
    <?php endif; ?>

    <div class="clearer"></div>
    <?php if($_product->stock_item->is_in_stock == 1) { ?>
    </form>
    <?php } ?>
    <script type="text/javascript">
    jQuery(function($){
        $('#addtocart').click(function(){
             var val = $('#attribute140').val();
             var qty = $('#qty').val();
             var n=val.split("-");
             var update = '<?php echo $arrParams['update'];?>';
             var id = '<?php echo $arrParams['id'];?>';
             //return;
             if(val != "")
             {
                if(update != "")
                 {
                    $(this).closest("form").submit();
                 }
                 else
                 {

                    window.location.href='/checkout/cart/add/product/'+n[1]+'/?super_attribute[140]='+n[0]+'&qty='+qty+'&mainid='+id;
                  }

             }
             else
             {
                alert("Please select the Pack size!");
             }

        });
});

    </script>
    </div>
    <?php echo $this->getChildHtml('bought.product.wrapper'); ?>

    <?php //echo $this->getChildHtml('long_description');?>

    <!-- <div id="blanket" style="display:none;"></div>
    <div id="popUpDiv" style="display:none;">
        <a href="#" id="closeLink" >Click to Close CSS Pop Up</a>
        <?php //echo $this->getLayout()->createBlock('review/form')->setTemplate('review/reviewform.phtml')->toHtml(); ?>
    </div> -->


    <div class="product-collateral">
<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
        <div class="box-collateral <?php echo "box-{$alias}"?>">
            <?php if ($title = $this->getChildData($alias, 'title')):?>
            <h2><?php echo $this->escapeHtml($title); ?></h2>
            <?php endif;?>
            <?php echo $html; ?>
        </div>
<?php endforeach;?>

        <?php echo $this->getChildHtml('product_additional_data') ?>
         <?php $attStuff= $_product->getData(); ?>
        <?php if( !empty( $attStuff['videoid'] ) ): ?>
        <div class="video">
             <p><span>Video review of:</span> Lorem ipsum dolor sit amet conse ctetur adipisicing elit</p>
             <iframe src="<?php echo $attStuff['videoid']; ?>" frameborder="0" allowfullscreen></iframe>
        </div>
        <?php endif; ?>

    </div>
    <div class="customer_rating"><?php
        echo $this->getChildHtml('review_form');
        //echo $this->getReviewsSummaryHtml($_product, false, true);
    // echo $this->getChildHtml('product_additional_data_reviews');
    // echo $this->getLayout()->createBlock('core/template')->setTemplate('review/form.phtml')->toHtml();
        ?></div>

         <?php
            echo $this->getLayout()->createBlock('frontend/index')->setTemplate('trustedcompany/review.phtml')->toHtml();
        ?>
        </div><?php echo $this->getChildHtml('upsell_products') ?>
        <div class="customer_review" style="overflow:hidden;width:70%;">
            <?php echo $this->getChildHtml('product_additional_data_reviews') ?>
        </div>



<script type="text/javascript">

     //< ![CDATA[
        var customForm = new VarienForm('userform',true);
    //]]>

    jQuery(document).ready(function($) {

        $('#notify_submit').click(function(e) {
            if(customForm.validator.validate()){
                e.preventDefault();
                var subscription_email = $("#subscription_email").val();
                var product_sku = $("#product_sku").val();
                var product_name = $("#product_name").val();
                var product_status = $("#product_status").val();
                var product_url = $("#product_url").val();

                var email = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;


                 if(subscription_email=="") {
                    // $( "div.invalid_email" ).replaceWith( '<div class="invalid_email">Insert Email Id</div>' );
                    // alert("Please Enter your email_id");
                    return false;
                } else if (!email.test(subscription_email)) {
                    // $( "div.invalid_email" ).replaceWith( '<div class="invalid_email">Invalid Email Id</div>' );
                   // alert("Invalid email id");
                   return false;
                }

                jQuery.ajax({
                    url: "<?php echo Mage::getUrl('outofstocksubscription/index/index') ?>",
                    type: "POST",
                    data: {"subscription_email":subscription_email,"product_sku":product_sku,"product_name":product_name,"product_status":product_status,"product_url":product_url},
                    beforeSend : function (){
                        //alert('test');
                    },
                    success: function(data) {
                        // alert(data);
                        // jQuery( 'div.invalid_email' ).html( 'Thank you, for your interest. You will be Notified by Email when it becomes available' );
                        jQuery( "div.invalid_email" ).replaceWith( '<div class="invalid_email">Thank you, for your interest. You will be Notified by Email when it becomes available.</div>' );
                        jQuery(".subscription_text").hide();
                        jQuery(".notify_tab").hide();
                        jQuery(".notify_tab2").hide();
                    }
                });
            }
        });
    });
</script>


    <div class="popup-wrapper">
        <div class="popup-content">
            <?php echo $this->getLayout()->createBlock('review/form')->setTemplate('review/reviewform.phtml')->toHtml(); ?>
            <div class="close-btn">X</div>
        </div>
    </div>
