<?php $catalogSearchHelper =  $this->helper('catalogsearch');?>
<form id="search_sidebar_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
    <?php 
    //$topSearchHelper = $this->helper('custommodule/data');
    //$collection = $topSearchHelper->topSearchResult();
    ?>
    <div class="header-form-search">
        <select id="dropdown1"> 
            <option value="Us">Equivalent Brands</option>
            <?php /*$i=0;
            foreach ($collection as $product) {         
                if($product['us_brand_name'] != 'Latisse'){ ?>
                <option class="header-brand-dropdown-option" value="<?php echo $this->__($product['us_brand_name']); ?>"><?php echo $this->__($product['us_brand_name']); ?></option> 
                <?php }} */?>
            </select> 

            <input id="searchtext" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText(); ?>" />
            <button type="submit" title="<?php echo $this->__('Search') ?>" ><img src="<?php echo $this->getSkinUrl('images/optimized/search-icon-white-one-md.png') ?>" alt="Search Button"/></button>
        </div>
        <div id="search_autocomplete" class="search-autocomplete" style="display: none;"></div>
    </form>
    <script type="text/javascript">
        jQuery("#searchtext").keyup(function (event) {
            
            if(event.which==13) {
                //console.log(jQuery("#search_autocomplete .ajaxsearch .selected a"));
                if(jQuery("#search_autocomplete .ajaxsearch .selected a").attr("href")!=undefined) {
                    window.location.href = jQuery("#search_autocomplete .ajaxsearch .selected a").attr("href");
                    event.preventDefault();
                }
            }
        });
        if(jQuery(location).attr('protocol')=="https:"){
            var url="<?php echo $this->getUrl('custommodule/index/topsearchresult', array('_secure'=>true)) ?>";
        }else{
            var url="<?php echo $this->getUrl('custommodule/index/topsearchresult') ?>";
            //var url="http://www.reliablerxpharmacy.com/";
        }

    });
    </script>

    <script type="text/javascript">
//<![CDATA[
var searchForm = new Varien.searchForm('search_sidebar_form', 'searchtext', '<?php echo $this->__('Search entire store here...') ?>');
searchForm.initAutocomplete('<?php echo $this->helper('searchautocomplete')->getSuggestUrl() ?>', 'search_autocomplete');
//]]>
</script>