<div class="frequently_bought_wrap">
<h2 class="page_head">Related Products</h2>
   <div class="slider_wraper">
<div class="item_wrap">
          <div class="item">
             <a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/" title="Adaferin Gel  - 0.1% (15gm)" class="product-image"><img class="lazy" src="http://192.168.1.218/allday/media/catalog/product/cache/1/small_image/100x/1023a0599857fc1de187ac9c9d2aa57d/images/catalog/product/placeholder/small_image.jpg" width="" height="" alt="Adaferin Gel  - 0.1% (15gm)" style="display: inline;"></a>
             <div class="pr-details-height">
                <h2 class="product-name"><a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/" title="Adaferin Gel  - 0.1% (15gm)">Adaferin Gel  - 0.1% (15gm)</a></h2>
                <div class="generic_name">
                   Adapalene                        
                </div>
                <div class="generic_for">
                   Generic for Differin                         
                </div>
                <div class="manufactured_by">
                   Manufactured by : Galderma, France                
                </div>
                <div class="first_child_info">
                   <div class="custom_price">
                       <span class="pack_size">1 Tube</span>
                       <span class="regular_price"> US$ 7.82</span>
                    </div>
                </div>
                <div class="ratings">
                   <div class="rating-box">
                      <a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/#customer-reviews">
                         <div class="rating" style="width:56%"></div>
                      </a>
                   </div>
                   <span class="amount"><a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/#customer-reviews">11 Review(s)</a></span>
                </div>
             </div>
             <div class="actions">
                <ul class="add-to-links">
                   <li><a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/" class="link-wishlist">Add to Wishlist</a></li>
                   <li class="link-compare-li"><span class="separator">|</span> <a href="http://192.168.1.218/allday/catalog/product_compare/add/product/7/uenc/aHR0cDovLzE5Mi4xNjguMS4yMTgvYWxsZGF5L2FjbmUuaHRtbA,,/form_key/LST3W6QFpPL78Vbq/" class="link-compare">Compare</a></li>
                </ul>
                <button type="button" title="View Details" class="button btn-cart" onclick="setLocation('http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/')"><span><span>View Details</span></span></button>
             </div>
          </div>
        </div>
        <div class="item_wrap">
          <div class="item">
             <a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/" title="Adaferin Gel  - 0.1% (15gm)" class="product-image"><img class="lazy" src="http://192.168.1.218/allday/media/catalog/product/cache/1/small_image/100x/1023a0599857fc1de187ac9c9d2aa57d/images/catalog/product/placeholder/small_image.jpg" width="" height="" alt="Adaferin Gel  - 0.1% (15gm)" style="display: inline;"></a>
             <div class="pr-details-height">
                <h2 class="product-name"><a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/" title="Adaferin Gel  - 0.1% (15gm)">Adaferin Gel  - 0.1% (15gm)</a></h2>
                <div class="generic_name">
                   Adapalene                        
                </div>
                <div class="generic_for">
                   Generic for Differin                         
                </div>
                <div class="manufactured_by">
                   Manufactured by : Galderma, France                
                </div>
                <div class="first_child_info">
                   <div class="custom_price">
                       <span class="pack_size">1 Tube</span>
                       <span class="old_price"> - US$ 7.82</span>
                       <!-- <span class="regular_price"> US$ 7.82</span> -->
                       <span class="special_price"> US$ 7.82</span>
                    </div>
                </div>
                <div class="ratings">
                   <div class="rating-box">
                      <a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/#customer-reviews">
                         <div class="rating" style="width:56%"></div>
                      </a>
                   </div>
                   <span class="amount"><a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/#customer-reviews">11 Review(s)</a></span>
                </div>
             </div>
             <div class="actions">
                <ul class="add-to-links">
                   <li><a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/" class="link-wishlist">Add to Wishlist</a></li>
                   <li class="link-compare-li"><span class="separator">|</span> <a href="http://192.168.1.218/allday/catalog/product_compare/add/product/7/uenc/aHR0cDovLzE5Mi4xNjguMS4yMTgvYWxsZGF5L2FjbmUuaHRtbA,,/form_key/LST3W6QFpPL78Vbq/" class="link-compare">Compare</a></li>
                </ul>
                <button type="button" title="View Details" class="button btn-cart" onclick="setLocation('http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/')"><span><span>View Details</span></span></button>
             </div>
          </div>
        </div>
        <div class="item_wrap">
          <div class="item">
             <a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/" title="Adaferin Gel  - 0.1% (15gm)" class="product-image"><img class="lazy" src="http://192.168.1.218/allday/media/catalog/product/cache/1/small_image/100x/1023a0599857fc1de187ac9c9d2aa57d/images/catalog/product/placeholder/small_image.jpg" width="" height="" alt="Adaferin Gel  - 0.1% (15gm)" style="display: inline;"></a>
             <div class="pr-details-height">
                <h2 class="product-name"><a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/" title="Adaferin Gel  - 0.1% (15gm)">Adaferin Gel  - 0.1% (15gm)</a></h2>
                <div class="generic_name">
                   Adapalene                        
                </div>
                <div class="generic_for">
                   Generic for Differin                         
                </div>
                <div class="manufactured_by">
                   Manufactured by : Galderma, France                
                </div>
                <div class="first_child_info">
                   <div class="custom_price">
                       <span class="pack_size">1 Tube</span>
                       <span class="old_price"> - US$ 7.82</span>
                       <!-- <span class="regular_price"> US$ 7.82</span> -->
                       <span class="special_price"> US$ 7.82</span>
                    </div>
                </div>
                <div class="ratings">
                   <div class="rating-box">
                      <a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/#customer-reviews">
                         <div class="rating" style="width:56%"></div>
                      </a>
                   </div>
                   <span class="amount"><a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/#customer-reviews">11 Review(s)</a></span>
                </div>
             </div>
             <div class="actions">
                <ul class="add-to-links">
                   <li><a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/" class="link-wishlist">Add to Wishlist</a></li>
                   <li class="link-compare-li"><span class="separator">|</span> <a href="http://192.168.1.218/allday/catalog/product_compare/add/product/7/uenc/aHR0cDovLzE5Mi4xNjguMS4yMTgvYWxsZGF5L2FjbmUuaHRtbA,,/form_key/LST3W6QFpPL78Vbq/" class="link-compare">Compare</a></li>
                </ul>
                <button type="button" title="View Details" class="button btn-cart" onclick="setLocation('http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/')"><span><span>View Details</span></span></button>
             </div>
          </div>
        </div>
        <div class="item_wrap">
          <div class="item">
             <a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/" title="Adaferin Gel  - 0.1% (15gm)" class="product-image"><img class="lazy" src="http://192.168.1.218/allday/media/catalog/product/cache/1/small_image/100x/1023a0599857fc1de187ac9c9d2aa57d/images/catalog/product/placeholder/small_image.jpg" width="" height="" alt="Adaferin Gel  - 0.1% (15gm)" style="display: inline;"></a>
             <div class="pr-details-height">
                <h2 class="product-name"><a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/" title="Adaferin Gel  - 0.1% (15gm)">Adaferin Gel  - 0.1% (15gm)</a></h2>
                <div class="generic_name">
                   Adapalene                        
                </div>
                <div class="generic_for">
                   Generic for Differin                         
                </div>
                <div class="manufactured_by">
                   Manufactured by : Galderma, France                
                </div>
                <div class="first_child_info">
                   <div class="custom_price">
                       <span class="pack_size">1 Tube</span>
                       <span class="regular_price"> US$ 7.82</span>
                    </div>
                </div>
                <div class="ratings">
                   <div class="rating-box">
                      <a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/#customer-reviews">
                         <div class="rating" style="width:56%"></div>
                      </a>
                   </div>
                   <span class="amount"><a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/#customer-reviews">11 Review(s)</a></span>
                </div>
             </div>
             <div class="actions">
                <ul class="add-to-links">
                   <li><a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/" class="link-wishlist">Add to Wishlist</a></li>
                   <li class="link-compare-li"><span class="separator">|</span> <a href="http://192.168.1.218/allday/catalog/product_compare/add/product/7/uenc/aHR0cDovLzE5Mi4xNjguMS4yMTgvYWxsZGF5L2FjbmUuaHRtbA,,/form_key/LST3W6QFpPL78Vbq/" class="link-compare">Compare</a></li>
                </ul>
                <button type="button" title="View Details" class="button btn-cart" onclick="setLocation('http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/')"><span><span>View Details</span></span></button>
             </div>
          </div>
        </div>
        <div class="item_wrap">
          <div class="item">
             <a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/" title="Adaferin Gel  - 0.1% (15gm)" class="product-image"><img class="lazy" src="http://192.168.1.218/allday/media/catalog/product/cache/1/small_image/100x/1023a0599857fc1de187ac9c9d2aa57d/images/catalog/product/placeholder/small_image.jpg" width="" height="" alt="Adaferin Gel  - 0.1% (15gm)" style="display: inline;"></a>
             <div class="pr-details-height">
                <h2 class="product-name"><a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/" title="Adaferin Gel  - 0.1% (15gm)">Adaferin Gel  - 0.1% (15gm)</a></h2>
                <div class="generic_name">
                   Adapalene                        
                </div>
                <div class="generic_for">
                   Generic for Differin                         
                </div>
                <div class="manufactured_by">
                   Manufactured by : Galderma, France                
                </div>
                <div class="first_child_info">
                   <div class="custom_price">
                       <span class="pack_size">1 Tube</span>
                       <span class="old_price"> - US$ 7.82</span>
                       <!-- <span class="regular_price"> US$ 7.82</span> -->
                       <span class="special_price"> US$ 7.82</span>
                    </div>
                </div>
                <div class="ratings">
                   <div class="rating-box">
                      <a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/#customer-reviews">
                         <div class="rating" style="width:56%"></div>
                      </a>
                   </div>
                   <span class="amount"><a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/#customer-reviews">11 Review(s)</a></span>
                </div>
             </div>
             <div class="actions">
                <ul class="add-to-links">
                   <li><a href="http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/" class="link-wishlist">Add to Wishlist</a></li>
                   <li class="link-compare-li"><span class="separator">|</span> <a href="http://192.168.1.218/allday/catalog/product_compare/add/product/7/uenc/aHR0cDovLzE5Mi4xNjguMS4yMTgvYWxsZGF5L2FjbmUuaHRtbA,,/form_key/LST3W6QFpPL78Vbq/" class="link-compare">Compare</a></li>
                </ul>
                <button type="button" title="View Details" class="button btn-cart" onclick="setLocation('http://192.168.1.218/allday/catalog/product/view/id/7/s/adaferin-gel/category/13/')"><span><span>View Details</span></span></button>
             </div>
          </div>
        </div>

      
   </div>
</div>