<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div class="entry-edit box-left" style="margin-right:10px;">
    <div class="entry-edit-head">
        <h4 class="icon-head"><?php echo Mage::helper('rewardpoints')->__('Agent Information') ?></h4>
     </div>
     <fieldset class="np">
         <div class="content">
            <div id="main">
                <div class="hor-scroll">
                    <table cellspacing="0">
                        <tbody>
                            <tr>
                                <td>
                                    <label for="agent_name">Order Placed By<span class="required">*</span></label>
                                </td>
                                <td style="padding-left: 30px;">
                                    <input id="agent_name" name="agent_name" value="" class="input-text required-entry" type="text">
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </fieldset>
</div>
