<div class="my-account">
<?php
    if(Mage::getStoreConfig('trackorder/trackorder_general/enabled')):
    ?>
    <div class="page-title"><h1><?php echo $this->__('Track Your Order ') ?></h1></div>
    <div class="form-list">
        <form name="track_order" id="track_order" action="" method="post" onsubmit="sendAjax('track_order','<?php  echo Mage::getUrl('*/*/track');?>'); return">
        <!--<form name="track_order" method="post" id="track_order" action="<?php echo Mage::getUrl('*/*/view');?>">-->
            <ul class="form-list">
                <li>
                    <label for="order_id" class="required"><em>*</em><?php echo $this->__('Order Id') ?></label>
                    <div class="input-box">
                        <input type="text" name="order_id" id="order_id" value="" title="" class="input-text required-entry" />
                    </div>    
                </li>
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box" >
                        <input type="text" name="email" id="email_address" value="" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>    
                </li>
                <!-- google recaptcha -->
                        <?php if($this->helper('recaptcha')->showOnTrackOrder()){?>
                           <!-- <li id="rcode">  
                                    <div class="captcha">
                                            <div class="g-recaptcha" data-sitekey="<?php echo $this->helper('recaptcha')->getKey(); ?>" data-theme="<?php echo ($this->helper('recaptcha')->getTheme()); ?>"> </div>
                                    </div>
                                    <span id="captcha-required" style='display:none; color:#ff0000'><?php echo $this->__('Please Fill Recaptcha To Continue'); ?></span>
                            </li>  -->
                             <div id="recaptchatrackorder"></div>
                            <span id="captcha-required" style='display:none; color:#ff0000'><?php echo $this->__('Please Fill Recaptcha To Continue'); ?></span>
                             <input type="hidden" id="qt_hiddenRecaptcha_trackorder"/>
                        <?php } ?>
                    <!-- google recpatcha -->
            </ul>
            <div class="buttons-set">
               <button type="submit" class="button" title="<?php echo $this->__('Track Order') ?>" name="track" id="track">
                    <span><span><?php echo $this->__('Track Order') ?></span></span>
                </button>
            </div>

        </form>
        <div id="loading-details" class="loading-details" style="display:none">
            <div id="loading-mask" >
                <p class="loader" id="loading_mask_loader"><img src="<?php echo $this->getSkinUrl('trackorder/images/ajax-loader-tr.gif') ?>" alt="<?php echo Mage::helper('adminhtml')->__('Loading...') ?>"/><br/><?php echo $this->__('Please wait...') ?></p>
            </div>
        </div>
    </div> 



    <div id="oderinfo" class="order-info-message"></div>


    <script type="text/javascript">
      var onloadCallbacktrackorder = function() {
           widgetId5 = grecaptcha.render('recaptchatrackorder', {
              'sitekey' : '<?php echo $this->helper('recaptcha')->getKey(); ?>',
              'theme' : '<?php echo $this->helper('recaptcha')->getTheme();?>',
              'callback' : correctCaptcha_quoteontrackorder,
            });
      };
      var correctCaptcha_quoteontrackorder = function(response) {
        document.getElementById("qt_hiddenRecaptcha_trackorder").value = response;
    };
</script>
    <script type="text/javascript">
        var validateForm = new VarienForm('track_order', true);
    </script>           
    <script type="text/javascript">

        function sendAjax(frmId,url){
            if (!validateForm.validator.validate()) {
                return;
            }

            validateRecaptcha();

            var data = $(frmId).serialize(this);
            $("loading-details").show();
            
      
        new Ajax.Updater(
                {
                    success:"oderinfo"
                },
                
                url,
                {
                    asynchronous:true,
                    evalScripts:false,
                    onComplete:function(request, json){
                        $("loading-details").hide();
                        return false;
                    }, 
                    onLoading:function(request, json){},
                    parameters:data
                }
            ); 
            return false;
        }

    </script>
    <?php else: ?>
    <?php
        $url = Mage::getBaseUrl();
        Mage::app()->getFrontController()->getResponse()->setRedirect($url);
    ?>
    <?php endif; ?>
 
</div>
<!-- google Recaptcha -->
<script type="text/javascript">
    function validateRecaptcha(){
                <?php if($this->helper('recaptcha')->showOnTrackOrder()){ ?>
                    if (document.getElementById("qt_hiddenRecaptcha_trackorder").value != ""){
                        document.getElementById("captcha-required").style.display = "none";
                         return true;
                    } else {
                        document.getElementById("captcha-required").style.display = "block";
                        return false;
                    }
                <?php } else { ?>
                    return true;
                <?php } ?>
            }
</script>
<script src="https://www.google.com/recaptcha/api.js?onload=onloadCallbacktrackorder&render=explicit"async defer></script>
<!-- google Recaptcha -->