<div class="box-left">
	<div class="entry-edit">
		<div class="entry-edit-head">
			<h4>Order Shipment</h4>
		</div>
		<fieldset>
			<div id="order_history_block">
				<div id="history_form" class="order-history-form">
					<div>Bulk Order Shipment</div>
					<form method="POST" enctype="multipart/form-data" action="<?php echo Mage::helper("adminhtml")->getUrl('/sales_order/bulkpdfshipment/') ?>">
						<input id="form_key" name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
						<table cellspacing="0" class="form-list">

							<tr>
								<th width="200" align="center"><?php echo $this->__('File'); ?></th>
								<th><input type="file" name="import_csvstatus" id="import_csvstatus"></th>
							</tr>
							<tr><td>&nbsp</td></tr>
							<tr>
								<th width="200" align="center"></th>
								<td colspan="2">
									<button  title="Submit Comment" type="button" class="scalable save" onclick="this.form.submit()"><span><span><span>Import Order</span></span></span></button>        </div>
								</td>
							</tr>

						</table>
					</form>
				</div>
			</div>
		</fieldset>
	</div>
</div>