<div style="width:48.5%">
  <div class="entry-edit">
    <div class="entry-edit-head">
      <h4>Order Description Export to Csv</h4>
    </div>
    <fieldset>
      <div id="order_history_block">
        <div id="history_form" class="order-history-form">
          <form method="POST" enctype="multipart/form-data" action="<?php echo Mage::helper("adminhtml")->getUrl('/sales_order/bulkdescripterexportcsv/') ?>">
            <input id="form_key" name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <table cellspacing="0" class="form-list">
              <tr>
                <th width="200" align="center"><?php echo $this->__('File'); ?></th>
                <th><input type="file" name="import_csvstatus" id="import_csvstatus"></th>
              </tr>
              <tr><td>&nbsp</td></tr>
              <tr>
                <th width="200" align="center"></th>
                <td colspan="2">
                 <button  title="Submit Comment" type="button" class="scalable save" onclick="this.form.submit()">
                    <span>
                      <span>
                        <span>Export Order</span>
                      </span>
                    </span>
                  </button>
                </td>
              </tr>
            </table>
          </form>
        </div>
      </div>
   </fieldset>
  </div>
 </div>
 <div style="width:48.5%">
  <div class="entry-edit">
    <div class="entry-edit-head">
      <h4>Order Description Import Csv</h4>
    </div>
    <fieldset>
      <div id="order_history_block">
        <div id="history_form" class="order-history-form">
          <form method="POST" enctype="multipart/form-data" action="<?php echo Mage::helper("adminhtml")->getUrl('/sales_order/bulkdescripterimportcsv/') ?>">
            <input id="form_key" name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <table cellspacing="0" class="form-list">
              <tr>
                <th width="200" align="center"><?php echo $this->__('File'); ?></th>
                <th><input type="file" name="import_csvstatus" id="import_csvstatus"></th>
              </tr>
              <tr><td>&nbsp</td></tr>
              <tr>
                <th width="200" align="center"></th>
                <td colspan="2">
                 <button  title="Submit Comment" type="button" class="scalable save" onclick="this.form.submit()">
                    <span>
                      <span>
                        <span>Import Order Descriptor</span>
                      </span>
                    </span>
                  </button>
                </td>
              </tr>
            </table>
          </form>
        </div>
      </div>
   </fieldset>
  </div>
 </div>
