<div id="review_loader"><img class="lazy" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/allday/medicine/images/loading_1.gif'; ?>" width="" height="" alt="Ropark - 0.25 mg" style="display: inline;"></div>
<div class='trustpilot_reviews trustpilot_reviews_wrapper'>
<?php
	$reviewsCollection = $this->getReviews();
	foreach ($reviewsCollection['links'] as $links) {

		if($links['rel'] == 'next-page'){
			$url = $links['href'];
		}
	}
	if(array_key_exists('reviews',$reviewsCollection)){
		foreach ($reviewsCollection['reviews'] as $reviews):
			echo '<div class="trustpilot_reviews_inner">';
			echo '<div class="consumer_name">'.$reviews['consumer']['displayName'].'</div>';
			$timpestamp =  strtotime($reviews['createdAt']);
			echo "<div class='review_date'>".date('Y-m-d',$timpestamp)."</div>";
?>
			<div class="review_img"><image src="<?php echo "http://images-static.trustpilot.com/api/stars/".$reviews['stars']."/130x24.png" ?>"></div>
<?php
			echo "<div class='review_title'>".$reviews['title']."</div>";
			echo "<div class='review_txt'>".$reviews['text']."</div>";
			echo "<div class='companyReply'><div style='color:red;font-weight: normal;
			color: #333;font-weight: 600;'>Company Reply: </div><br>".$reviews['companyReply']['text']."</div>";
			echo "</div>";
		endforeach;
?>
</div>
<div class="load_more_reviews_btn">
	<button type="button" id="load_more_reviews">Load More Reviews</button>
</div>
<div class="review_error_message">
	<span id='error_message'></span>
</div>
<?php 
    }else{
        	echo 'No Reviews';
		}
?>
<script type="text/javascript">
	jQuery(document).ready(function($){
		$('#review_loader').hide();
		var apiurl = "<?php echo $url ?>";
		$('#load_more_reviews').click(function(){
			var click_event = this;
			$('#error_message').hide();
			$(click_event).prop('disabled', true);
			$('#review_loader').show('slow');
				$.ajax({
			        url: "<?php echo $this->getUrl("trustpilot-reviews/index/ajaxReview")?>",
			        type: "post",
			        data:{apiurl:apiurl},
			        success: function (response) {
			        	var obj = JSON.parse(response);
			        	if(obj.success == 'true'){
			        		$('#review_loader').hide('slow');
			        		apiurl = obj.apiurl;
			        		$('.trustpilot_reviews').append(obj.data);
			        		$(click_event).prop('disabled', false);
			        	}else{
			        		$('#review_loader').hide('slow');
			        		$('#error_message').show();
			        		$('#error_message').html(obj.message);
			        		$(click_event).prop('disabled', false);
			        	}
			        },
			    timeout: 10000
			});
		});
	})
	 
</script>