<?php
$results=$this->getSuggestProducts();
$suggests=Mage::helper('catalogsearch')->getSuggestCollection();
$flag = 0;
?>
<ul class="ajaxsearch" ><li style="display:none"></li>
<?php
$q = Mage::app()->getRequest()->getParam('q');
if($results->count()&&$this->enabledPreview())
{

  foreach($results as $_pro)
  {
    $flag = 1;
    $pro=Mage::getModel('catalog/product')->load($_pro->getId());
    echo "<li class=\"preview\" ><a href=\"{$pro->getProductUrl()}\">";
    if($this->isShowImage())
    {
    echo "<img src=\"{$this->helper('catalog/image')->init($pro, 'small_image')->resize($this->getImageWidth(),$this->getImageHeight())}\"  />";
    }
    if($this->isShowName())
    {
	  $name = "/\b(".$q.".+?)\b/i";
	  preg_match($name,$pro->getName(),$matches1);
	  if($matches1[1] != NULL || strtolower($pro->getName()) == strtolower($q))
	   {
		echo "{$pro->getName()}";
	  }
	  else
	  {
	    $name = "/\b(".$q.".+?)\b/i";
		preg_match($name,$pro->getUsBrandName(),$matches2);
	    if($matches2[1] != NULL || strtolower($pro->getUsBrandName()) == strtolower($q))
		{
			echo "{$pro->getName()}";
		}
		else
		{
			echo "{$pro->getName()}";
		}
	  }
	}


    if($this->isShowDescription())
    {
        $description=substr($pro->getDescription(),0,$this->getNumDescriptionChar());
        $description=strip_tags(substr($description,0,strrpos($description,' ')));
        echo "<div class=\"description\">$description...</div>";
    }
    echo "</a></li>";
  }
}
    if($flag == 0){
	echo "<a href='#'><li style='cursor: default;'>No data found</li></a>";
	}


?>
</ul>
<style>
.ajaxsearch{border:solid <?php echo $this->getBorderColor().' '.$this->getBorderWidth().'px';?>}
.ajaxsearch .suggest{background:<?php echo $this->getSuggestBackground();?>; color:<?php echo $this->getSuggestColor();?>}
.ajaxsearch .suggest .amount{color:<?php echo $this->getSuggestCountColor();?>}
.ajaxsearch .preview {background:<?php echo $this->getPreviewBackground();?>}
.ajaxsearch .preview a {color:<?php echo $this->getProductNameColor();?>}
.ajaxsearch .preview .description {color:<?php echo $this->getProductDescriptionColor();?>}
.ajaxsearch .preview img {border:solid <?php echo $this->getImageBorderWidth().'px '.$this->getImageBorderColor();?> }
.header .form-search .ajaxsearch li.selected {background-color:<?php echo $this->getHoverBackground();?>}
</style>
