<?php
$customerLoggedIn = Mage::getSingleton('customer/session')->isLoggedIn();
$customerData = Mage::getSingleton('customer/session')->getCustomer();
$CustomerName = "Customer";
if($customerLoggedIn)
{
    $CustomerDataArr = $customerData->getData();
    if($CustomerDataArr['firstname'] != "")
    {
        $CustomerName = $CustomerDataArr['firstname'];
    }
}
$paymentTitle = Mage::getStoreConfig('payment/pay/title');
?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display:none">
    <h5><?php echo $paymentTitle;?></h5>
    <li>
        <p>
            Dear <?php echo ucfirst($CustomerName); ?>,<br/><br/>
        </p>
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pay_now_msg')->toHtml(); ?> 
    </li>
        <button type="button" title="<?php echo $this->__('Place Order Now') ?>" class="button btn-checkout opc-btn-checkout"><span><span><?php echo $this->__('Continue') ?></span></span></button>
    </ul>

