<?php
  $_product = $this->getProduct();
  $related_product_collection = $_product->getRelatedProductIds();
?>
<?php 
if(!empty($related_product_collection)){
?>
<div class="slider_heading">
    <h2>Related Products</h2>
</div>

<div class="related_slider">
<ol class="multiple-items">
    <?php
    foreach($related_product_collection as $_item): ?>
    <?php
        $productData = Mage::getModel('catalog/product')->load($_item);
    ?>
    <li>
        <div class="item_wrap">
            <div class="product-images">
                <a href="<?php echo $productData->getProductUrl() ?>">

                <img class="lazy" data-src="<?php echo $this->helper('catalog/image')->init($productData, 'thumbnail')->resize(50) ?>" alt="<?php echo $this->htmlEscape($productData->getName()) ?>" src="<?php echo $this->getSkinUrl('images/loading_1.gif') ?>"/>
                </a>
            </div>
            <div class="product-details">
                    <a class="p_name" href="<?php echo $productData->getProductUrl() ?>"><?php echo $this->htmlEscape($productData->getName()) ?></a>
                    <?php echo $this->getPriceHtml($productData, true) ?>
                    <?php //if ($this->helper('wishlist')->isAllow()) : ?>
                    <!-- <a href="<?php //echo $this->getAddToWishlistUrl($productData) ?>" class="wishlist-link"><?php //echo $this->__('Add to Wishlist') ?></a> -->
                    <?php //endif; ?>
            </div>
        </div>
    </li>
<?php endforeach ?>
</ol>
</div>
<?php } ?>
<script type="text/javascript">
jQuery(document).ready(function($){

    $('.multiple-items').slick({
      infinite: true,
      slidesToShow: 3,
      slidesToScroll: 1,
      autoplay: true,
      autoplaySpeed: 1000,
      responsive: [
    {
      breakpoint: 901,
      settings: {
        slidesToShow: 2
      }
    },
    {
      breakpoint: 360,
      settings: {
        slidesToShow: 1
      }
    }
    // You can unslick at a given breakpoint now by adding:
    // settings: "unslick"
    // instead of a settings object
  ]
    });

    jQuery("img.lazy").lazy();

});
</script>