<div class="box-left">
  <div class="entry-edit">
    <div class="entry-edit-head">
      <h4>Birthday Coupon</h4>
    </div>
    <fieldset>
      <div id="order_history_block">
        <div id="history_form" class="order-history-form">
          <div>Enter email to send birthday coupon</div>
          <form method="POST" enctype="multipart/form-data" action="<?php echo $this->getUrl('birthday/adminhtml_birthday/sendEmailCoupon') ?>">
            <input id="form_key" name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <table cellspacing="0" class="form-list">

              <tr>
                <th width="200" align="center"><?php echo $this->__('Email'); ?></th>
                <th><input type="text" name="email" id="email" class="required-entry validate-email"></th>
              </tr>
              <tr><td>&nbsp</td></tr>
              <tr>
                <th width="200" align="center"></th>
                <td colspan="2">
                 <button  title="Submit Comment" type="button" class="scalable save" onclick="this.form.submit()"><span><span><span>Send Coupon</span></span></span></button>        </div>
               </td>
             </tr>

           </table>
         </form>
       </div>
  </div>
   </fieldset>
 </div>
</div>